interface CountryInfo {
  code: string;
  name: string;
  dialCode: string;
  flag: string;
  currencyCode: string;
  currencySymbol: string;
  timeZone: string;
}

const countryData: CountryInfo[] = [
  { code: "US", name: "United States", dialCode: "+1", flag: "🇺🇸", currencyCode: "USD", currencySymbol: "$", timeZone: "America/New_York" },
  { code: "UK", name: "United Kingdom", dialCode: "+44", flag: "🇬🇧", currencyCode: "GBP", currencySymbol: "£", timeZone: "Europe/London" },
  { code: "CA", name: "Canada", dialCode: "+1", flag: "🇨🇦", currencyCode: "CAD", currencySymbol: "$", timeZone: "America/Toronto" },
  { code: "AE", name: "United Arab Emirates", dialCode: "+971", flag: "🇦🇪", currencyCode: "AED", currencySymbol: "د.إ", timeZone: "Asia/Dubai" },
  { code: "IN", name: "India", dialCode: "+91", flag: "🇮🇳", currencyCode: "INR", currencySymbol: "₹", timeZone: "Asia/Kolkata" },
  { code: "EU", name: "European Union", dialCode: "+388", flag: "🇪🇺", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Brussels" },
  { code: "AF", name: "Afghanistan", dialCode: "+93", flag: "🇦🇫", currencyCode: "AFN", currencySymbol: "؋", timeZone: "Asia/Kabul" },
  { code: "AX", name: "Åland Islands", dialCode: "+358", flag: "🇦🇽", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Helsinki" },
  { code: "AL", name: "Albania", dialCode: "+355", flag: "🇦🇱", currencyCode: "ALL", currencySymbol: "L", timeZone: "Europe/Tirane" },
  { code: "DZ", name: "Algeria", dialCode: "+213", flag: "🇩🇿", currencyCode: "DZD", currencySymbol: "د.ج", timeZone: "Africa/Algiers" },
  { code: "AS", name: "American Samoa", dialCode: "+1 684", flag: "🇦🇸", currencyCode: "USD", currencySymbol: "$", timeZone: "Pacific/Pago_Pago" },
  { code: "AD", name: "Andorra", dialCode: "+376", flag: "🇦🇩", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Andorra" },
  { code: "AO", name: "Angola", dialCode: "+244", flag: "🇦🇴", currencyCode: "AOA", currencySymbol: "Kz", timeZone: "Africa/Luanda" },
  { code: "AI", name: "Anguilla", dialCode: "+1 264", flag: "🇦🇮", currencyCode: "XCD", currencySymbol: "$", timeZone: "America/Anguilla" },
  { code: "AQ", name: "Antarctica", dialCode: "+672", flag: "🇦🇶", currencyCode: "USD", currencySymbol: "$", timeZone: "Antarctica/Casey" },
  { code: "AG", name: "Antigua And Barbuda", dialCode: "+1 268", flag: "🇦🇬", currencyCode: "XCD", currencySymbol: "$", timeZone: "America/Antigua" },
  { code: "AR", name: "Argentina", dialCode: "+54", flag: "🇦🇷", currencyCode: "ARS", currencySymbol: "$", timeZone: "America/Argentina/Buenos_Aires" },
  { code: "AM", name: "Armenia", dialCode: "+374", flag: "🇦🇲", currencyCode: "AMD", currencySymbol: "֏", timeZone: "Asia/Yerevan" },
  { code: "AW", name: "Aruba", dialCode: "+297", flag: "🇦🇼", currencyCode: "AWG", currencySymbol: "ƒ", timeZone: "America/Aruba" },
  { code: "AC", name: "Ascension Island", dialCode: "+247", flag: " ", currencyCode: "SHP", currencySymbol: "£", timeZone: "Atlantic/St_Helena" },
  { code: "AU", name: "Australia", dialCode: "+61", flag: "🇦🇺", currencyCode: "AUD", currencySymbol: "$", timeZone: "Australia/Sydney" },
  { code: "AT", name: "Austria", dialCode: "+43", flag: "🇦🇹", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Vienna" },
  { code: "AZ", name: "Azerbaijan", dialCode: "+994", flag: "🇦🇿", currencyCode: "AZN", currencySymbol: "₼", timeZone: "Asia/Baku" },
  { code: "BS", name: "Bahamas", dialCode: "+1 242", flag: "🇧🇸", currencyCode: "BSD", currencySymbol: "$", timeZone: "America/Nassau" },
  { code: "BH", name: "Bahrain", dialCode: "+973", flag: "🇧🇭", currencyCode: "BHD", currencySymbol: ".د.ب", timeZone: "Asia/Bahrain" },
  { code: "BD", name: "Bangladesh", dialCode: "+880", flag: "🇧🇩", currencyCode: "BDT", currencySymbol: "৳", timeZone: "Asia/Dhaka" },
  { code: "BB", name: "Barbados", dialCode: "+1 246", flag: "🇧🇧", currencyCode: "BBD", currencySymbol: "$", timeZone: "America/Barbados" },
  { code: "BY", name: "Belarus", dialCode: "+375", flag: "🇧🇾", currencyCode: "BYN", currencySymbol: "Br", timeZone: "Europe/Minsk" },
  { code: "BE", name: "Belgium", dialCode: "+32", flag: "🇧🇪", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Brussels" },
  { code: "BZ", name: "Belize", dialCode: "+501", flag: "🇧🇿", currencyCode: "BZD", currencySymbol: "BZ$", timeZone: "America/Belize" },
  { code: "BJ", name: "Benin", dialCode: "+229", flag: "🇧🇯", currencyCode: "XOF", currencySymbol: "CFA", timeZone: "Africa/Porto-Novo" },
  { code: "BM", name: "Bermuda", dialCode: "+1 441", flag: "🇧🇲", currencyCode: "BMD", currencySymbol: "$", timeZone: "Atlantic/Bermuda" },
  { code: "BT", name: "Bhutan", dialCode: "+975", flag: "🇧🇹", currencyCode: "BTN", currencySymbol: "Nu.", timeZone: "Asia/Thimphu" },
  { code: "BO", name: "Bolivia, Plurinational State Of", dialCode: "+591", flag: "🇧🇴", currencyCode: "BOB", currencySymbol: "Bs.", timeZone: "America/La_Paz" },
  { code: "BQ", name: "Bonaire, Saint Eustatius And Saba", dialCode: "+599", flag: "🇧🇶", currencyCode: "USD", currencySymbol: "$", timeZone: "America/Kralendijk" },
  { code: "BA", name: "Bosnia & Herzegovina", dialCode: "+387", flag: "🇧🇦", currencyCode: "BAM", currencySymbol: "KM", timeZone: "Europe/Sarajevo" },
  { code: "BW", name: "Botswana", dialCode: "+267", flag: "🇧🇼", currencyCode: "BWP", currencySymbol: "P", timeZone: "Africa/Gaborone" },
  { code: "BR", name: "Brazil", dialCode: "+55", flag: "🇧🇷", currencyCode: "BRL", currencySymbol: "R$", timeZone: "America/Sao_Paulo" },
  { code: "IO", name: "British Indian Ocean Territory", dialCode: "+246", flag: "🇮🇴", currencyCode: "USD", currencySymbol: "$", timeZone: "Indian/Chagos" },
  { code: "BN", name: "Brunei Darussalam", dialCode: "+673", flag: "🇧🇳", currencyCode: "BND", currencySymbol: "$", timeZone: "Asia/Brunei" },
  { code: "BG", name: "Bulgaria", dialCode: "+359", flag: "🇧🇬", currencyCode: "BGN", currencySymbol: "лв", timeZone: "Europe/Sofia" },
  { code: "BF", name: "Burkina Faso", dialCode: "+226", flag: "🇧🇫", currencyCode: "XOF", currencySymbol: "CFA", timeZone: "Africa/Ouagadougou" },
  { code: "BI", name: "Burundi", dialCode: "+257", flag: "🇧🇮", currencyCode: "BIF", currencySymbol: "FBu", timeZone: "Africa/Bujumbura" },
  { code: "CV", name: "Cabo Verde", dialCode: "+238", flag: "🇨🇻", currencyCode: "CVE", currencySymbol: "$", timeZone: "Atlantic/Cape_Verde" },
  { code: "KH", name: "Cambodia", dialCode: "+855", flag: "🇰🇭", currencyCode: "KHR", currencySymbol: "៛", timeZone: "Asia/Phnom_Penh" },
  { code: "CM", name: "Cameroon", dialCode: "+237", flag: "🇨🇲", currencyCode: "XAF", currencySymbol: "FCFA", timeZone: "Africa/Douala" },
  { code: "KY", name: "Cayman Islands", dialCode: "+1 345", flag: "🇰🇾", currencyCode: "KYD", currencySymbol: "$", timeZone: "America/Cayman" },
  { code: "CF", name: "Central African Republic", dialCode: "+236", flag: "🇨🇫", currencyCode: "XAF", currencySymbol: "FCFA", timeZone: "Africa/Bangui" },
  { code: "TD", name: "Chad", dialCode: "+235", flag: "🇹🇩", currencyCode: "XAF", currencySymbol: "FCFA", timeZone: "Africa/Ndjamena" },
  { code: "CL", name: "Chile", dialCode: "+56", flag: "🇨🇱", currencyCode: "CLP", currencySymbol: "$", timeZone: "America/Santiago" },
  { code: "CN", name: "China", dialCode: "+86", flag: "🇨🇳", currencyCode: "CNY", currencySymbol: "¥", timeZone: "Asia/Shanghai" },
  { code: "CX", name: "Christmas Island", dialCode: "+61", flag: "🇨🇽", currencyCode: "AUD", currencySymbol: "$", timeZone: "Indian/Christmas" },
  { code: "CC", name: "Cocos (Keeling) Islands", dialCode: "+61", flag: "🇨🇨", currencyCode: "AUD", currencySymbol: "$", timeZone: "Indian/Cocos" },
  { code: "CO", name: "Colombia", dialCode: "+57", flag: "🇨🇴", currencyCode: "COP", currencySymbol: "$", timeZone: "America/Bogota" },
  { code: "KM", name: "Comoros", dialCode: "+269", flag: "🇰🇲", currencyCode: "KMF", currencySymbol: "CF", timeZone: "Indian/Comoro" },
  { code: "CK", name: "Cook Islands", dialCode: "+682", flag: "🇨🇰", currencyCode: "NZD", currencySymbol: "$", timeZone: "Pacific/Rarotonga" },
  { code: "CR", name: "Costa Rica", dialCode: "+506", flag: "🇨🇷", currencyCode: "CRC", currencySymbol: "₡", timeZone: "America/Costa_Rica" },
  { code: "CI", name: "Côte d'Ivoire", dialCode: "+225", flag: "🇨🇮", currencyCode: "XOF", currencySymbol: "CFA", timeZone: "Africa/Abidjan" },
  { code: "HR", name: "Croatia", dialCode: "+385", flag: "🇭🇷", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Zagreb" },
  { code: "CU", name: "Cuba", dialCode: "+53", flag: "🇨🇺", currencyCode: "CUP", currencySymbol: "$", timeZone: "America/Havana" },
  { code: "CW", name: "Curacao", dialCode: "+599", flag: "🇨🇼", currencyCode: "ANG", currencySymbol: "ƒ", timeZone: "America/Curacao" },
  { code: "CY", name: "Cyprus", dialCode: "+357", flag: "🇨🇾", currencyCode: "EUR", currencySymbol: "€", timeZone: "Asia/Nicosia" },
  { code: "CZ", name: "Czech Republic", dialCode: "+420", flag: "🇨🇿", currencyCode: "CZK", currencySymbol: "Kč", timeZone: "Europe/Prague" },
  { code: "CD", name: "Democratic Republic Of Congo", dialCode: "+243", flag: "🇨🇩", currencyCode: "CDF", currencySymbol: "FC", timeZone: "Africa/Kinshasa" },
  { code: "DK", name: "Denmark", dialCode: "+45", flag: "🇩🇰", currencyCode: "DKK", currencySymbol: "kr", timeZone: "Europe/Copenhagen" },
  { code: "DJ", name: "Djibouti", dialCode: "+253", flag: "🇩🇯", currencyCode: "DJF", currencySymbol: "Fdj", timeZone: "Africa/Djibouti" },
  { code: "DM", name: "Dominica", dialCode: "+1 767", flag: "🇩🇲", currencyCode: "XCD", currencySymbol: "$", timeZone: "America/Dominica" },
  { code: "DO", name: "Dominican Republic", dialCode: "+1", flag: "🇩🇴", currencyCode: "DOP", currencySymbol: "RD$", timeZone: "America/Dominica" },
  { code: "EC", name: "Ecuador", dialCode: "+593", flag: "🇪🇨", currencyCode: "USD", currencySymbol: "$", timeZone: "America/Guayaquil" },
  { code: "EG", name: "Egypt", dialCode: "+20", flag: "🇪🇬", currencyCode: "EGP", currencySymbol: "E£", timeZone: "Africa/Cairo" },
  { code: "SV", name: "El Salvador", dialCode: "+503", flag: "🇸🇻", currencyCode: "USD", currencySymbol: "$", timeZone: "America/El_Salvador" },
  { code: "GQ", name: "Equatorial Guinea", dialCode: "+240", flag: "🇬🇶", currencyCode: "XAF", currencySymbol: "FCFA", timeZone: "Africa/Malabo" },
  { code: "ER", name: "Eritrea", dialCode: "+291", flag: "🇪🇷", currencyCode: "ERN", currencySymbol: "Nfk", timeZone: "Africa/Asmara" },
  { code: "EE", name: "Estonia", dialCode: "+372", flag: "🇪🇪", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Tallinn" },
  { code: "ET", name: "Ethiopia", dialCode: "+251", flag: "🇪🇹", currencyCode: "ETB", currencySymbol: "Br", timeZone: "Africa/Addis_Ababa" },
  { code: "EU", name: "European Union", dialCode: "+388", flag: "🇪🇺", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Brussels" },
  { code: "FK", name: "Falkland Islands", dialCode: "+500", flag: "🇫🇰", currencyCode: "FKP", currencySymbol: "£", timeZone: "Atlantic/Stanley" },
  { code: "FO", name: "Faroe Islands", dialCode: "+298", flag: "🇫🇴", currencyCode: "DKK", currencySymbol: "kr", timeZone: "Atlantic/Faroe" },
  { code: "FJ", name: "Fiji", dialCode: "+679", flag: "🇫🇯", currencyCode: "FJD", currencySymbol: "$", timeZone: "Pacific/Fiji" },
  { code: "FI", name: "Finland", dialCode: "+358", flag: "🇫🇮", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Helsinki" },
  { code: "FR", name: "France", dialCode: "+33", flag: "🇫🇷", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Paris" },
  { code: "GF", name: "French Guiana", dialCode: "+594", flag: "🇬🇫", currencyCode: "EUR", currencySymbol: "€", timeZone: "America/Cayenne" },
  { code: "PF", name: "French Polynesia", dialCode: "+689", flag: "🇵🇫", currencyCode: "XPF", currencySymbol: "₣", timeZone: "Pacific/Tahiti" },
  { code: "GA", name: "Gabon", dialCode: "+241", flag: "🇬🇦", currencyCode: "XAF", currencySymbol: "FCFA", timeZone: "Africa/Libreville" },
  { code: "GM", name: "Gambia", dialCode: "+220", flag: "🇬🇲", currencyCode: "GMD", currencySymbol: "D", timeZone: "Africa/Banjul" },
  { code: "GE", name: "Georgia", dialCode: "+995", flag: "🇬🇪", currencyCode: "GEL", currencySymbol: "₾", timeZone: "Asia/Tbilisi" },
  { code: "DE", name: "Germany", dialCode: "+49", flag: "🇩🇪", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Berlin" },
  { code: "GH", name: "Ghana", dialCode: "+233", flag: "🇬🇭", currencyCode: "GHS", currencySymbol: "₵", timeZone: "Africa/Accra" },
  { code: "GI", name: "Gibraltar", dialCode: "+350", flag: "🇬🇮", currencyCode: "GIP", currencySymbol: "£", timeZone: "Europe/Gibraltar" },
  { code: "GR", name: "Greece", dialCode: "+30", flag: "🇬🇷", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Athens" },
  { code: "GL", name: "Greenland", dialCode: "+299", flag: "🇬🇱", currencyCode: "DKK", currencySymbol: "kr", timeZone: "America/Nuuk" },
  { code: "GD", name: "Grenada", dialCode: "+1 473", flag: "🇬🇩", currencyCode: "XCD", currencySymbol: "$", timeZone: "America/Grenada" },
  { code: "GP", name: "Guadeloupe", dialCode: "+590", flag: "🇬🇵", currencyCode: "EUR", currencySymbol: "€", timeZone: "America/Guadeloupe" },
  { code: "GU", name: "Guam", dialCode: "+1 671", flag: "🇬🇺", currencyCode: "USD", currencySymbol: "$", timeZone: "Pacific/Guam" },
  { code: "GT", name: "Guatemala", dialCode: "+502", flag: "🇬🇹", currencyCode: "GTQ", currencySymbol: "Q", timeZone: "America/Guatemala" },
  { code: "GG", name: "Guernsey", dialCode: "+44", flag: "🇬🇬", currencyCode: "GBP", currencySymbol: "£", timeZone: "Europe/Guernsey" },
  { code: "GN", name: "Guinea", dialCode: "+224", flag: "🇬🇳", currencyCode: "GNF", currencySymbol: "FG", timeZone: "Africa/Conakry" },
  { code: "GW", name: "Guinea-Bissau", dialCode: "+245", flag: "🇬🇼", currencyCode: "XOF", currencySymbol: "CFA", timeZone: "Africa/Bissau" },
  { code: "GY", name: "Guyana", dialCode: "+595", flag: "🇬🇾", currencyCode: "GYD", currencySymbol: "$", timeZone: "America/Guyana" },
  { code: "HT", name: "Haiti", dialCode: "+509", flag: "🇭🇹", currencyCode: "HTG", currencySymbol: "G", timeZone: "America/Port-au-Prince" },
  { code: "HN", name: "Honduras", dialCode: "+504", flag: "🇭🇳", currencyCode: "HNL", currencySymbol: "L", timeZone: "America/Tegucigalpa" },
  { code: "HK", name: "Hong Kong", dialCode: "+852", flag: "🇭🇰", currencyCode: "HKD", currencySymbol: "$", timeZone: "Asia/Hong_Kong" },
  { code: "HU", name: "Hungary", dialCode: "+36", flag: "🇭🇺", currencyCode: "HUF", currencySymbol: "Ft", timeZone: "Europe/Budapest" },
  { code: "IS", name: "Iceland", dialCode: "+354", flag: "🇮🇸", currencyCode: "ISK", currencySymbol: "kr", timeZone: "Atlantic/Reykjavik" },
  { code: "IN", name: "India", dialCode: "+91", flag: "🇮🇳", currencyCode: "INR", currencySymbol: "₹", timeZone: "Asia/Kolkata" },
  { code: "ID", name: "Indonesia", dialCode: "+62", flag: "🇮🇩", currencyCode: "IDR", currencySymbol: "Rp", timeZone: "Asia/Jakarta" },
  { code: "IR", name: "Iran, Islamic Republic Of", dialCode: "+98", flag: "🇮🇷", currencyCode: "IRR", currencySymbol: "﷼", timeZone: "Asia/Tehran" },
  { code: "IQ", name: "Iraq", dialCode: "+964", flag: "🇮🇶", currencyCode: "IQD", currencySymbol: "د.ع", timeZone: "Asia/Baghdad" },
  { code: "IE", name: "Ireland", dialCode: "+353", flag: "🇮🇪", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Dublin" },
  { code: "IM", name: "Isle Of Man", dialCode: "+44", flag: "🇮🇲", currencyCode: "GBP", currencySymbol: "£", timeZone: "Europe/Isle_of_Man" },
  { code: "IL", name: "Israel", dialCode: "+972", flag: "🇮🇱", currencyCode: "ILS", currencySymbol: "₪", timeZone: "Asia/Jerusalem" },
  { code: "IT", name: "Italy", dialCode: "+39", flag: "🇮🇹", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Rome" },
  { code: "JM", name: "Jamaica", dialCode: "+1", flag: "🇯🇲", currencyCode: "JMD", currencySymbol: "$", timeZone: "America/Jamaica" },
  { code: "JP", name: "Japan", dialCode: "+81", flag: "🇯🇵", currencyCode: "JPY", currencySymbol: "¥", timeZone: "Asia/Tokyo" },
  { code: "JE", name: "Jersey", dialCode: "+44", flag: "🇯🇪", currencyCode: "GBP", currencySymbol: "£", timeZone: "Europe/Jersey" },
  { code: "JO", name: "Jordan", dialCode: "+962", flag: "🇯🇴", currencyCode: "JOD", currencySymbol: "JD", timeZone: "Asia/Amman" },
  { code: "KZ", name: "Kazakhstan", dialCode: "+7", flag: "🇰🇿", currencyCode: "KZT", currencySymbol: "₸", timeZone: "Asia/Almaty" },
  { code: "KE", name: "Kenya", dialCode: "+254", flag: "🇰🇪", currencyCode: "KES", currencySymbol: "KSh", timeZone: "Africa/Nairobi" },
  { code: "KI", name: "Kiribati", dialCode: "+686", flag: "🇰🇮", currencyCode: "AUD", currencySymbol: "$", timeZone: "Pacific/Tarawa" },
  { code: "KP", name: "Korea, Democratic People's Republic Of", dialCode: "+850", flag: "🇰🇵", currencyCode: "KPW", currencySymbol: "₩", timeZone: "Asia/Pyongyang" },
  { code: "KR", name: "Korea, Republic Of", dialCode: "+82", flag: "🇰🇷", currencyCode: "KRW", currencySymbol: "₩", timeZone: "Asia/Seoul" },
  { code: "XK", name: "Kosovo", dialCode: "+383", flag: " ", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Belgrade" },
  { code: "KW", name: "Kuwait", dialCode: "+965", flag: "🇰🇼", currencyCode: "KWD", currencySymbol: "KD", timeZone: "Asia/Kuwait" },
  { code: "KG", name: "Kyrgyzstan", dialCode: "+996", flag: "🇰🇬", currencyCode: "KGS", currencySymbol: "лв", timeZone: "Asia/Bishkek" },
  { code: "LA", name: "Lao People's Democratic Republic", dialCode: "+856", flag: "🇱🇦", currencyCode: "LAK", currencySymbol: "₭", timeZone: "Asia/Vientiane" },
  { code: "LV", name: "Latvia", dialCode: "+371", flag: "🇱🇻", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Riga" },
  { code: "LB", name: "Lebanon", dialCode: "+961", flag: "🇱🇧", currencyCode: "LBP", currencySymbol: "ل.ل", timeZone: "Asia/Beirut" },
  { code: "LS", name: "Lesotho", dialCode: "+266", flag: "🇱🇸", currencyCode: "LSL", currencySymbol: "L", timeZone: "Africa/Maseru" },
  { code: "LR", name: "Liberia", dialCode: "+231", flag: "🇱🇷", currencyCode: "LRD", currencySymbol: "$", timeZone: "Africa/Monrovia" },
  { code: "LY", name: "Libya", dialCode: "+218", flag: "🇱🇾", currencyCode: "LYD", currencySymbol: "ل.د", timeZone: "Africa/Tripoli" },
  { code: "LI", name: "Liechtenstein", dialCode: "+423", flag: "🇱🇮", currencyCode: "CHF", currencySymbol: "CHF", timeZone: "Europe/Vaduz" },
  { code: "LT", name: "Lithuania", dialCode: "+370", flag: "🇱🇹", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Vilnius" },
  { code: "LU", name: "Luxembourg", dialCode: "+352", flag: "🇱🇺", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Luxembourg" },
  { code: "MO", name: "Macao", dialCode: "+853", flag: "🇲🇴", currencyCode: "MOP", currencySymbol: "MOP$", timeZone: "Asia/Macau" },
  { code: "MK", name: "Macedonia, The Former Yugoslav Republic Of", dialCode: "+389", flag: "🇲🇰", currencyCode: "MKD", currencySymbol: "ден", timeZone: "Europe/Skopje" },
  { code: "MG", name: "Madagascar", dialCode: "+261", flag: "🇲🇬", currencyCode: "MGA", currencySymbol: "Ar", timeZone: "Indian/Antananarivo" },
  { code: "MW", name: "Malawi", dialCode: "+265", flag: "🇲🇼", currencyCode: "MWK", currencySymbol: "MK", timeZone: "Africa/Blantyre" },
  { code: "MY", name: "Malaysia", dialCode: "+60", flag: "🇲🇾", currencyCode: "MYR", currencySymbol: "RM", timeZone: "Asia/Kuala_Lumpur" },
  { code: "MV", name: "Maldives", dialCode: "+960", flag: "🇲🇻", currencyCode: "MVR", currencySymbol: ".ރ", timeZone: "Indian/Maldives" },
  { code: "ML", name: "Mali", dialCode: "+223", flag: "🇲🇱", currencyCode: "XOF", currencySymbol: "CFA", timeZone: "Africa/Bamako" },
  { code: "MT", name: "Malta", dialCode: "+356", flag: "🇲🇹", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Malta" },
  { code: "MH", name: "Marshall Islands", dialCode: "+692", flag: "🇲🇷", currencyCode: "USD", currencySymbol: "$", timeZone: "Pacific/Majuro" },
  { code: "MQ", name: "Martinique", dialCode: "+596", flag: "🇲🇶", currencyCode: "EUR", currencySymbol: "€", timeZone: "America/Martinique" },
  { code: "MR", name: "Mauritania", dialCode: "+222", flag: "🇲🇷", currencyCode: "MRU", currencySymbol: "UM", timeZone: "Africa/Nouakchott" },
  { code: "MU", name: "Mauritius", dialCode: "+230", flag: "🇲🇺", currencyCode: "MUR", currencySymbol: "₨", timeZone: "Indian/Mauritius" },
  { code: "YT", name: "Mayotte", dialCode: "+262", flag: "🇾🇹", currencyCode: "EUR", currencySymbol: "€", timeZone: "Indian/Mayotte" },
  { code: "MX", name: "Mexico", dialCode: "+52", flag: "🇲🇽", currencyCode: "MXN", currencySymbol: "$", timeZone: "America/Mexico_City" },
  { code: "FM", name: "Micronesia, Federated States Of", dialCode: "+691", flag: "🇫🇲", currencyCode: "USD", currencySymbol: "$", timeZone: "Pacific/Pohnpei" },
  { code: "MD", name: "Moldova", dialCode: "+373", flag: "🇲🇩", currencyCode: "MDL", currencySymbol: "L", timeZone: "Europe/Chisinau" },
  { code: "MC", name: "Monaco", dialCode: "+377", flag: "🇲🇨", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Monaco" },
  { code: "MN", name: "Mongolia", dialCode: "+976", flag: "🇲🇳", currencyCode: "MNT", currencySymbol: "₮", timeZone: "Asia/Ulaanbaatar" },
  { code: "ME", name: "Montenegro", dialCode: "+382", flag: "🇲🇪", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Podgorica" },
  { code: "MS", name: "Montserrat", dialCode: "+1 664", flag: "🇲🇸", currencyCode: "XCD", currencySymbol: "$", timeZone: "America/Montserrat" },
  { code: "MA", name: "Morocco", dialCode: "+212", flag: "🇲🇦", currencyCode: "MAD", currencySymbol: "د.م.", timeZone: "Africa/Casablanca" },
  { code: "MZ", name: "Mozambique", dialCode: "+258", flag: "🇲🇿", currencyCode: "MZN", currencySymbol: "MT", timeZone: "Africa/Maputo" },
  { code: "MM", name: "Myanmar", dialCode: "+95", flag: "🇲🇲", currencyCode: "MMK", currencySymbol: "K", timeZone: "Asia/Yangon" },
  { code: "NA", name: "Namibia", dialCode: "+264", flag: "🇳🇦", currencyCode: "NAD", currencySymbol: "$", timeZone: "Africa/Windhoek" },
  { code: "NR", name: "Nauru", dialCode: "+674", flag: "🇳🇷", currencyCode: "AUD", currencySymbol: "$", timeZone: "Pacific/Nauru" },
  { code: "NP", name: "Nepal", dialCode: "+977", flag: "🇳🇵", currencyCode: "NPR", currencySymbol: "रू", timeZone: "Asia/Kathmandu" },
  { code: "NL", name: "Netherlands", dialCode: "+31", flag: "🇳🇱", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Amsterdam" },
  { code: "NC", name: "New Caledonia", dialCode: "+687", flag: "🇳🇨", currencyCode: "XPF", currencySymbol: "₣", timeZone: "Pacific/Noumea" },
  { code: "NZ", name: "New Zealand", dialCode: "+64", flag: "🇳🇿", currencyCode: "NZD", currencySymbol: "$", timeZone: "Pacific/Auckland" },
  { code: "NI", name: "Nicaragua", dialCode: "+505", flag: "🇳🇮", currencyCode: "NIO", currencySymbol: "C$", timeZone: "America/Managua" },
  { code: "NE", name: "Niger", dialCode: "+227", flag: "🇳🇪", currencyCode: "XOF", currencySymbol: "CFA", timeZone: "Africa/Niamey" },
  { code: "NG", name: "Nigeria", dialCode: "+234", flag: "🇳🇬", currencyCode: "NGN", currencySymbol: "₦", timeZone: "Africa/Lagos" },
  { code: "NU", name: "Niue", dialCode: "+683", flag: "🇳🇺", currencyCode: "NZD", currencySymbol: "$", timeZone: "Pacific/Niue" },
  { code: "NF", name: "Norfolk Island", dialCode: "+672", flag: "🇳🇫", currencyCode: "AUD", currencySymbol: "$", timeZone: "Pacific/Norfolk" },
  { code: "MP", name: "Northern Mariana Islands", dialCode: "+1 670", flag: "🇲🇵", currencyCode: "USD", currencySymbol: "$", timeZone: "Pacific/Saipan" },
  { code: "NO", name: "Norway", dialCode: "+47", flag: "🇳🇴", currencyCode: "NOK", currencySymbol: "kr", timeZone: "Europe/Oslo" },
  { code: "OM", name: "Oman", dialCode: "+968", flag: "🇴🇲", currencyCode: "OMR", currencySymbol: "﷼", timeZone: "Asia/Muscat" },
  { code: "PK", name: "Pakistan", dialCode: "+92", flag: "🇵🇰", currencyCode: "PKR", currencySymbol: "₨", timeZone: "Asia/Karachi" },
  { code: "PW", name: "Palau", dialCode: "+680", flag: "🇵🇼", currencyCode: "USD", currencySymbol: "$", timeZone: "Pacific/Palau" },
  { code: "PS", name: "Palestinian Territory, Occupied", dialCode: "+970", flag: "🇵🇸", currencyCode: "ILS", currencySymbol: "₪", timeZone: "Asia/Gaza" },
  { code: "PA", name: "Panama", dialCode: "+507", flag: "🇵🇦", currencyCode: "PAB", currencySymbol: "B/.", timeZone: "America/Panama" },
  { code: "PG", name: "Papua New Guinea", dialCode: "+675", flag: "🇵🇬", currencyCode: "PGK", currencySymbol: "K", timeZone: "Pacific/Port_Moresby" },
  { code: "PY", name: "Paraguay", dialCode: "+595", flag: "🇵🇾", currencyCode: "PYG", currencySymbol: "₲", timeZone: "America/Asuncion" },
  { code: "PE", name: "Peru", dialCode: "+51", flag: "🇵🇪", currencyCode: "PEN", currencySymbol: "S/.", timeZone: "America/Lima" },
  { code: "PH", name: "Philippines", dialCode: "+63", flag: "🇵🇷", currencyCode: "PHP", currencySymbol: "₱", timeZone: "Asia/Manila" },
  { code: "PN", name: "Pitcairn", dialCode: "+872", flag: "🇵🇳", currencyCode: "NZD", currencySymbol: "$", timeZone: "Pacific/Pitcairn" },
  { code: "PL", name: "Poland", dialCode: "+48", flag: "🇵🇱", currencyCode: "PLN", currencySymbol: "zł", timeZone: "Europe/Warsaw" },
  { code: "PT", name: "Portugal", dialCode: "+351", flag: "🇵🇹", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Lisbon" },
  { code: "PR", name: "Puerto Rico", dialCode: "+1", flag: "🇵🇷", currencyCode: "USD", currencySymbol: "$", timeZone: "America/Puerto_Rico" },
  { code: "QA", name: "Qatar", dialCode: "+974", flag: "🇶🇦", currencyCode: "QAR", currencySymbol: "﷼", timeZone: "Asia/Qatar" },
  { code: "CG", name: "Republic Of Congo", dialCode: "+242", flag: "🇨🇬", currencyCode: "XAF", currencySymbol: "FCFA", timeZone: "Africa/Brazzaville" },
  { code: "RE", name: "Reunion", dialCode: "+262", flag: "🇷🇪", currencyCode: "EUR", currencySymbol: "€", timeZone: "Indian/Reunion" },
  { code: "RO", name: "Romania", dialCode: "+40", flag: "🇷🇴", currencyCode: "RON", currencySymbol: "lei", timeZone: "Europe/Bucharest" },
  { code: "RU", name: "Russian Federation", dialCode: "+7", flag: "🇷🇺", currencyCode: "RUB", currencySymbol: "₽", timeZone: "Europe/Moscow" },
  { code: "RW", name: "Rwanda", dialCode: "+250", flag: "🇷🇼", currencyCode: "RWF", currencySymbol: "FRw", timeZone: "Africa/Kigali" },
  { code: "BL", name: "Saint Barthélémy", dialCode: "+590", flag: "🇧🇱", currencyCode: "EUR", currencySymbol: "€", timeZone: "America/St_Barthelemy" },
  { code: "SH", name: "Saint Helena, Ascension And Tristan Da Cunha", dialCode: "+290", flag: "🇸🇭", currencyCode: "SHP", currencySymbol: "£", timeZone: "Atlantic/St_Helena" },
  { code: "KN", name: "Saint Kitts And Nevis", dialCode: "+1 869", flag: "🇰🇳", currencyCode: "XCD", currencySymbol: "$", timeZone: "America/St_Kitts" },
  { code: "LC", name: "Saint Lucia", dialCode: "+1 758", flag: "🇱🇨", currencyCode: "XCD", currencySymbol: "$", timeZone: "America/St_Lucia" },
  { code: "MF", name: "Saint Martin", dialCode: "+590", flag: "🇲🇫", currencyCode: "EUR", currencySymbol: "€", timeZone: "America/Marigot" },
  { code: "PM", name: "Saint Pierre And Miquelon", dialCode: "+508", flag: "🇵🇲", currencyCode: "EUR", currencySymbol: "€", timeZone: "America/Miquelon" },
  { code: "VC", name: "Saint Vincent And The Grenadines", dialCode: "+1 784", flag: "🇻🇨", currencyCode: "XCD", currencySymbol: "$", timeZone: "America/St_Vincent" },
  { code: "WS", name: "Samoa", dialCode: "+685", flag: "🇼🇸", currencyCode: "WST", currencySymbol: "T", timeZone: "Pacific/Apia" },
  { code: "SM", name: "San Marino", dialCode: "+378", flag: "🇸🇲", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/San_Marino" },
  { code: "ST", name: "Sao Tome and Principe", dialCode: "+239", flag: "🇸🇹", currencyCode: "STN", currencySymbol: "Db", timeZone: "Africa/Sao_Tome" },
  { code: "SA", name: "Saudi Arabia", dialCode: "+966", flag: "🇸🇦", currencyCode: "SAR", currencySymbol: "﷼", timeZone: "Asia/Riyadh" },
  { code: "SN", name: "Senegal", dialCode: "+221", flag: "🇸🇳", currencyCode: "XOF", currencySymbol: "CFA", timeZone: "Africa/Dakar" },
  { code: "RS", name: "Serbia", dialCode: "+381", flag: "🇷🇸", currencyCode: "RSD", currencySymbol: "дин.", timeZone: "Europe/Belgrade" },
  { code: "SC", name: "Seychelles", dialCode: "+248", flag: "🇸🇨", currencyCode: "SCR", currencySymbol: "₨", timeZone: "Indian/Mahe" },
  { code: "SL", name: "Sierra Leone", dialCode: "+232", flag: "🇸🇱", currencyCode: "SLL", currencySymbol: "Le", timeZone: "Africa/Freetown" },
  { code: "SG", name: "Singapore", dialCode: "+65", flag: "🇸🇬", currencyCode: "SGD", currencySymbol: "$", timeZone: "Asia/Singapore" },
  { code: "SX", name: "Sint Maarten", dialCode: "+1 721", flag: "🇸🇽", currencyCode: "ANG", currencySymbol: "ƒ", timeZone: "America/Lower_Princes" },
  { code: "SK", name: "Slovakia", dialCode: "+421", flag: "🇸🇰", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Bratislava" },
  { code: "SI", name: "Slovenia", dialCode: "+386", flag: "🇸🇮", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Ljubljana" },
  { code: "SB", name: "Solomon Islands", dialCode: "+677", flag: "🇸🇧", currencyCode: "SBD", currencySymbol: "$", timeZone: "Pacific/Guadalcanal" },
  { code: "SO", name: "Somalia", dialCode: "+252", flag: "🇸🇴", currencyCode: "SOS", currencySymbol: "Sh", timeZone: "Africa/Mogadishu" },
  { code: "ZA", name: "South Africa", dialCode: "+27", flag: "🇿🇦", currencyCode: "ZAR", currencySymbol: "R", timeZone: "Africa/Johannesburg" },
  { code: "SS", name: "South Sudan", dialCode: "+211", flag: "🇸🇸", currencyCode: "SSP", currencySymbol: "£", timeZone: "Africa/Juba" },
  { code: "ES", name: "Spain", dialCode: "+34", flag: "🇪🇸", currencyCode: "EUR", currencySymbol: "€", timeZone: "Europe/Madrid" },
  { code: "LK", name: "Sri Lanka", dialCode: "+94", flag: "🇱🇰", currencyCode: "LKR", currencySymbol: "₨", timeZone: "Asia/Colombo" },
  { code: "SD", name: "Sudan", dialCode: "+249", flag: "🇸🇩", currencyCode: "SDG", currencySymbol: "ج.س.", timeZone: "Africa/Khartoum" },
  { code: "SR", name: "Suriname", dialCode: "+597", flag: "🇸🇷", currencyCode: "SRD", currencySymbol: "$", timeZone: "America/Paramaribo" },
  { code: "SJ", name: "Svalbard And Jan Mayen", dialCode: "+47", flag: "🇸🇯", currencyCode: "NOK", currencySymbol: "kr", timeZone: "Arctic/Longyearbyen" },
  { code: "SZ", name: "Swaziland", dialCode: "+268", flag: "🇸🇿", currencyCode: "SZL", currencySymbol: "L", timeZone: "Africa/Mbabane" },
  { code: "SE", name: "Sweden", dialCode: "+46", flag: "🇸🇪", currencyCode: "SEK", currencySymbol: "kr", timeZone: "Europe/Stockholm" },
  { code: "CH", name: "Switzerland", dialCode: "+41", flag: "🇨🇭", currencyCode: "CHF", currencySymbol: "CHF", timeZone: "Europe/Zurich" },
  { code: "SY", name: "Syrian Arab Republic", dialCode: "+963", flag: "🇸🇾", currencyCode: "SYP", currencySymbol: "£", timeZone: "Asia/Damascus" },
  { code: "TW", name: "Taiwan", dialCode: "+886", flag: "🇹🇼", currencyCode: "TWD", currencySymbol: "NT$", timeZone: "Asia/Taipei" },
  { code: "TJ", name: "Tajikistan", dialCode: "+992", flag: "🇹🇯", currencyCode: "TJS", currencySymbol: "ЅМ", timeZone: "Asia/Dushanbe" },
  { code: "TZ", name: "Tanzania, United Republic Of", dialCode: "+255", flag: "🇹🇿", currencyCode: "TZS", currencySymbol: "TSh", timeZone: "Africa/Dar_es_Salaam" },
  { code: "TH", name: "Thailand", dialCode: "+66", flag: "🇹🇭", currencyCode: "THB", currencySymbol: "฿", timeZone: "Asia/Bangkok" },
  { code: "TL", name: "Timor-Leste, Democratic Republic of", dialCode: "+670", flag: "🇹🇱", currencyCode: "USD", currencySymbol: "$", timeZone: "Asia/Dili" },
  { code: "TG", name: "Togo", dialCode: "+228", flag: "🇹🇬", currencyCode: "XOF", currencySymbol: "CFA", timeZone: "Africa/Lagos" },
  { code: "TK", name: "Tokelau", dialCode: "+690", flag: "🇹🇰", currencyCode: "NZD", currencySymbol: "$", timeZone: "Pacific/Fakaofo" },
  { code: "TO", name: "Tonga", dialCode: "+676", flag: "🇹🇴", currencyCode: "TOP", currencySymbol: "T$", timeZone: "Pacific/Tongatapu" },
  { code: "TT", name: "Trinidad And Tobago", dialCode: "+1 868", flag: "🇹🇹", currencyCode: "TTD", currencySymbol: "$", timeZone: "America/Port_of_Arthur" },
  { code: "TA", name: "Tristan de Cunha", dialCode: "+290", flag: " ", currencyCode: "ANG", currencySymbol: "ƒ", timeZone: "America/Port_of_Arthur" },
  { code: "TN", name: "Tunisia", dialCode: "+216", flag: "🇹🇳", currencyCode: "TND", currencySymbol: "د.ت", timeZone: "Africa/Tunis" },
  { code: "TR", name: "Turkey", dialCode: "+90", flag: "🇹🇷", currencyCode: "TRY", currencySymbol: "₺", timeZone: "Europe/Istanbul" },
  { code: "TM", name: "Turkmenistan", dialCode: "+993", flag: "🇹🇲", currencyCode: "TMT", currencySymbol: "m", timeZone: "Asia/Ashgabat" },
  { code: "TC", name: "Turks And Caicos Islands", dialCode: "+1 649", flag: "🇹Ｃ", currencyCode: "USD", currencySymbol: "$", timeZone: "America/Port_of_Arthur" },
  { code: "TV", name: "Tuvalu", dialCode: "+688", flag: "🇹🇻", currencyCode: "AUD", currencySymbol: "$", timeZone: "America/Port_of_Arthur" },
  { code: "UG", name: "Uganda", dialCode: "+256", flag: "🇺🇬", currencyCode: "UGX", currencySymbol: "USh", timeZone: "America/Port_of_Arthur" },
  { code: "UA", name: "Ukraine", dialCode: "+380", flag: "🇺🇦", currencyCode: "UAH", currencySymbol: "₴", timeZone: "America/Port_of_Arthur" },
  { code: "UM", name: "United States Minor Outlying Islands", dialCode: "+1", flag: "🇺🇲", currencyCode: "USD", currencySymbol: "$", timeZone: "America/Port_of_Arthur" },
  { code: "UY", name: "Uruguay", dialCode: "+598", flag: "🇺🇾", currencyCode: "UYU", currencySymbol: "$", timeZone: "America/Port_of_Arthur" },
  { code: "UZ", name: "Uzbekistan", dialCode: "+998", flag: "🇺🇿", currencyCode: "UZS", currencySymbol: "сўм", timeZone: "America/Port_of_Arthur" },
  { code: "VU", name: "Vanuatu", dialCode: "+678", flag: "🇻🇺", currencyCode: "VUV", currencySymbol: "VT", timeZone: "America/Port_of_Arthur" },
  { code: "VA", name: "Vatican City State", dialCode: "+379", flag: "🇻🇦", currencyCode: "EUR", currencySymbol: "€", timeZone: "America/Port_of_Arthur" },
  { code: "VE", name: "Venezuela, Bolivarian Republic Of", dialCode: "+58", flag: "🇻🇪", currencyCode: "VES", currencySymbol: "Bs", timeZone: "America/Port_of_Arthur" },
  { code: "VN", name: "Viet Nam", dialCode: "+84", flag: "🇻🇳", currencyCode: "VND", currencySymbol: "₫", timeZone: "America/Port_of_Arthur" },
  { code: "VG", name: "Virgin Islands (British)", dialCode: "+1 284", flag: "🇻🇬", currencyCode: "USD", currencySymbol: "$", timeZone: "America/Port_of_Arthur" },
  { code: "VI", name: "Virgin Islands (US)", dialCode: "+1 340", flag: "🇻🇮", currencyCode: "USD", currencySymbol: "$", timeZone: "America/Port_of_Arthur" },
  { code: "WF", name: "Wallis And Futuna", dialCode: "+681", flag: "🇼🇫", currencyCode: "XPF", currencySymbol: "CFP", timeZone: "America/Port_of_Arthur" },
  { code: "EH", name: "Western Sahara", dialCode: "+212", flag: "🇪🇭", currencyCode: "MAD", currencySymbol: "د.م.", timeZone: "America/Port_of_Arthur" },
  { code: "YE", name: "Yemen", dialCode: "+967", flag: "🇾🇪", currencyCode: "YER", currencySymbol: "﷼", timeZone: "America/Port_of_Arthur" },
  { code: "ZM", name: "Zambia", dialCode: "+260", flag: "🇿🇲", currencyCode: "ZMW", currencySymbol: "ZK", timeZone: "America/Port_of_Arthur" },
  { code: "ZW", name: "Zimbabwe", dialCode: "+263", flag: "🇿🇼", currencyCode: "USD", currencySymbol: "$", timeZone: "America/Port_of_Arthur" }
]

export default countryData;
