export type SignalDeskFirebaseMode = "shared" | "separate";
export type SignalDeskAdminCredentialPrefix = "FIREBASE" | "MENULIST_SIGNALDESK_FIREBASE";

export const SIGNALDESK_FIREBASE_APP_NAME = "menulist-signaldesk-admin";
export const SIGNALDESK_CLIENT_FIREBASE_APP_NAME = "menulist-signaldesk";
export const SIGNALDESK_DEFAULT_FIREBASE_APP_NAME = "[DEFAULT]";
export const SIGNALDESK_FIREBASE_CREDENTIAL_PREFIX = "MENULIST_SIGNALDESK_FIREBASE" as const;
export const SIGNALDESK_DEFAULT_FIREBASE_CREDENTIAL_PREFIX = "FIREBASE" as const;

export const SIGNALDESK_FIREBASE_ENV = {
    API_KEY: "NEXT_PUBLIC_MENULIST_SIGNALDESK_FIREBASE_API_KEY",
    APP_ID: "NEXT_PUBLIC_MENULIST_SIGNALDESK_FIREBASE_APP_ID",
    AUTH_DOMAIN: "NEXT_PUBLIC_MENULIST_SIGNALDESK_FIREBASE_AUTH_DOMAIN",
    CLIENT_EMAIL: "MENULIST_SIGNALDESK_FIREBASE_CLIENT_EMAIL",
    FIREBASE_MODE: "MENULIST_SIGNALDESK_FIREBASE_MODE",
    FIRESTORE_DATABASE_ID: "MENULIST_SIGNALDESK_FIRESTORE_DATABASE_ID",
    GOOGLE_APPLICATION_CREDENTIALS: "MENULIST_SIGNALDESK_GOOGLE_APPLICATION_CREDENTIALS",
    MESSAGING_SENDER_ID: "NEXT_PUBLIC_MENULIST_SIGNALDESK_FIREBASE_MESSAGING_SENDER_ID",
    PRIVATE_KEY: "MENULIST_SIGNALDESK_FIREBASE_PRIVATE_KEY",
    PROJECT_ID: "MENULIST_SIGNALDESK_FIREBASE_PROJECT_ID",
    PUBLIC_FIREBASE_MODE: "NEXT_PUBLIC_MENULIST_SIGNALDESK_FIREBASE_MODE",
    PUBLIC_FIRESTORE_DATABASE_ID: "NEXT_PUBLIC_MENULIST_SIGNALDESK_FIRESTORE_DATABASE_ID",
    PUBLIC_PROJECT_ID: "NEXT_PUBLIC_MENULIST_SIGNALDESK_FIREBASE_PROJECT_ID",
    PUBLIC_STORAGE_BUCKET: "NEXT_PUBLIC_MENULIST_SIGNALDESK_FIREBASE_STORAGE_BUCKET",
    STORAGE_BUCKET: "MENULIST_SIGNALDESK_FIREBASE_STORAGE_BUCKET",
} as const;

export const SIGNALDESK_FIREBASE_PROJECT_ID_ENV_KEYS = [
    SIGNALDESK_FIREBASE_ENV.PUBLIC_PROJECT_ID,
    SIGNALDESK_FIREBASE_ENV.PROJECT_ID,
] as const;

export const SIGNALDESK_FIRESTORE_DATABASE_ID_ENV_KEYS = [
    SIGNALDESK_FIREBASE_ENV.PUBLIC_FIRESTORE_DATABASE_ID,
    SIGNALDESK_FIREBASE_ENV.FIRESTORE_DATABASE_ID,
] as const;

export const SIGNALDESK_FIREBASE_MODE_ENV_KEYS = [
    SIGNALDESK_FIREBASE_ENV.PUBLIC_FIREBASE_MODE,
    SIGNALDESK_FIREBASE_ENV.FIREBASE_MODE,
] as const;

export const SIGNALDESK_FIREBASE_MODE_ALIASES: Record<SignalDeskFirebaseMode, readonly string[]> = {
    shared: ["shared", "same", "default"],
    separate: ["separate", "isolated", "dedicated"],
};
