import { GEMINI_MODELS } from '@constant/AI/models';

export const SIGNALDESK_INTEGRATION_ENV = {
    GEMINI_AI_KEY: "MENULIST_SIGNALDESK_GEMINI_AI_KEY",
    GEMINI_AI_KEY_2: "MENULIST_SIGNALDESK_GEMINI_AI_KEY_2",
    GEMINI_AI_KEY_3: "MENULIST_SIGNALDESK_GEMINI_AI_KEY_3",
    GEMINI_AI_KEY_4: "MENULIST_SIGNALDESK_GEMINI_AI_KEY_4",
    AI_MODEL: "MENULIST_SIGNALDESK_AI_MODEL",
    APIFY_API_TOKEN: "MENULIST_SIGNALDESK_APIFY_API_TOKEN",
    APIFY_SOURCE_ACTOR_ID: "MENULIST_SIGNALDESK_APIFY_SOURCE_ACTOR_ID",
    APIFY_WEBHOOK_SECRET: "MENULIST_SIGNALDESK_APIFY_WEBHOOK_SECRET",
    EMAIL_FROM: "MENULIST_SIGNALDESK_EMAIL_FROM",
    EMAIL_REPLY_TO: "MENULIST_SIGNALDESK_EMAIL_REPLY_TO",
    EMAIL_WEBHOOK_SECRET: "MENULIST_SIGNALDESK_EMAIL_WEBHOOK_SECRET",
    GOOGLE_PLACES_API_KEY: "MENULIST_SIGNALDESK_GOOGLE_PLACES_API_KEY",
    META_ACCESS_TOKEN: "MENULIST_SIGNALDESK_META_ACCESS_TOKEN",
    META_APP_SECRET: "MENULIST_SIGNALDESK_META_APP_SECRET",
    META_VERIFY_TOKEN: "MENULIST_SIGNALDESK_META_VERIFY_TOKEN",
    OUTCOME_BRIDGE_SECRET: "MENULIST_SIGNALDESK_OUTCOME_BRIDGE_SECRET",
    MESSENGER_PAGE_ID: "MENULIST_SIGNALDESK_MESSENGER_PAGE_ID",
    PHYSICAL_ADDRESS: "MENULIST_SIGNALDESK_PHYSICAL_ADDRESS",
    SMTP_HOST: "MENULIST_SIGNALDESK_SMTP_HOST",
    SMTP_PASS: "MENULIST_SIGNALDESK_SMTP_PASS",
    SMTP_PORT: "MENULIST_SIGNALDESK_SMTP_PORT",
    SMTP_SECURE: "MENULIST_SIGNALDESK_SMTP_SECURE",
    SMTP_USER: "MENULIST_SIGNALDESK_SMTP_USER",
    UNSUBSCRIBE_URL: "MENULIST_SIGNALDESK_UNSUBSCRIBE_URL",
    WHATSAPP_PHONE_NUMBER_ID: "MENULIST_SIGNALDESK_WHATSAPP_PHONE_NUMBER_ID",
    INSTAGRAM_PAGE_ID: "MENULIST_SIGNALDESK_INSTAGRAM_PAGE_ID",
    SMARTLEAD_API_KEY: "MENULIST_SIGNALDESK_SMARTLEAD_API_KEY",
    SMARTLEAD_WEBHOOK_SECRET: "MENULIST_SIGNALDESK_SMARTLEAD_WEBHOOK_SECRET",
} as const;

export const SIGNALDESK_DEFAULT_AI_MODEL = GEMINI_MODELS.TEXT_GEN;
export const SIGNALDESK_FAST_AI_MODEL = GEMINI_MODELS.TEXT_FAST;
export const SIGNALDESK_APIFY_API_BASE = "https://api.apify.com";
export const SIGNALDESK_FHRS_API_BASE = "https://api.ratings.food.gov.uk";
export const SIGNALDESK_GOOGLE_PLACES_TEXT_SEARCH_ENDPOINT = "https://places.googleapis.com/v1/places:searchText";
export const SIGNALDESK_GOOGLE_PLACES_FIELD_MASK = [
    "places.id",
    "places.displayName",
    "places.formattedAddress",
    "places.primaryType",
    "places.businessStatus",
    "places.googleMapsUri",
].join(",");
export const SIGNALDESK_META_GRAPH_VERSION = "v21.0";
export const SIGNALDESK_OUTCOME_ROUTE_SCOPE = "menulist-activation-outcomes-v1";
