export {
    CONSTANTLAYER_LOCAL_DEV_PATH_PREFIX as CONSTANTLAYER_LOCAL_PATH_PREFIX,
    CONSTANTLAYER_PRODUCTION_DOMAINS,
    CONSTANTLAYER_STAGING_DOMAINS,
} from '@constant/constantlayer/domains';

export {
    CONSTANTLAYER_ANSWERLATTICE_URL,
    CONSTANTLAYER_CAMPAIGNCUE_URL,
    CONSTANTLAYER_CONTACT_EMAIL,
    CONSTANTLAYER_LEGAL_EMAIL,
    CONSTANTLAYER_MENULIST_URL,
    CONSTANTLAYER_PRIVACY_EMAIL,
    CONSTANTLAYER_PRODUCT_LINEUP,
    CONSTANTLAYER_PUBLIC_PAGES,
    CONSTANTLAYER_RELATIONSHIP_LINE,
    CONSTANTLAYER_SITE_DESCRIPTION,
    CONSTANTLAYER_SITE_TITLE,
    CONSTANTLAYER_SITE_URL,
    buildConstantLayerUrl,
} from '@constant/constantlayer/website';
