/**
 * Extracted Data Types
 *
 * Types for AI-extracted menu data (categories, items, languages).
 */

import { UserUploadedFileType } from "@type/common";
import { FileMessage } from "./fileMessages.types";

/**
 * Feature #3: Time-Based Categories
 *
 * Categories can be assigned to store-level time slot presets.
 * If timeSlots is undefined or empty = category always visible
 * If timeSlots has entries = category visible only during those preset windows
 */

/**
 * Category Time Slot - references a store-level preset
 * Note: Fields are optional to allow partial overrides from CategoryOverride
 */
export interface CategoryTimeSlot {
    presetId?: string; // Reference to store preset
    startTime?: string; // "HH:mm" format e.g., "07:00"
    endTime?: string; // "HH:mm" format e.g., "10:00"
    days?: number[]; // Days of week (0=Sunday, 6=Saturday)
}

export interface ExtractedDataCategory {
    id: string;
    active: boolean;
    name: { [key: string]: string }; // Language code keys
    extractionIdAliases?: string[]; // Keeps category identity stable across re-extraction
    icon?: string; // Optional category icon, e.g. "lu:LuPizza" or "emoji:🍕"
    images?: UserUploadedFileType[];
    timeSlots?: CategoryTimeSlot[]; // Time-based visibility with preset support
    orderIndex?: number; // Multi-store: Store can override category order
}

export interface ExtractedDataAttribute {
    name: { [key: string]: string };
    id: string;
    price: string;
    active: boolean; // Can be overridden by store (hide specific variant)
    orderIndex?: number; // Multi-store: Store can override attribute order
}

export type DecisionFactPrimitive = string | number | boolean;
export type DecisionFactValue =
    | DecisionFactPrimitive
    | DecisionFactPrimitive[]
    | {
        calories?: number;
        protein?: number;
        carbs?: number;
        fat?: number;
        servingSize?: string;
    };

export interface DecisionFactEntry {
    value?: DecisionFactValue;
    source?: 'owner' | 'ai' | 'import' | 'system';
    confirmed?: boolean;
    updatedAt?: string;
}

export type ItemDecisionFacts = Record<string, DecisionFactEntry>;

export interface ExtractedDataItem {
    id: string;
    extractionIdAliases?: string[]; // Keeps item identity stable across re-extraction and outlet overrides
    attributes?: ExtractedDataAttribute[];
    category: string;
    name: { [key: string]: string };
    description?: { [key: string]: string };
    descriptionSource?: 'ai' | 'manual'; // Tracks if description was AI-generated or manually written
    // 'ai' = Generated by MenuList AI (can be refreshed)
    // 'manual' = Written/edited by user (protected from refresh)
    // undefined = Legacy data, treated as 'ai' for refresh purposes
    price?: string; // Price might be optional if attributes exist
    images?: UserUploadedFileType[];
    tags?: string[];
    active: boolean;
    available?: boolean; // Availability toggle - false = "Sold out" on customer menu (default: true)
    isBestSeller?: boolean; // System-curated or owner-marked popular item for filter chips
    /**
     * Generic customer decision facts.
     *
     * New SMB-type-specific item facts should be added here instead of growing
     * the top-level item type. Existing top-level metadata fields below remain
     * as compatibility mirrors for legacy data and integrations.
     */
    decisionFacts?: ItemDecisionFacts;
    // Note: Dietary info (Veg/Non-Veg) is stored in `tags` field as strings
    // e.g., tags: ["Vegetarian"] or tags: ["Non-Vegetarian"]
    // Extracted from visual markers in menu images (see parallelProcessingPrompt.ts)

    // ── Structured Item Metadata (SMB-Compatible) ──
    // Fields are universal on the type but conditionally visible in editor UI
    // based on store's businessType via src/config/itemMetadataConfig.ts.
    //
    // Food & Beverage fields:
    allergens?: string[]; // e.g., ["dairy", "nuts", "gluten", "shellfish", "soy", "eggs"]
    dietaryTags?: string[]; // e.g., ["vegan", "vegetarian", "gluten-free", "halal", "kosher", "keto"]
    spiceLevel?: 'none' | 'mild' | 'medium' | 'hot' | 'very-hot'; // Standardized spice scale
    nutritionInfo?: {
        calories?: number; // kcal per serving
        protein?: number; // grams
        carbs?: number; // grams
        fat?: number; // grams
        servingSize?: string; // e.g., "1 plate", "250ml"
    };
    //
    // Service / Health / Creative fields:
    skillLevel?: 'beginner' | 'intermediate' | 'advanced' | 'all-levels'; // Gyms, yoga, classes
    targetAudience?: 'for-men' | 'for-women' | 'unisex' | 'kids' | 'adults' | 'seniors'; // Salons, spas, gyms
    //
    // Retail / Creative fields:
    materials?: string; // e.g., "100% cotton", "sterling silver", "oak wood"
    warranty?: string; // e.g., "1 year manufacturer warranty"

    // Decision Intelligence Fields (Feature: Decision Blocks)
    duration?: number; // Time in minutes (prep time for food, service duration for others)
    // AI-extracted or owner-set. Falls back to category defaults if not set.
    ownerBoost?: number; // Score modifier from -20 to +20 (0 = neutral, positive = boost, negative = suppress)
    // Used in recommendation scoring. Default: 0
    orderIndex?: number; // Multi-store: Store can override item order within category
    qualityReview?: {
        priceOutlierReviewedAt?: string;
        priceOutlierReviewedPrice?: string;
    };
}

export interface ExtractedDataLanguage {
    name: string;
    code: string;
    isPrimary: boolean; // True for detected/source language, false for translations
}

export interface BusinessAttributeSuggestion {
    key: string;
    value: true;
    confidence?: 'high' | 'medium' | 'low';
    evidence?: string;
    sourceFileIndex?: number;
}

export interface ExtractedData {
    message?: string; // Deprecated - use processingMessages instead
    processingMessages?: FileMessage[]; // Per-file warnings/errors (Section 8.14)
    data: {
        categories: ExtractedDataCategory[];
        items: ExtractedDataItem[];
        languages: ExtractedDataLanguage[];
        businessAttributeSuggestions?: BusinessAttributeSuggestion[];
    };
}
