import { ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG } from '../sharedData/answerlatticeEmbedding';
import { GEMINI_STABLE_MODELS } from '../sharedData/geminiRuntime';

export const ANSWERLATTICE_TEXT_MODEL = GEMINI_STABLE_MODELS.TEXT_HIGH_THROUGHPUT;

export const ANSWERLATTICE_EMBEDDING_MODEL = ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.model;
export const ANSWERLATTICE_EMBEDDING_OUTPUT_DIMENSIONALITY =
    ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.outputDimensionality;
export const ANSWERLATTICE_EMBEDDING_CACHE_VERSION = ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.cacheVersion;
export const ANSWERLATTICE_EMBEDDING_VECTOR_FIELD = ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.vectorField;
