import { ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG } from '../sharedData/answerlatticeEmbedding';

export const ANSWERLATTICE_TEXT_MODEL = 'gemini-2.5-flash';

export const ANSWERLATTICE_EMBEDDING_MODEL = ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.model;
export const ANSWERLATTICE_EMBEDDING_OUTPUT_DIMENSIONALITY =
    ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.outputDimensionality;
export const ANSWERLATTICE_EMBEDDING_CACHE_VERSION = ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.cacheVersion;
export const ANSWERLATTICE_EMBEDDING_VECTOR_FIELD = ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.vectorField;
