import { FEATURE_FLAGS } from '@config/features';
import { PERMISSIONS } from '@constant/permissions';
import { AI_ACTIONS_TYPES } from '@constant/common';
import type { OwnerBusinessActionDefinition } from '../types';

const ACTIONS: OwnerBusinessActionDefinition[] = [
  {
    actionType: 'navigate_business_health',
    ownerLabel: 'Open Business Health',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.VIEW_ANALYTICS],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_HEALTH_PAGE', 'ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_business_health_detail',
    ownerLabel: 'Open Business Health',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.VIEW_ANALYTICS],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_HEALTH_PAGE', 'ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'navigate_analytics',
    ownerLabel: 'Open analytics',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.VIEW_ANALYTICS],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['store', 'project'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_dashboard_analytics',
    ownerLabel: 'Open dashboard analytics',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.VIEW_ANALYTICS],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['store', 'project'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'navigate_menu',
    ownerLabel: 'Open menu',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_MENU],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['project', 'menu_item', 'category'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_menu_editor_target',
    ownerLabel: 'Open menu editor',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_MENU],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['project', 'menu_item', 'category'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_publish_screen',
    ownerLabel: 'Open publish screen',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.PUBLISH_MENU],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['project'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_feedback_reviews',
    ownerLabel: 'Open feedback',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_FEEDBACK],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['feedback', 'review', 'store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_business_settings',
    ownerLabel: 'Open business settings',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_STORE],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_hours_settings',
    ownerLabel: 'Open hours settings',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_STORE],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_public_info_settings',
    ownerLabel: 'Open public information',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_PUBLIC_PRESENCE],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_qr_share',
    ownerLabel: 'Open QR code',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_MENU_SHARING],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['qr', 'project'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_customer_app_settings',
    ownerLabel: 'Open Customer App settings',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_PUBLIC_PRESENCE],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['customer_app', 'store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_digital_screen_settings',
    ownerLabel: 'Open digital screen settings',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_DIGITAL_SCREENS],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['screen', 'store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_domain_settings',
    ownerLabel: 'Open domain settings',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_PUBLIC_PRESENCE],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['domain', 'store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_locations',
    ownerLabel: 'Open locations',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.SWITCH_STORES],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['outlet', 'store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_billing',
    ownerLabel: 'Open billing',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.ACCESS_BILLING],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['billing', 'store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_users_permissions',
    ownerLabel: 'Open users and permissions',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_USERS],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['team', 'store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_pos_sync_settings',
    ownerLabel: 'Open POS settings',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_INTEGRATIONS],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['pos', 'store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'open_compliance_pages',
    ownerLabel: 'Open compliance pages',
    riskLevel: 'navigate',
    requiredPermissions: [PERMISSIONS.MANAGE_PUBLIC_PRESENCE],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_NAVIGATION'],
    targetKinds: ['compliance', 'store'],
    resolver: 'screen_route',
    executor: 'navigate',
    cacheImpact: 'none',
  },
  {
    actionType: 'prepare_description_rewrite',
    ownerLabel: 'Prepare description rewrite',
    riskLevel: 'draft',
    requiredPermissions: [PERMISSIONS.GENERATE_DESCRIPTIONS, PERMISSIONS.MANAGE_MENU],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_DRAFTS', 'ENABLE_OWNER_BUSINESS_ACTION_PROVIDER_TEXT'],
    targetKinds: ['menu_item'],
    resolver: 'project_doc',
    draftSchema: 'menu_item_description',
    executor: 'prepare_draft',
    cacheImpact: 'project_public',
    aiCostAction: AI_ACTIONS_TYPES.OWNER_BUSINESS_ASSISTANT_ACTION_TEXT,
  },
  {
    actionType: 'menu_item_description_prepare',
    ownerLabel: 'Prepare description rewrite',
    riskLevel: 'draft',
    requiredPermissions: [PERMISSIONS.GENERATE_DESCRIPTIONS, PERMISSIONS.MANAGE_MENU],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_DRAFTS', 'ENABLE_OWNER_BUSINESS_ACTION_PROVIDER_TEXT'],
    targetKinds: ['menu_item'],
    resolver: 'project_doc',
    draftSchema: 'menu_item_description',
    executor: 'prepare_draft',
    cacheImpact: 'project_public',
    aiCostAction: AI_ACTIONS_TYPES.OWNER_BUSINESS_ASSISTANT_ACTION_TEXT,
  },
  {
    actionType: 'prepare_review_reply',
    ownerLabel: 'Prepare review reply',
    riskLevel: 'draft',
    requiredPermissions: [PERMISSIONS.MANAGE_FEEDBACK],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_DRAFTS', 'ENABLE_OWNER_BUSINESS_ACTION_PROVIDER_TEXT'],
    targetKinds: ['review', 'feedback'],
    resolver: 'existing_api',
    draftSchema: 'review_reply',
    executor: 'prepare_draft',
    cacheImpact: 'none',
    aiCostAction: AI_ACTIONS_TYPES.OWNER_BUSINESS_ASSISTANT_ACTION_TEXT,
  },
  {
    actionType: 'review_reply_prepare',
    ownerLabel: 'Prepare review reply',
    riskLevel: 'draft',
    requiredPermissions: [PERMISSIONS.MANAGE_FEEDBACK],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_DRAFTS', 'ENABLE_OWNER_BUSINESS_ACTION_PROVIDER_TEXT'],
    targetKinds: ['review', 'feedback'],
    resolver: 'existing_api',
    draftSchema: 'review_reply',
    executor: 'prepare_draft',
    cacheImpact: 'none',
    aiCostAction: AI_ACTIONS_TYPES.OWNER_BUSINESS_ASSISTANT_ACTION_TEXT,
  },
  {
    actionType: 'store_temp_status_set',
    ownerLabel: 'Prepare temporary status',
    riskLevel: 'draft',
    requiredPermissions: [PERMISSIONS.MANAGE_STORE],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_DRAFTS'],
    targetKinds: ['store'],
    resolver: 'existing_api',
    draftSchema: 'store_temp_status',
    executor: 'prepare_draft',
    cacheImpact: 'store_public',
  },
  {
    actionType: 'store_temp_status_clear',
    ownerLabel: 'Prepare temporary status removal',
    riskLevel: 'draft',
    requiredPermissions: [PERMISSIONS.MANAGE_STORE],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_DRAFTS'],
    targetKinds: ['store'],
    resolver: 'existing_api',
    draftSchema: 'store_temp_status_clear',
    executor: 'prepare_draft',
    cacheImpact: 'store_public',
  },
  {
    actionType: 'mark_health_check_reviewed',
    ownerLabel: 'Mark as reviewed',
    riskLevel: 'confirmed_write',
    requiredPermissions: [PERMISSIONS.VIEW_ANALYTICS],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_CHECK_WORKFLOW'],
    targetKinds: ['store', 'project'],
    resolver: 'summary',
    executor: 'mark_reviewed',
    cacheImpact: 'none',
  },
  {
    actionType: 'dismiss_health_check',
    ownerLabel: 'Dismiss check',
    riskLevel: 'confirmed_write',
    requiredPermissions: [PERMISSIONS.VIEW_ANALYTICS],
    requiredFlags: ['ENABLE_OWNER_BUSINESS_ACTION_CHECK_WORKFLOW'],
    targetKinds: ['store', 'project'],
    resolver: 'summary',
    executor: 'dismiss_check',
    cacheImpact: 'none',
  },
];

const isFlagEnabled = (flag: string) => {
  const flags = FEATURE_FLAGS as Record<string, unknown>;
  return flags[flag] === true;
};

export function getOwnerBusinessAssistantActionDefinition(actionType: string) {
  return ACTIONS.find((action) => action.actionType === actionType) || null;
}

export function getOwnerBusinessAssistantAllowedActions() {
  if (!FEATURE_FLAGS.ENABLE_OWNER_BUSINESS_ACTION_SUPPORT) return [];

  return ACTIONS.filter((action) => action.requiredFlags.every(isFlagEnabled));
}

export function isOwnerBusinessAssistantActionEnabled(action: OwnerBusinessActionDefinition) {
  return FEATURE_FLAGS.ENABLE_OWNER_BUSINESS_ACTION_SUPPORT && action.requiredFlags.every(isFlagEnabled);
}

export function getOwnerBusinessAssistantActionRegistry() {
  return ACTIONS;
}
