import type { CreativeEditorAiToolAction } from "@/modules/creative-editor/types";

export const CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS = {
    ADD_MISSING_DETAILS: "campaigncue.add_missing_details",
    AD_HANDOFF_COPY: "campaigncue.ad_handoff_copy",
    BRAND_CHECK: "campaigncue.brand_check",
    CAPTION_VARIANTS: "campaigncue.caption_variants",
    EXPORT_CHECKLIST: "campaigncue.export_checklist",
    GOOGLE_POST: "campaigncue.google_post",
    IMPROVE_DESIGN: "campaigncue.improve_design",
    LAYER_SELECTED_IMAGE: "campaigncue.layer_selected_image",
    LOCALIZE_SELECTED_TEXT: "campaigncue.localize_selected_text",
    READY_TO_SHARE_CHECK: "campaigncue.ready_to_share_check",
    REMOVE_BACKGROUND_GUIDE: "campaigncue.remove_background_guide",
    REWRITE_SELECTED_TEXT: "campaigncue.rewrite_selected_text",
    SHORTEN_SELECTED_TEXT: "campaigncue.shorten_selected_text",
    SOURCE_FACT_CHECK: "campaigncue.source_fact_check",
    WHATSAPP_PACK: "campaigncue.whatsapp_pack",
} as const;

export type CampaignCueCreativeEditorAiActionId = (
    typeof CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS
)[keyof typeof CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS];

export const CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTIONS: CreativeEditorAiToolAction[] = [
    {
        category: "recommended",
        costLabel: "No provider call",
        description: "Check business facts, visible brand details, and manual export readiness before the owner shares the design.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.READY_TO_SHARE_CHECK,
        label: "Check if ready to share",
        ownerHint: "No posting from CampaignCue.",
    },
    {
        category: "recommended",
        costLabel: "No provider call",
        description: "Show which business details are missing from the current design and suggest safe editable lines.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.ADD_MISSING_DETAILS,
        label: "Add missing business details",
        ownerHint: "Uses saved facts only.",
    },
    {
        category: "recommended",
        costLabel: "No provider call",
        description: "Create a stronger headline, support line, and call to action from the current CampaignCue context.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.IMPROVE_DESIGN,
        label: "Improve this design",
        ownerHint: "Adds editable text only.",
    },
    {
        category: "copy",
        costLabel: "No provider call",
        description: "Prepare caption options the owner can paste manually after export.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.CAPTION_VARIANTS,
        label: "Caption options",
        ownerHint: "Manual use only.",
    },
    {
        category: "copy",
        costLabel: "No provider call",
        description: "Create a WhatsApp-ready message and short reply prompt for this asset.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.WHATSAPP_PACK,
        label: "WhatsApp text pack",
        ownerHint: "No sending from CampaignCue.",
    },
    {
        category: "copy",
        costLabel: "No provider call",
        description: "Draft a Google Business Profile update the owner can copy after export.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.GOOGLE_POST,
        label: "Google post text",
        ownerHint: "No Google account action.",
    },
    {
        category: "copy",
        costLabel: "No provider call",
        description: "Prepare headline, primary text, and description for a manual ad handoff.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.AD_HANDOFF_COPY,
        label: "Ad handoff copy",
        ownerHint: "No ad spend mutation.",
    },
    {
        category: "copy",
        costLabel: "No provider call",
        description: "Rewrite the selected text layer while keeping it editable.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.REWRITE_SELECTED_TEXT,
        label: "Rewrite selected text",
        requiresSelection: true,
    },
    {
        category: "copy",
        costLabel: "No provider call",
        description: "Make the selected text shorter for small designs.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.SHORTEN_SELECTED_TEXT,
        label: "Shorten selected text",
        requiresSelection: true,
    },
    {
        category: "copy",
        costLabel: "No provider call",
        description: "Add the local business/location context to the selected text.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.LOCALIZE_SELECTED_TEXT,
        label: "Make selected text local",
        requiresSelection: true,
    },
    {
        category: "check",
        costLabel: "No provider call",
        description: "Check visible text against known business facts and source-confidence warnings.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.SOURCE_FACT_CHECK,
        label: "Check business facts",
    },
    {
        category: "check",
        costLabel: "No provider call",
        description: "Check whether the design uses available brand name, color, logo, and export-safe copy.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.BRAND_CHECK,
        label: "Check brand fit",
    },
    {
        category: "image",
        costLabel: "No provider call",
        description: "Use the CueLayers upload path when an old poster, screenshot, or flat image should become reusable.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.LAYER_SELECTED_IMAGE,
        label: "Reuse old image",
        ownerHint: "Original stays preserved.",
        requiresImageSelection: true,
    },
    {
        category: "image",
        costLabel: "Provider gated",
        description: "Background removal needs the governed provider pipeline and is not active in the editor yet.",
        disabled: true,
        disabledReason: "Use image crop, opacity, outline, or CueLayers fallback for now.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.REMOVE_BACKGROUND_GUIDE,
        label: "Remove background",
    },
    {
        category: "export",
        costLabel: "No provider call",
        description: "Show the manual checks before downloading and using the asset.",
        id: CAMPAIGNCUE_CREATIVE_EDITOR_AI_ACTION_IDS.EXPORT_CHECKLIST,
        label: "Export checklist",
        ownerHint: "Download/export only.",
    },
];
