export const CAMPAIGNCUE_ERROR_CODES = {
    DECISION_GATE: "CAMPAIGNCUE_DECISION_GATE",
    FIREBASE_UNAVAILABLE: "CAMPAIGNCUE_FIREBASE_UNAVAILABLE",
    IDEMPOTENCY_CONFLICT: "CAMPAIGNCUE_IDEMPOTENCY_CONFLICT",
    RUNTIME_ERROR: "CAMPAIGNCUE_RUNTIME_ERROR",
} as const;
