export type CampaignCueFirebaseMode = "shared" | "separate";
export type CampaignCueAdminCredentialPrefix = "FIREBASE" | "CAMPAIGNCUE_FIREBASE";

export const CAMPAIGNCUE_FIREBASE_APP_NAME = "campaigncue-admin";
export const CAMPAIGNCUE_DEFAULT_FIREBASE_APP_NAME = "[DEFAULT]";
export const CAMPAIGNCUE_FIREBASE_CREDENTIAL_PREFIX = "CAMPAIGNCUE_FIREBASE" as const;
export const CAMPAIGNCUE_DEFAULT_FIREBASE_CREDENTIAL_PREFIX = "FIREBASE" as const;

export const CAMPAIGNCUE_FIREBASE_ENV = {
    API_KEY: "NEXT_PUBLIC_CAMPAIGNCUE_FIREBASE_API_KEY",
    APP_ID: "NEXT_PUBLIC_CAMPAIGNCUE_FIREBASE_APP_ID",
    AUTH_DOMAIN: "NEXT_PUBLIC_CAMPAIGNCUE_FIREBASE_AUTH_DOMAIN",
    CLIENT_EMAIL: "CAMPAIGNCUE_FIREBASE_CLIENT_EMAIL",
    FIRESTORE_DATABASE_ID: "CAMPAIGNCUE_FIRESTORE_DATABASE_ID",
    FIREBASE_MODE: "CAMPAIGNCUE_FIREBASE_MODE",
    GOOGLE_APPLICATION_CREDENTIALS: "CAMPAIGNCUE_GOOGLE_APPLICATION_CREDENTIALS",
    MESSAGING_SENDER_ID: "NEXT_PUBLIC_CAMPAIGNCUE_FIREBASE_MESSAGING_SENDER_ID",
    PRIVATE_KEY: "CAMPAIGNCUE_FIREBASE_PRIVATE_KEY",
    PROJECT_ID: "CAMPAIGNCUE_FIREBASE_PROJECT_ID",
    PUBLIC_FIREBASE_MODE: "NEXT_PUBLIC_CAMPAIGNCUE_FIREBASE_MODE",
    PUBLIC_FIRESTORE_DATABASE_ID: "NEXT_PUBLIC_CAMPAIGNCUE_FIRESTORE_DATABASE_ID",
    PUBLIC_PROJECT_ID: "NEXT_PUBLIC_CAMPAIGNCUE_FIREBASE_PROJECT_ID",
    PUBLIC_STORAGE_BUCKET: "NEXT_PUBLIC_CAMPAIGNCUE_FIREBASE_STORAGE_BUCKET",
    STORAGE_BUCKET: "CAMPAIGNCUE_FIREBASE_STORAGE_BUCKET",
} as const;

export const CAMPAIGNCUE_FIREBASE_PROJECT_ID_ENV_KEYS = [
    CAMPAIGNCUE_FIREBASE_ENV.PUBLIC_PROJECT_ID,
    CAMPAIGNCUE_FIREBASE_ENV.PROJECT_ID,
] as const;

export const CAMPAIGNCUE_FIRESTORE_DATABASE_ID_ENV_KEYS = [
    CAMPAIGNCUE_FIREBASE_ENV.PUBLIC_FIRESTORE_DATABASE_ID,
    CAMPAIGNCUE_FIREBASE_ENV.FIRESTORE_DATABASE_ID,
] as const;

export const CAMPAIGNCUE_FIREBASE_MODE_ENV_KEYS = [
    CAMPAIGNCUE_FIREBASE_ENV.PUBLIC_FIREBASE_MODE,
    CAMPAIGNCUE_FIREBASE_ENV.FIREBASE_MODE,
] as const;

export const CAMPAIGNCUE_ADMIN_CREDENTIAL_ENV_KEYS = [
    CAMPAIGNCUE_FIREBASE_ENV.PUBLIC_PROJECT_ID,
    CAMPAIGNCUE_FIREBASE_ENV.CLIENT_EMAIL,
    CAMPAIGNCUE_FIREBASE_ENV.PRIVATE_KEY,
] as const;

export const CAMPAIGNCUE_FIREBASE_MODE_ALIASES: Record<CampaignCueFirebaseMode, readonly string[]> = {
    shared: ["shared", "same", "default"],
    separate: ["separate", "isolated", "dedicated"],
};
