import { PRODUCT_IDS } from "@constant/product";

export const CAMPAIGNCUE_PRODUCT_CODE = PRODUCT_IDS.CAMPAIGNCUE;
export const CAMPAIGNCUE_PRODUCT_SLUG = "campaigncue" as const;
export const CAMPAIGNCUE_PRODUCT_NAME = "CampaignCue" as const;
export const CAMPAIGNCUE_SIGNIN_PRODUCT_PARAM = CAMPAIGNCUE_PRODUCT_SLUG;
export const CAMPAIGNCUE_RATE_LIMIT_NAMESPACE = CAMPAIGNCUE_PRODUCT_SLUG;
