import type { WebsiteResourcesCopy } from './types';
import { WEBSITE_RESOURCE_SOURCE_VERSION } from './sourceVersion';

const publishedAt = '2026-06-01';
const updatedAt = '2026-06-02';

export const enUSWebsiteResources: WebsiteResourcesCopy = {
    locale: 'en-US',
    localeStatus: 'source',
    sourceVersion: WEBSITE_RESOURCE_SOURCE_VERSION,
    clusterLabels: {
        'source-audit': 'Source audit',
        'official-source': 'Official source',
        'qr-menu': 'QR menu',
        'google-menu': 'Google menu',
        'menu-seo': 'Menu SEO',
        'ai-discovery': 'AI discovery',
        'menu-engineering': 'Menu engineering',
        'checklists': 'Checklist',
        'multi-location': 'Multi-location',
    },
    labels: {
        allResources: 'All resources',
        backToHub: 'Back to resources',
        checklist: 'Checklist',
        comparison: 'Comparison',
        copiedChecklist: 'Checklist copied',
        copyChecklist: 'Copy checklist',
        faqTitle: 'Questions owners ask',
        onThisPage: 'On this page',
        primaryAction: 'Next step',
        quickAnswer: 'Quick answer',
        readingTime: 'Read time',
        readResource: 'Read resource',
        relatedResources: 'Related resources',
        resources: 'Resources',
        updated: 'Updated',
    },
    hub: {
        eyebrow: 'Menu and service-list resources',
        title: 'Learn how to keep one public list current.',
        titleHighlight: 'one public list current',
        subtitle: 'Plain guides, audits, worksheets, and checklists for owners who want customers to see the same current menu, service list, catalogue, or price list on QR, Google, WhatsApp, websites, screens, and printed material.',
        primaryCta: { label: 'Create customer link', href: '/create-menu' },
        secondaryCta: { label: 'Start with a source audit', href: '/resources/menu-source-audit' },
        proofItems: [
            'For menus and service lists',
            'Owner guides, not tech docs',
            'No ranking or citation promises',
        ],
        clusterTitle: 'Start from the problem customers see',
        clusterSubtitle: 'Each resource explains one practical surface where menus become stale, then routes the owner back to one approved source.',
        toolTitle: 'Tools and checklists',
        toolSubtitle: 'Use these pages as working checklists with staff, printers, consultants, or location managers.',
    },
    articles: [
        {
            slug: 'menu-source-audit',
            cluster: 'source-audit',
            title: 'Audit every place customers may still see an old menu',
            metaTitle: 'Menu Source Audit for Restaurants | MenuList',
            metaDescription: 'Check Google, QR codes, WhatsApp, Instagram, PDFs, staff files, websites, and branch copies for old menu versions.',
            description: 'A practical audit for finding old menu copies before they confuse customers or staff.',
            quickAnswer: 'A menu source audit checks every public and staff-shared place where a customer might still see old prices, old items, or an outdated menu file. The goal is one current approved menu URL behind QR, Google, WhatsApp, website, print, screen, and branch surfaces.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.82,
            primaryCta: { label: 'Upload your current menu', href: '/create-menu' },
            relatedSlugs: ['official-menu-source', 'google-business-profile-menu', 'official-menu-url-checklist'],
            distributionSnippets: [
                'Most menu problems are not inside the menu. They are in old copies still visible on Google, WhatsApp, QR cards, and staff files.',
                'Before printing a new QR code, check where the old menu is still being shared.',
            ],
            sections: [
                {
                    id: 'why-old-menus-remain',
                    title: 'Why old menus remain visible',
                    body: [
                        'Menu changes are simple inside the business, but the old version keeps travelling. A PDF stays in WhatsApp. A table QR opens an old file. A customer photo remains on Google. A staff member sends last month\'s screenshot.',
                        'The customer only sees the mismatch. They do not know which version is correct.',
                    ],
                },
                {
                    id: 'places-to-check',
                    title: 'Places to check first',
                    body: [
                        'Start with the surfaces customers use before they call, visit, order, or share the business.',
                    ],
                    checklist: [
                        'Google Business Profile menu link',
                        'Google menu photos uploaded by the owner or customers',
                        'QR codes on tables, counters, windows, packaging, and bill folders',
                        'WhatsApp catalog links, groups, and saved replies',
                        'Instagram bio link, story highlights, and old posts',
                        'Business website menu page or PDF',
                        'Printed PDFs, takeaway flyers, and table tents',
                        'Staff phones, staff shared folders, and front-desk files',
                        'Delivery or ordering links that show menu content',
                        'Branch-specific copies for each location',
                    ],
                },
                {
                    id: 'monthly-check',
                    title: 'Monthly check',
                    body: [
                        'The audit should be short enough to run after price changes, availability changes, and seasonal menu changes.',
                    ],
                    checklist: [
                        'Open the QR code with a customer phone.',
                        'Search the business on Google and open every menu surface shown.',
                        'Open the Instagram and WhatsApp links customers see.',
                        'Ask one staff member what menu file they send when a customer asks.',
                        'Confirm branch managers are not using copied menus from an older outlet.',
                    ],
                },
                {
                    id: 'how-menulist-fits',
                    title: 'How MenuList fits',
                    body: [
                        'MenuList gives the business an official menu source for the current approved menu. QR, website links, saved menu shortcuts, WhatsApp replies, print assets, screens, branch pages, and official pages can point back to that current source.',
                        'External platforms still decide what they crawl, show, cache, or refresh. The MenuList job is to make the official source clearer and easier to reuse.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'audit-frequency',
                    question: 'How often should a business run this audit?',
                    answer: 'Run it after every price change, seasonal menu change, branch change, or printed QR update. For stable menus, a monthly check is enough.',
                },
                {
                    id: 'google-photos-removal',
                    question: 'Does MenuList remove old Google photos?',
                    answer: 'No. Google controls Google Business Profile content. MenuList gives the owner a current official menu source to place in the right fields and public links.',
                },
                {
                    id: 'old-pdf-deletion',
                    question: 'Should every old PDF be deleted?',
                    answer: 'Old public PDFs should stop being the main customer source. A current PDF can still be useful for print or backup when it is generated from the approved menu.',
                },
            ],
        },
        {
            slug: 'menu-engineering',
            cluster: 'menu-engineering',
            title: 'Menu engineering starts with the menu customers actually see',
            metaTitle: 'Menu Engineering Starts With the Public Menu | MenuList',
            metaDescription: 'Use menu engineering basics only after the customer-facing menu is current, clear, and owner-approved.',
            description: 'A practical owner guide to menu engineering without pretending MenuList replaces food-cost or POS analysis.',
            quickAnswer: 'Menu engineering reviews items, pricing, placement, and customer clarity. It works better when the public menu is current first, because owners cannot improve a menu customers are not actually seeing.',
            readingTime: '7 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.78,
            primaryCta: { label: 'Upload your current menu', href: '/create-menu' },
            relatedSlugs: ['menu-engineering-worksheet', 'official-menu-source', 'restaurant-menu-seo'],
            distributionSnippets: [
                'Menu engineering does not start in a spreadsheet. It starts with the menu customers actually see.',
            ],
            sections: [
                {
                    id: 'meaning',
                    title: 'What menu engineering means',
                    body: [
                        'Menu engineering usually groups items by popularity and margin. Owners use that view to decide which items to feature, rewrite, reprice, move, or remove.',
                        'MenuList should not claim to calculate full profitability unless food-cost and sales data are connected. The safe first step is keeping the public menu current and easier to review.',
                    ],
                },
                {
                    id: 'customer-facing-first',
                    title: 'The customer-facing menu comes first',
                    body: [
                        'If customers see old prices or old items, better item labels and better placement will not fix the main problem. The owner needs one current menu before judging what to improve.',
                    ],
                    bullets: [
                        'Item names should match what staff and customers use.',
                        'Prices should match the current approved menu.',
                        'Descriptions should make choice easier, not longer.',
                        'Photos should match the item being sold.',
                        'Sections should follow how customers decide.',
                    ],
                },
                {
                    id: 'matrix',
                    title: 'The basic menu engineering matrix',
                    comparisonRows: [
                        { label: 'Stars', left: 'High popularity', right: 'High margin' },
                        { label: 'Puzzles', left: 'Low popularity', right: 'High margin' },
                        { label: 'Plowhorses', left: 'High popularity', right: 'Low margin' },
                        { label: 'Dogs', left: 'Low popularity', right: 'Low margin' },
                    ],
                },
                {
                    id: 'actions',
                    title: 'Useful actions',
                    checklist: [
                        'Keep stars visible and easy to order.',
                        'Rewrite or reposition puzzles before removing them.',
                        'Review plowhorse pricing, portion, and placement.',
                        'Remove or hide dogs only after checking operational need.',
                        'Keep public prices aligned before printing new material.',
                    ],
                },
                {
                    id: 'how-menulist-fits',
                    title: 'How MenuList fits',
                    body: [
                        'MenuList keeps the public menu source structured, current, and owner-approved. That gives the owner a cleaner starting point for menu review, QR placement, public search copy, and print material.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'profitability-calculation',
                    question: 'Does MenuList calculate item profitability?',
                    answer: 'No. MenuList can keep the public menu source current and structured. Full profitability engineering needs food-cost and sales data.',
                },
                {
                    id: 'engineering-without-pos',
                    question: 'Can menu engineering be done without POS data?',
                    answer: 'A basic review can use owner knowledge, staff input, and customer clarity. POS data makes it stronger, but the public menu still needs to be current first.',
                },
            ],
        },
        {
            slug: 'qr-menu-for-restaurants',
            cluster: 'qr-menu',
            title: 'QR menus need one current approved destination',
            metaTitle: 'QR Menu Setup for Restaurants | MenuList',
            metaDescription: 'Plan restaurant QR menus around one stable official menu URL, table placement, scan testing, and current customer-facing content.',
            description: 'A QR menu guide focused on the official source behind the code.',
            quickAnswer: 'A restaurant QR code should open one stable, current, mobile-friendly menu URL. The QR itself is only a doorway. The official menu source behind it decides whether customers trust what they see.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.78,
            primaryCta: { label: 'Create one official QR menu', href: '/create-menu' },
            relatedSlugs: ['restaurant-qr-menu-mistakes', 'qr-code-placement-checklist', 'official-menu-source'],
            sections: [
                {
                    id: 'what-qr-opens',
                    title: 'What the QR should open',
                    body: [
                        'The QR should open the official menu source: a current public menu page that works on a phone, shows business identity, and stays readable without downloading a heavy file.',
                    ],
                    bullets: [
                        'Current item names and prices',
                        'Clear sections',
                        'Open status and business details when available',
                        'Call, WhatsApp, directions, or ordering handoffs when the business has them',
                        'A stable URL that can stay the same after menu changes',
                    ],
                },
                {
                    id: 'why-qr-fails',
                    title: 'Why QR menus fail',
                    checklist: [
                        'The QR opens an old PDF.',
                        'The page is hard to read on a phone.',
                        'The link changes after every menu update.',
                        'Staff print new QR cards without checking the old ones.',
                        'The QR points to a shared branch menu when this location has different prices or availability.',
                        'Customers scan in poor lighting or from too far away.',
                    ],
                },
                {
                    id: 'placement',
                    title: 'Where to place QR codes',
                    body: [
                        'QR placement should match where customers decide. A table QR is useful for browsing. A counter QR works for takeaway. A packaging QR works for repeat customers after they leave.',
                    ],
                    checklist: [
                        'Tables and counters',
                        'Entrance or waiting area',
                        'Bill folders and receipts',
                        'Takeaway packaging',
                        'Delivery bag stickers',
                        'Window posters',
                    ],
                },
                {
                    id: 'testing',
                    title: 'Scan testing before printing',
                    checklist: [
                        'Test with iPhone and Android.',
                        'Test in the same lighting customers will use.',
                        'Open the link on mobile data, not only Wi-Fi.',
                        'Confirm the page opens the current menu.',
                        'Keep the readable short URL printed under the QR.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'qr-opens-pdf',
                    question: 'Should a QR code open a PDF?',
                    answer: 'A PDF can work as a backup, but it should not be the main customer source when the menu changes often.',
                },
                {
                    id: 'same-qr-after-changes',
                    question: 'Can the same QR work after menu changes?',
                    answer: 'Yes, when the QR points to a stable MenuList link and the menu behind that link is updated.',
                },
            ],
        },
        {
            slug: 'digital-menu-vs-pdf-menu',
            cluster: 'official-source',
            title: 'A PDF can be useful, but it should not be your main public menu source',
            metaTitle: 'Digital Menu vs PDF Menu | MenuList',
            metaDescription: 'Compare mobile digital menus, PDFs, and print files for QR codes, WhatsApp, Google links, updates, and customer trust.',
            description: 'A comparison page for owners still using menu PDFs and print files everywhere.',
            quickAnswer: 'A PDF or print file is useful for print, controlled sharing, and backup, but a mobile digital menu is usually better as the main public source because it can stay current, searchable, and easier to read on phones.',
            readingTime: '5 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.76,
            primaryCta: { label: 'Replace your old PDF menu', href: '/create-menu' },
            relatedSlugs: ['qr-menu-for-restaurants', 'official-menu-source', 'menu-update-checklist'],
            sections: [
                {
                    id: 'pdf-useful',
                    title: 'Where PDFs are useful',
                    bullets: [
                        'Printer handoff packet',
                        'A backup file for staff',
                        'A static takeaway menu when prices rarely change',
                        'A downloadable version generated from the current approved menu',
                    ],
                },
                {
                    id: 'pdf-problems',
                    title: 'Where PDFs create problems',
                    body: [
                        'PDFs keep circulating after the menu changes. A customer may open a saved file from last month and treat it as current.',
                    ],
                    checklist: [
                        'Old prices remain in WhatsApp.',
                        'Large files load slowly on mobile data.',
                        'Text may be hard to zoom and scan.',
                        'Multiple PDF versions create source confusion.',
                    ],
                },
                {
                    id: 'comparison',
                    title: 'Digital menu vs PDF menu',
                    comparisonRows: [
                        { label: 'Mobile reading', left: 'Built for phone browsing', right: 'Often requires zooming' },
                        { label: 'Updates', left: 'Same link can show the latest menu', right: 'New file must replace old copies' },
                        { label: 'Search', left: 'Customers can search and jump sections', right: 'Depends on PDF quality' },
                        { label: 'Print', left: 'Can generate current PDF and printer handoff files', right: 'Good for direct printing' },
                    ],
                },
                {
                    id: 'safe-setup',
                    title: 'The safer setup',
                    body: [
                        'Use a current digital menu page as the main customer source. When you need paper, WhatsApp, or a printer handoff, generate the PDF or packet from that approved menu instead of maintaining a separate file.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'stop-using-pdfs',
                    question: 'Should a business stop using PDFs completely?',
                    answer: 'No. PDFs and print packets still work for print and controlled sharing. They should be generated from the current approved menu, not maintained as the main public source.',
                },
            ],
        },
        {
            slug: 'google-business-profile-menu',
            cluster: 'google-menu',
            title: 'Use one clear menu URL in Google Business Profile',
            metaTitle: 'Google Business Profile Menu URL | MenuList',
            metaDescription: 'Use one current official menu URL for Google Business Profile while avoiding claims about ranking, refresh timing, or automatic Google updates.',
            description: 'A careful owner guide for Google menu links, photos, and old menu cleanup.',
            quickAnswer: 'Google Business Profile can show menu links, menu photos, and customer-uploaded images. A current official menu URL reduces confusion, but Google decides what it crawls, shows, and refreshes.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.8,
            primaryCta: { label: 'Use one official menu link', href: '/create-menu' },
            relatedSlugs: ['menu-source-audit', 'restaurant-menu-seo', 'ai-search-menu-discovery'],
            distributionSnippets: [
                'Google cannot fix a scattered menu system by itself. Give it one clearer current source to read.',
            ],
            sections: [
                {
                    id: 'why-outdated',
                    title: 'Why Google menu information becomes outdated',
                    body: [
                        'Google may show business links, menu links, photos, customer-uploaded images, and other discovered content. If old files remain public, customers can still find them even after the restaurant has changed prices or items.',
                        'The owner-controlled job is to make the current approved menu easy to identify and reuse as the official source.',
                    ],
                },
                {
                    id: 'what-to-check',
                    title: 'What to check in Google Business Profile',
                    checklist: [
                        'Menu URL or website field',
                        'Owner-uploaded menu photos',
                        'Customer-uploaded menu photos',
                        'Old PDF links on the business website',
                        'Preferred menu source settings where available',
                        'Business hours, phone, and address consistency',
                    ],
                },
                {
                    id: 'old-menu-cleanup',
                    title: 'Old menu cleanup',
                    body: [
                        'The owner should remove or replace menu photos and links they control. Customer-uploaded photos may need reporting or owner-side management through Google tools.',
                    ],
                    checklist: [
                        'Replace the menu link with the current official menu URL.',
                        'Remove owner-uploaded outdated menu photos.',
                        'Report customer-uploaded old menu photos when appropriate.',
                        'Check the visible customer view after changes.',
                        'Keep the same current menu URL on QR, Instagram, WhatsApp, and the business website.',
                    ],
                },
                {
                    id: 'claim-limit',
                    title: 'What MenuList does not control',
                    body: [
                        'MenuList does not control Google ranking, Google Maps placement, photo removal decisions, crawl timing, or AI summaries. MenuList prepares a clearer official menu source and stable URL that owners can place where Google and customers look.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'automatic-google-update',
                    question: 'Will a MenuList link update Google automatically?',
                    answer: 'No. Owners still manage Google Business Profile. MenuList gives them a current official menu link to use.',
                },
                {
                    id: 'old-customer-photos',
                    question: 'Can old customer menu photos remain visible?',
                    answer: 'Yes. Google controls customer-uploaded photos. Owners can manage or report them through Google Business Profile tools.',
                },
            ],
        },
        {
            slug: 'official-menu-source',
            cluster: 'official-source',
            title: 'Official menu source: one current approved menu for every public surface',
            metaTitle: 'Official Menu Source for Restaurants | MenuList',
            metaDescription: 'Define one approved public menu source for QR codes, Google, WhatsApp, Instagram, websites, print, and multi-location teams.',
            description: 'The core MenuList concept explained in owner language: one official source for the current approved menu.',
            quickAnswer: 'An official menu source is the owner-approved menu version that every public link and material should point to. It gives QR codes, Google links, WhatsApp replies, websites, print assets, screens, branch pages, search engines, and AI systems one clearer current menu URL to work from.',
            readingTime: '5 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.8,
            primaryCta: { label: 'Create one official menu source', href: '/create-menu' },
            relatedSlugs: ['menu-source-audit', 'digital-menu-vs-pdf-menu', 'multi-location-menu-management'],
            sections: [
                {
                    id: 'problem',
                    title: 'The problem with menu copies everywhere',
                    body: [
                        'A business can have one current menu internally and many outdated copies publicly. Customers see screenshots, saved PDFs, old QR links, Google photos, Instagram posts, and staff-shared files.',
                        'MenuList gives every public surface one current approved menu source, so customers, staff, QR codes, Google links, WhatsApp links, branch pages, websites, print assets, screens, search engines, and AI/search systems are less likely to work from stale menu information.',
                    ],
                },
                {
                    id: 'what-source-includes',
                    title: 'What an official menu source should include',
                    checklist: [
                        'Business name and identity',
                        'Current sections, items, prices, and availability',
                        'Menu update or freshness signals',
                        'Phone-friendly layout',
                        'Call, WhatsApp, directions, order, or reservation handoffs when used',
                        'Stable URL for QR, Google, Instagram, WhatsApp, print, and website links',
                    ],
                },
                {
                    id: 'when-prices-change',
                    title: 'When prices or items change',
                    body: [
                        'The owner updates the current approved menu source. The QR and customer links should keep opening the current version instead of forcing the owner to chase every old file.',
                    ],
                },
                {
                    id: 'how-menulist-fits',
                    title: 'How MenuList fits',
                    body: [
                        'MenuList turns the current approved menu into a structured public source. The same source can support QR menus, official pages, sharing links, print/PDF assets, screens, and multi-location control.',
                        'MenuList does not guarantee that outside platforms will crawl, rank, cite, refresh, or summarize the page. Its job is to keep the public customer-facing version clearer and easier to reuse.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'official-source-vs-website',
                    question: 'Is an official menu source the same as a website?',
                    answer: 'Not exactly. A website can include many pages. The official menu source is the current menu truth customers should reach from every public surface.',
                },
            ],
        },
        {
            slug: 'restaurant-menu-seo',
            cluster: 'menu-seo',
            title: 'Make your menu easier for customers and search systems to understand',
            metaTitle: 'Restaurant Menu SEO Guide | MenuList',
            metaDescription: 'Learn how visible menu text, stable URLs, headings, metadata, internal links, and structured data support menu discovery without ranking promises.',
            description: 'A practical SEO guide for restaurant menu pages.',
            quickAnswer: 'Restaurant menu SEO starts with visible text, a stable menu URL, clear headings, useful metadata, internal links, and structured data that matches the page. No system can guarantee rankings.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.78,
            primaryCta: { label: 'Publish an official menu page', href: '/create-menu' },
            relatedSlugs: ['google-business-profile-menu', 'ai-search-menu-discovery', 'official-menu-source'],
            sections: [
                {
                    id: 'visible-text',
                    title: 'Visible text matters',
                    body: [
                        'Search systems and answer engines need readable page content. A menu trapped inside an image or old PDF is harder to understand than a structured page with visible item names, sections, prices, and business context.',
                    ],
                },
                {
                    id: 'stable-url',
                    title: 'A stable menu URL matters',
                    body: [
                        'A stable URL lets QR codes, Google fields, social profiles, and customers point to the same place. The content can update behind the link while the link remains familiar.',
                    ],
                },
                {
                    id: 'seo-basics',
                    title: 'Useful menu SEO basics',
                    checklist: [
                        'One H1 for the page.',
                        'Clear section headings.',
                        'Readable item names and descriptions.',
                        'Metadata that matches visible page content.',
                        'Internal links from the homepage or business page to the menu.',
                        'Schema that describes only what the page visibly shows.',
                    ],
                },
                {
                    id: 'claim-limit',
                    title: 'What SEO cannot promise',
                    body: [
                        'Search engines decide crawling, ranking, rich results, and snippets. A better menu page gives them a clearer source, but it does not force placement.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'structured-data-guarantee',
                    question: 'Does structured data guarantee rich results?',
                    answer: 'No. Structured data should match visible content. Search engines decide whether to use it.',
                },
            ],
        },
        {
            slug: 'ai-search-menu-discovery',
            cluster: 'ai-discovery',
            title: 'Make your current menu easier for search and AI systems to understand',
            metaTitle: 'AI Search Menu Discovery | MenuList',
            metaDescription: 'Prepare a clearer public menu source for search and AI systems with visible HTML, schema, sitemap, robots, and LLM context files.',
            description: 'A careful AEO guide without ranking or citation promises.',
            quickAnswer: 'AI search systems work better with clear public sources. A current menu page with visible text, schema, sitemap signals, robots policy, and LLM context is easier to read than scattered PDFs and old images.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.78,
            primaryCta: { label: 'Create one official menu source', href: '/create-menu' },
            relatedSlugs: ['restaurant-menu-seo', 'official-menu-source', 'google-business-profile-menu'],
            sections: [
                {
                    id: 'why-ai-needs-source',
                    title: 'Why AI systems need a clear source',
                    body: [
                        'AI assistants and answer systems may summarize public information from search results, crawled pages, user-triggered fetches, and structured data. When old menu copies remain online, summaries can become uncertain or stale.',
                    ],
                },
                {
                    id: 'what-readable-means',
                    title: 'What readable means',
                    checklist: [
                        'Important menu text is visible in HTML.',
                        'Schema matches visible page content.',
                        'Sitemap lists active public pages.',
                        'Robots policy is intentional.',
                        'LLM context files explain public facts and boundaries.',
                        'The page states what external systems decide for themselves.',
                    ],
                },
                {
                    id: 'scattered-sources',
                    title: 'Why scattered files confuse answers',
                    body: [
                        'A current menu page says one thing. An old PDF, an old Google photo, and an old WhatsApp image say something else. The clearer source should be the one the owner maintains.',
                    ],
                },
                {
                    id: 'claim-limit',
                    title: 'What MenuList does not guarantee',
                    body: [
                        'MenuList does not guarantee Google rankings, ChatGPT citations, AI answer placement, crawl timing, or external platform refreshes. MenuList prepares a clearer public source for those systems to read when they choose to.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'llms-required-google-ai',
                    question: 'Is llms.txt required for Google AI features?',
                    answer: 'No. Google says normal search fundamentals still matter. MenuList uses LLM context files as an additional public-agent contract, not as a Google requirement.',
                },
            ],
        },
        {
            slug: 'menu-update-checklist',
            cluster: 'checklists',
            title: 'Check the public menu before and after every update',
            metaTitle: 'Restaurant Menu Update Checklist | MenuList',
            metaDescription: 'Use this checklist before changing prices, availability, descriptions, QR links, Google menu links, PDFs, and staff-shared menu files.',
            description: 'A working checklist for safe menu changes.',
            quickAnswer: 'A menu update is not finished when the owner changes the internal menu. It is finished when customers can see the current approved version on the public surfaces they use.',
            readingTime: '5 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.76,
            primaryCta: { label: 'Review your menu source', href: '/create-menu' },
            relatedSlugs: ['menu-source-audit', 'official-menu-source', 'digital-menu-vs-pdf-menu'],
            sections: [
                {
                    id: 'before-update',
                    title: 'Before updating',
                    checklist: [
                        'Confirm item names and spelling.',
                        'Confirm current prices and currency.',
                        'Mark unavailable items clearly.',
                        'Check photos still match items.',
                        'Check descriptions are short and useful.',
                        'Confirm categories still make sense.',
                    ],
                },
                {
                    id: 'after-update',
                    title: 'After updating',
                    checklist: [
                        'Open the public menu on a phone.',
                        'Scan the main QR code.',
                        'Open the Google menu link if used.',
                        'Open the Instagram and WhatsApp links.',
                        'Replace old PDFs or print files if they changed.',
                        'Tell staff which link to send customers.',
                    ],
                },
                {
                    id: 'branch-updates',
                    title: 'Branch and outlet updates',
                    body: [
                        'For multi-location businesses, confirm whether the change applies to every outlet or only one location.',
                    ],
                    checklist: [
                        'Shared master menu updated.',
                        'Location-level price differences checked.',
                        'Local unavailable items checked.',
                        'Branch QR links tested.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'biggest-update-mistake',
                    question: 'What is the biggest update mistake?',
                    answer: 'Changing the menu in one place while customers still see old prices in another place.',
                },
            ],
        },
        {
            slug: 'qr-code-placement-checklist',
            cluster: 'checklists',
            title: 'Place QR codes where customers can scan them without asking staff',
            metaTitle: 'QR Code Placement Checklist for Restaurants | MenuList',
            metaDescription: 'Use this checklist for QR code size, table placement, counter placement, packaging, lighting, fallback URLs, and scan testing.',
            description: 'A practical QR placement checklist for owners, staff, and printers.',
            quickAnswer: 'A good QR setup uses the right size, clear placement, good lighting, a readable fallback URL, and scan testing on real customer phones before printing at scale.',
            readingTime: '5 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.76,
            primaryCta: { label: 'Create one QR menu source', href: '/create-menu' },
            relatedSlugs: ['qr-menu-for-restaurants', 'menu-source-audit', 'digital-menu-vs-pdf-menu'],
            sections: [
                {
                    id: 'placement',
                    title: 'Placement checklist',
                    checklist: [
                        'Table card visible from normal seated position.',
                        'Counter QR near ordering or payment point.',
                        'Window QR readable from outside if used.',
                        'Packaging QR placed on a flat visible area.',
                        'Bill-folder or receipt QR does not fold across the code.',
                        'Fallback short URL printed below the code.',
                    ],
                },
                {
                    id: 'size-lighting',
                    title: 'Size and lighting',
                    checklist: [
                        'Print test at the final size before bulk printing.',
                        'Avoid glossy glare where lighting is strong.',
                        'Keep quiet space around the QR.',
                        'Use strong contrast.',
                        'Do not place on curved or heavily textured surfaces.',
                    ],
                },
                {
                    id: 'scan-test',
                    title: 'Scan test',
                    checklist: [
                        'Test iPhone camera.',
                        'Test Android camera.',
                        'Test in-store Wi-Fi and mobile data.',
                        'Confirm the page opens the current menu.',
                        'Ask staff to test before placing cards on tables.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'table-specific-qr',
                    question: 'Should each table have a different QR?',
                    answer: 'Not for the menu source. A single official menu link is simpler. Table-specific codes only matter when a separate ordering system needs table identity.',
                },
            ],
        },
        {
            slug: 'menu-engineering-worksheet',
            cluster: 'menu-engineering',
            title: 'Review menu items with a simple worksheet',
            metaTitle: 'Menu Engineering Worksheet | MenuList',
            metaDescription: 'Use a simple item worksheet for section, price, cost estimate, popularity estimate, margin estimate, clarity, and next action.',
            description: 'An HTML-first worksheet for reviewing menu items before changing public menus.',
            quickAnswer: 'A useful menu worksheet gives each item a section, current price, rough cost, popularity estimate, margin estimate, customer clarity score, and next action.',
            readingTime: '5 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.74,
            primaryCta: { label: 'Start from your current menu', href: '/create-menu' },
            relatedSlugs: ['menu-engineering', 'menu-update-checklist', 'official-menu-source'],
            sections: [
                {
                    id: 'worksheet-fields',
                    title: 'Worksheet fields',
                    checklist: [
                        'Item name',
                        'Section',
                        'Current price',
                        'Cost estimate',
                        'Popularity estimate',
                        'Margin estimate',
                        'Customer clarity',
                        'Action: keep, rewrite, reprice, move, remove, or test',
                    ],
                },
                {
                    id: 'how-to-use',
                    title: 'How to use it',
                    body: [
                        'Use the worksheet after the current public menu is structured. Review one section at a time so the owner is not forced to redesign the full menu at once.',
                    ],
                    checklist: [
                        'Mark best-known items first.',
                        'Mark confusing item names.',
                        'Find items with unclear prices or weak descriptions.',
                        'Decide what should be more visible.',
                        'Update the public menu only after owner approval.',
                    ],
                },
                {
                    id: 'claim-limit',
                    title: 'What this worksheet is not',
                    body: [
                        'This is not a POS profitability report. It is a practical owner review tool. Use food-cost and sales systems for exact margin analysis.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'staff-worksheet',
                    question: 'Can staff fill this worksheet?',
                    answer: 'Staff can add notes, but owner approval should remain the final source before public changes go live.',
                },
            ],
        },
        {
            slug: 'restaurant-menu-schema',
            cluster: 'menu-seo',
            title: 'Use restaurant menu schema only for menu details customers can see',
            metaTitle: 'Restaurant Menu Schema Guide | MenuList',
            metaDescription: 'Learn how Restaurant, LocalBusiness, Menu, MenuSection, MenuItem, OpeningHoursSpecification, Article, FAQPage, and BreadcrumbList schema should be used.',
            description: 'A practical structured-data guide for public restaurant menu pages.',
            quickAnswer: 'Restaurant menu schema should describe the same public menu content customers can see on the page. Use Restaurant or LocalBusiness for the business, Menu, MenuSection, and MenuItem for visible menu content, and never mark up hidden prices, fake reviews, or unavailable details.',
            readingTime: '6 min',
            publishedAt: '2026-06-02',
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.74,
            primaryCta: { label: 'Publish a structured menu page', href: '/create-menu' },
            relatedSlugs: ['restaurant-menu-seo', 'ai-search-menu-discovery', 'official-menu-source'],
            distributionSnippets: [
                'Restaurant menu schema is useful only when it matches the menu customers can actually see.',
                'Structured data should describe current public menu content, not invent prices, reviews, or hidden items.',
            ],
            sections: [
                {
                    id: 'schema-types',
                    title: 'Schema types that fit restaurant menu pages',
                    body: [
                        'A restaurant public page can use business schema for identity and menu schema for the actual menu. The safest setup is simple: describe the business, the public menu URL, menu sections, and menu items that are visible on the page.',
                    ],
                    checklist: [
                        'Use Restaurant when the business is a restaurant.',
                        'Use LocalBusiness or a closer subtype when Restaurant does not fit.',
                        'Use Menu for the public menu object.',
                        'Use MenuSection for visible menu categories.',
                        'Use MenuItem for visible menu items.',
                        'Use OpeningHoursSpecification only for published business hours.',
                        'Use FAQPage only when the same questions and answers are visible on the page.',
                        'Use BreadcrumbList for page navigation context.',
                    ],
                },
                {
                    id: 'visible-content',
                    title: 'Structured data must match visible content',
                    body: [
                        'Schema is not a place to add information customers cannot see. If the price, item, hour, rating, review, image, dietary claim, or offer is not visible and current on the public page, it should not be marked up.',
                    ],
                    checklist: [
                        'Visible item name matches the MenuItem name.',
                        'Visible price matches the Offer price when price markup is used.',
                        'Visible hours match OpeningHoursSpecification.',
                        'Visible FAQ content matches FAQPage markup.',
                        'Canonical URL matches the public page URL.',
                        'Sitemap includes only public pages intended for discovery.',
                    ],
                },
                {
                    id: 'common-mistakes',
                    title: 'Common schema mistakes',
                    checklist: [
                        'Adding fake reviews or ratings.',
                        'Marking up hidden FAQ answers.',
                        'Keeping old prices in structured data after changing visible prices.',
                        'Using Restaurant schema for a non-restaurant business.',
                        'Adding unavailable menu items that customers cannot see.',
                        'Expecting schema to guarantee rankings, rich results, or AI citations.',
                    ],
                },
                {
                    id: 'how-menulist-fits',
                    title: 'How MenuList fits',
                    body: [
                        'MenuList keeps public menu pages structured around the owner-approved menu source. That makes it easier to keep visible content, metadata, sitemap entries, and JSON-LD aligned.',
                        'External search and AI systems still decide what they crawl, show, cite, summarize, or ignore.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'schema-guarantee',
                    question: 'Does restaurant menu schema guarantee rich results or rankings?',
                    answer: 'No. Schema can help systems understand a page, but search engines decide whether to crawl, index, rank, or show enhanced results.',
                },
                {
                    id: 'hidden-menu-items',
                    question: 'Can hidden menu items be added to schema?',
                    answer: 'No. Structured data should match the public page. Hidden items, old prices, and private notes should stay out of public schema.',
                },
            ],
        },
        {
            slug: 'official-menu-url-checklist',
            cluster: 'checklists',
            title: 'Use one stable menu URL everywhere customers look',
            metaTitle: 'Official Menu URL Checklist for Restaurants | MenuList',
            metaDescription: 'A checklist for using one stable menu URL across QR codes, Google Business Profile, WhatsApp, Instagram, websites, print assets, screens, and branches.',
            description: 'A surface-by-surface checklist for replacing scattered menu links with one approved source URL.',
            quickAnswer: 'An official menu URL is the stable public link customers should use for the current approved menu. Put the same URL behind QR codes, Google menu links, social profiles, website buttons, WhatsApp replies, print assets, screens, and branch pages where it fits.',
            readingTime: '5 min',
            publishedAt: '2026-06-02',
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.76,
            primaryCta: { label: 'Create a stable menu URL', href: '/create-menu' },
            relatedSlugs: ['official-menu-source', 'menu-source-audit', 'qr-menu-for-restaurants'],
            distributionSnippets: [
                'Do not create a new menu file for every update. Keep one stable menu URL and update the approved menu behind it.',
                'The best menu link is the one customers keep reaching, even after prices or availability change.',
            ],
            sections: [
                {
                    id: 'choose-source-url',
                    title: 'Choose the source URL',
                    body: [
                        'Start with the public menu page that the owner can keep current. This URL should stay stable even when prices, items, photos, or availability change.',
                    ],
                    checklist: [
                        'Use a short public URL when possible.',
                        'Confirm the page opens on mobile without login.',
                        'Confirm the menu shown is owner-approved.',
                        'Confirm the page can be updated without changing the URL.',
                        'Use branch-specific URLs when each location has different prices or availability.',
                    ],
                },
                {
                    id: 'update-surfaces',
                    title: 'Update every customer-facing surface',
                    checklist: [
                        'QR codes on tables, counters, packaging, windows, and bill folders.',
                        'Google Business Profile menu link where available.',
                        'Instagram bio, highlights, and link-in-bio tools.',
                        'WhatsApp saved replies, catalog notes, and group descriptions.',
                        'Website menu buttons and navigation links.',
                        'PDF or print files that include a menu URL.',
                        'Digital screens and counter displays.',
                        'Branch pages and branch-specific QR cards.',
                    ],
                },
                {
                    id: 'test-before-printing',
                    title: 'Test before printing or sharing',
                    checklist: [
                        'Open the URL on mobile data.',
                        'Scan the QR from final print size.',
                        'Check the menu title, prices, and current availability.',
                        'Ask staff to send the same URL when customers ask for the menu.',
                        'Keep old PDFs from being used as the main customer link.',
                    ],
                },
                {
                    id: 'limits',
                    title: 'What the URL cannot force',
                    body: [
                        'A clear official URL reduces confusion, but it does not force external sites to refresh instantly. Google, social platforms, customer-uploaded photos, and old shared files can still show cached or old information until they update or are replaced.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'new-qr-every-update',
                    question: 'Does every menu update need a new QR code?',
                    answer: 'No. If the QR points to a stable menu URL, the business can update the menu behind the URL and keep the same printed QR code.',
                },
                {
                    id: 'delete-old-pdfs',
                    question: 'Should old PDF links be removed?',
                    answer: 'Old public PDFs should stop being the main menu link. Keep only current print or backup files that match the approved menu.',
                },
            ],
        },
        {
            slug: 'restaurant-qr-menu-mistakes',
            cluster: 'qr-menu',
            title: 'Common QR menu mistakes restaurants should avoid',
            metaTitle: 'Common QR Menu Mistakes Restaurants Should Avoid | MenuList',
            metaDescription: 'Avoid stale PDF menus, tiny QR codes, missing fallback URLs, slow mobile pages, branch mismatches, and untested QR placements.',
            description: 'A practical mistake list for QR menus before owners print table cards or packaging.',
            quickAnswer: 'The biggest QR menu mistake is treating the QR code as the menu. The QR is only an access point. The important part is the stable current menu source behind it, plus readable placement, a fallback URL, and scan testing before customers use it.',
            readingTime: '5 min',
            publishedAt: '2026-06-02',
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.74,
            primaryCta: { label: 'Set up a stable QR menu', href: '/create-menu' },
            relatedSlugs: ['qr-menu-for-restaurants', 'qr-code-placement-checklist', 'digital-menu-vs-pdf-menu'],
            distributionSnippets: [
                'The QR code is not the menu. It is only the doorway to the menu source behind it.',
                'A QR menu fails when the link, placement, or branch version is wrong.',
            ],
            sections: [
                {
                    id: 'pdf-only',
                    title: 'Mistake 1: pointing QR codes to old PDFs',
                    body: [
                        'A PDF can be useful for print, but it often becomes stale when it is shared through WhatsApp, old website links, or old QR cards. A mobile menu page is easier to update behind the same link.',
                    ],
                    checklist: [
                        'Use a mobile-friendly menu page as the main QR destination.',
                        'Keep PDF files secondary for print or backup.',
                        'Replace old PDF links when prices or items change.',
                    ],
                },
                {
                    id: 'unstable-links',
                    title: 'Mistake 2: changing the link after every menu update',
                    body: [
                        'If each update creates a new URL, printed QR material becomes risky. The safer setup is a stable URL with menu content updated behind it.',
                    ],
                    checklist: [
                        'Use one stable public menu URL.',
                        'Update content behind the URL instead of replacing the URL.',
                        'Keep staff replies and social links pointed to the same source.',
                    ],
                },
                {
                    id: 'placement-testing',
                    title: 'Mistake 3: printing before real scan testing',
                    checklist: [
                        'Test the QR at final print size.',
                        'Test iPhone and Android cameras.',
                        'Test in the same lighting customers will use.',
                        'Print a readable fallback URL below the QR.',
                        'Open the page on mobile data, not only Wi-Fi.',
                    ],
                },
                {
                    id: 'branch-mismatch',
                    title: 'Mistake 4: using one branch menu for every location',
                    body: [
                        'A shared brand menu is useful, but branches may have different prices, availability, hours, or service modes. QR codes should send customers to the right branch version when those differences matter.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'biggest-qr-mistake',
                    question: 'What is the most common QR menu mistake?',
                    answer: 'Using a QR code that opens an old or hard-to-read menu file instead of a stable current menu page.',
                },
                {
                    id: 'branch-specific-qr',
                    question: 'Should each branch have its own QR menu?',
                    answer: 'Yes when prices, availability, hours, or service details differ by branch. A shared QR is fine only when the same menu is truly correct everywhere.',
                },
            ],
        },
        {
            slug: 'multi-location-menu-management',
            cluster: 'multi-location',
            title: 'Keep branch menus aligned without hiding local differences',
            metaTitle: 'Multi-location Menu Source Control | MenuList',
            metaDescription: 'Manage master menus, outlet differences, branch price drift, local availability, QR links, Google links, and public branch consistency from one approved source.',
            description: 'A guide for brands running more than one location.',
            quickAnswer: 'Multi-location menu management needs one current approved master source plus controlled outlet differences for price, availability, local items, hours, QR links, Google links, and branch-specific public details.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.76,
            primaryCta: { label: 'Set up your first location', href: '/create-menu' },
            relatedSlugs: ['official-menu-source', 'official-menu-url-checklist', 'menu-update-checklist'],
            sections: [
                {
                    id: 'why-branches-drift',
                    title: 'Why branch menus drift',
                    body: [
                        'One outlet changes a price. Another runs out of an item. A third prints old QR material. A fourth updates WhatsApp replies but not Google. Over time the brand has many menu versions and no simple way to know what customers see.',
                    ],
                },
                {
                    id: 'master-vs-outlet',
                    title: 'Master menu and outlet menu',
                    comparisonRows: [
                        { label: 'Master menu', left: 'Shared item structure, brand sections, common descriptions', right: 'Used as the approved source' },
                        { label: 'Outlet menu', left: 'Local price, availability, local item, branch details', right: 'Used for customer truth at that branch' },
                    ],
                },
                {
                    id: 'what-to-control',
                    title: 'What to control',
                    checklist: [
                        'Shared item names and sections',
                        'Outlet-level price differences',
                        'Local availability',
                        'Branch-specific service modes',
                        'QR links for each outlet',
                        'Google and social links per outlet',
                        'Public branch pages where customer truth differs',
                        'Printed materials per outlet',
                    ],
                },
                {
                    id: 'how-menulist-fits',
                    title: 'How MenuList fits',
                    body: [
                        'MenuList supports a master menu and outlet-aware control so businesses can keep the shared source stable while preserving local differences where needed. The goal is not to hide branch differences; it is to keep each public branch version approved and current.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'same-menu-every-outlet',
                    question: 'Should every outlet show exactly the same menu?',
                    answer: 'Only when the business actually operates that way. The safer setup is shared structure with controlled outlet differences.',
                },
            ],
        },
    ],
};
