import type { WebsiteResourcesCopy } from './types';
import { WEBSITE_RESOURCE_SOURCE_VERSION } from './sourceVersion';

const publishedAt = '2026-06-01';
const updatedAt = '2026-06-01';

export const enUSWebsiteResources: WebsiteResourcesCopy = {
    locale: 'en-US',
    localeStatus: 'source',
    sourceVersion: WEBSITE_RESOURCE_SOURCE_VERSION,
    clusterLabels: {
        'source-audit': 'Source audit',
        'official-source': 'Official source',
        'qr-menu': 'QR menu',
        'google-menu': 'Google menu',
        'menu-seo': 'Menu SEO',
        'ai-discovery': 'AI discovery',
        'menu-engineering': 'Menu engineering',
        'checklists': 'Checklist',
        'multi-location': 'Multi-location',
    },
    labels: {
        allResources: 'All resources',
        backToHub: 'Back to resources',
        checklist: 'Checklist',
        comparison: 'Comparison',
        faqTitle: 'Questions owners ask',
        onThisPage: 'On this page',
        primaryAction: 'Next step',
        quickAnswer: 'Quick answer',
        readingTime: 'Read time',
        readResource: 'Read resource',
        relatedResources: 'Related resources',
        resources: 'Resources',
        updated: 'Updated',
    },
    hub: {
        eyebrow: 'Menu correctness resources',
        title: 'Learn how to keep one public menu current.',
        titleHighlight: 'one public menu current',
        subtitle: 'Plain guides, audits, worksheets, and checklists for owners who want customers to see the same current menu on QR, Google, WhatsApp, websites, screens, and printed material.',
        primaryCta: { label: 'Upload your menu', href: '/create-menu' },
        secondaryCta: { label: 'Start with the audit', href: '/resources/menu-source-audit' },
        proofItems: [
            'Evergreen owner guides',
            'Visible HTML for search and answer systems',
            'No ranking or citation promises',
        ],
        clusterTitle: 'Start from the problem customers see',
        clusterSubtitle: 'Each resource explains one practical surface where menus become stale, then routes the owner back to one approved source.',
        toolTitle: 'Tools and checklists',
        toolSubtitle: 'Use these pages as working checklists with staff, printers, consultants, or location managers.',
    },
    articles: [
        {
            slug: 'menu-source-audit',
            cluster: 'source-audit',
            title: 'Find every place customers may still see an old menu',
            metaTitle: 'Menu Source Audit for Restaurants | MenuList',
            metaDescription: 'Check Google, QR codes, WhatsApp, Instagram, PDFs, staff files, websites, and branch copies for old menu versions.',
            description: 'A practical audit for finding old menu copies before they confuse customers.',
            quickAnswer: 'A menu source audit checks every public and staff-shared place where a customer might still see old prices, old items, or an outdated menu file. The goal is one current approved menu link behind every surface.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.82,
            primaryCta: { label: 'Upload your current menu', href: '/create-menu' },
            relatedSlugs: ['official-menu-source', 'google-business-profile-menu', 'menu-update-checklist'],
            distributionSnippets: [
                'Most menu problems are not inside the menu. They are in old copies still visible on Google, WhatsApp, QR cards, and staff files.',
                'Before printing a new QR code, check where the old menu is still being shared.',
            ],
            sections: [
                {
                    id: 'why-old-menus-remain',
                    title: 'Why old menus remain visible',
                    body: [
                        'Menu changes are simple inside the business, but the old version keeps travelling. A PDF stays in WhatsApp. A table QR opens an old file. A customer photo remains on Google. A staff member sends last month\'s screenshot.',
                        'The customer only sees the mismatch. They do not know which version is correct.',
                    ],
                },
                {
                    id: 'places-to-check',
                    title: 'Places to check first',
                    body: [
                        'Start with the surfaces customers use before they call, visit, order, or share the business.',
                    ],
                    checklist: [
                        'Google Business Profile menu link',
                        'Google menu photos uploaded by the owner or customers',
                        'QR codes on tables, counters, windows, packaging, and bill folders',
                        'WhatsApp catalog links, groups, and saved replies',
                        'Instagram bio link, story highlights, and old posts',
                        'Business website menu page or PDF',
                        'Printed PDFs, takeaway flyers, and table tents',
                        'Staff phones, staff shared folders, and front-desk files',
                        'Delivery or ordering links that show menu content',
                        'Branch-specific copies for each location',
                    ],
                },
                {
                    id: 'monthly-check',
                    title: 'Monthly check',
                    body: [
                        'The audit should be short enough to run after price changes, availability changes, and seasonal menu changes.',
                    ],
                    checklist: [
                        'Open the QR code with a customer phone.',
                        'Search the business on Google and open every menu surface shown.',
                        'Open the Instagram and WhatsApp links customers see.',
                        'Ask one staff member what menu file they send when a customer asks.',
                        'Confirm branch managers are not using copied menus from an older outlet.',
                    ],
                },
                {
                    id: 'how-menulist-fits',
                    title: 'How MenuList fits',
                    body: [
                        'MenuList gives the business one approved menu source and public link. QR, website links, saved menu shortcuts, print assets, and official pages can point back to that current source.',
                        'External platforms still decide what they crawl, show, cache, or refresh. The MenuList job is to make the official source clearer and easier to reuse.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'audit-frequency',
                    question: 'How often should a business run this audit?',
                    answer: 'Run it after every price change, seasonal menu change, branch change, or printed QR update. For stable menus, a monthly check is enough.',
                },
                {
                    id: 'google-photos-removal',
                    question: 'Does MenuList remove old Google photos?',
                    answer: 'No. Google controls Google Business Profile content. MenuList gives the owner a current official menu source to place in the right fields and public links.',
                },
                {
                    id: 'old-pdf-deletion',
                    question: 'Should every old PDF be deleted?',
                    answer: 'Old public PDFs should stop being the main customer source. A current PDF can still be useful for print or backup when it is generated from the approved menu.',
                },
            ],
        },
        {
            slug: 'menu-engineering',
            cluster: 'menu-engineering',
            title: 'Menu engineering starts with the menu customers actually see',
            metaTitle: 'Menu Engineering Starts With the Public Menu | MenuList',
            metaDescription: 'Use menu engineering basics only after the customer-facing menu is current, clear, and owner-approved.',
            description: 'A practical owner guide to menu engineering without pretending MenuList replaces food-cost or POS analysis.',
            quickAnswer: 'Menu engineering reviews items, pricing, placement, and customer clarity. It works better when the public menu is current first, because owners cannot improve a menu customers are not actually seeing.',
            readingTime: '7 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.78,
            primaryCta: { label: 'Upload your current menu', href: '/create-menu' },
            relatedSlugs: ['menu-engineering-worksheet', 'official-menu-source', 'restaurant-menu-seo'],
            distributionSnippets: [
                'Menu engineering does not start in a spreadsheet. It starts with the menu customers actually see.',
            ],
            sections: [
                {
                    id: 'meaning',
                    title: 'What menu engineering means',
                    body: [
                        'Menu engineering usually groups items by popularity and margin. Owners use that view to decide which items to feature, rewrite, reprice, move, or remove.',
                        'MenuList should not claim to calculate full profitability unless food-cost and sales data are connected. The safe first step is keeping the public menu current and easier to review.',
                    ],
                },
                {
                    id: 'customer-facing-first',
                    title: 'The customer-facing menu comes first',
                    body: [
                        'If customers see old prices or old items, better item labels and better placement will not fix the main problem. The owner needs one current menu before judging what to improve.',
                    ],
                    bullets: [
                        'Item names should match what staff and customers use.',
                        'Prices should match the current approved menu.',
                        'Descriptions should make choice easier, not longer.',
                        'Photos should match the item being sold.',
                        'Sections should follow how customers decide.',
                    ],
                },
                {
                    id: 'matrix',
                    title: 'The basic menu engineering matrix',
                    comparisonRows: [
                        { label: 'Stars', left: 'High popularity', right: 'High margin' },
                        { label: 'Puzzles', left: 'Low popularity', right: 'High margin' },
                        { label: 'Plowhorses', left: 'High popularity', right: 'Low margin' },
                        { label: 'Dogs', left: 'Low popularity', right: 'Low margin' },
                    ],
                },
                {
                    id: 'actions',
                    title: 'Useful actions',
                    checklist: [
                        'Keep stars visible and easy to order.',
                        'Rewrite or reposition puzzles before removing them.',
                        'Review plowhorse pricing, portion, and placement.',
                        'Remove or hide dogs only after checking operational need.',
                        'Keep public prices aligned before printing new material.',
                    ],
                },
                {
                    id: 'how-menulist-fits',
                    title: 'How MenuList fits',
                    body: [
                        'MenuList keeps the public menu source structured, current, and owner-approved. That gives the owner a cleaner starting point for menu review, QR placement, public search copy, and print material.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'profitability-calculation',
                    question: 'Does MenuList calculate item profitability?',
                    answer: 'No. MenuList can keep the public menu source current and structured. Full profitability engineering needs food-cost and sales data.',
                },
                {
                    id: 'engineering-without-pos',
                    question: 'Can menu engineering be done without POS data?',
                    answer: 'A basic review can use owner knowledge, staff input, and customer clarity. POS data makes it stronger, but the public menu still needs to be current first.',
                },
            ],
        },
        {
            slug: 'qr-menu-for-restaurants',
            cluster: 'qr-menu',
            title: 'A QR code is only useful when the menu behind it is current',
            metaTitle: 'QR Menu for Restaurants | MenuList',
            metaDescription: 'Plan QR menus around one stable menu link, table placement, scan testing, and current customer-facing content.',
            description: 'A QR menu guide focused on the source behind the code.',
            quickAnswer: 'A restaurant QR code should open one stable, current, mobile-friendly menu link. The QR itself is only a doorway. The menu source behind it decides whether customers trust it.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.78,
            primaryCta: { label: 'Create one official QR menu', href: '/create-menu' },
            relatedSlugs: ['qr-code-placement-checklist', 'digital-menu-vs-pdf-menu', 'official-menu-source'],
            sections: [
                {
                    id: 'what-qr-opens',
                    title: 'What the QR should open',
                    body: [
                        'The QR should open a current public menu page that works on a phone, shows business identity, and stays readable without downloading a heavy file.',
                    ],
                    bullets: [
                        'Current item names and prices',
                        'Clear sections',
                        'Open status and business details when available',
                        'Call, WhatsApp, directions, or ordering handoffs when the business has them',
                        'A stable URL that can stay the same after menu changes',
                    ],
                },
                {
                    id: 'why-qr-fails',
                    title: 'Why QR menus fail',
                    checklist: [
                        'The QR opens an old PDF.',
                        'The page is hard to read on a phone.',
                        'The link changes after every menu update.',
                        'Staff print new QR cards without checking the old ones.',
                        'Customers scan in poor lighting or from too far away.',
                    ],
                },
                {
                    id: 'placement',
                    title: 'Where to place QR codes',
                    body: [
                        'QR placement should match where customers decide. A table QR is useful for browsing. A counter QR works for takeaway. A packaging QR works for repeat customers after they leave.',
                    ],
                    checklist: [
                        'Tables and counters',
                        'Entrance or waiting area',
                        'Bill folders and receipts',
                        'Takeaway packaging',
                        'Delivery bag stickers',
                        'Window posters',
                    ],
                },
                {
                    id: 'testing',
                    title: 'Scan testing before printing',
                    checklist: [
                        'Test with iPhone and Android.',
                        'Test in the same lighting customers will use.',
                        'Open the link on mobile data, not only Wi-Fi.',
                        'Confirm the page opens the current menu.',
                        'Keep the readable short URL printed under the QR.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'qr-opens-pdf',
                    question: 'Should a QR code open a PDF?',
                    answer: 'A PDF can work as a backup, but it should not be the main customer source when the menu changes often.',
                },
                {
                    id: 'same-qr-after-changes',
                    question: 'Can the same QR work after menu changes?',
                    answer: 'Yes, when the QR points to a stable MenuList link and the menu behind that link is updated.',
                },
            ],
        },
        {
            slug: 'digital-menu-vs-pdf-menu',
            cluster: 'official-source',
            title: 'A PDF can be useful, but it should not be your main public menu source',
            metaTitle: 'Digital Menu vs PDF Menu | MenuList',
            metaDescription: 'Compare mobile digital menus, PDFs, and print files for QR codes, WhatsApp, Google links, updates, and customer trust.',
            description: 'A comparison page for owners still using menu PDFs and print files everywhere.',
            quickAnswer: 'A PDF or print file is useful for print, controlled sharing, and backup, but a mobile digital menu is usually better as the main public source because it can stay current, searchable, and easier to read on phones.',
            readingTime: '5 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.76,
            primaryCta: { label: 'Replace your old PDF menu', href: '/create-menu' },
            relatedSlugs: ['qr-menu-for-restaurants', 'official-menu-source', 'menu-update-checklist'],
            sections: [
                {
                    id: 'pdf-useful',
                    title: 'Where PDFs are useful',
                    bullets: [
                        'Printer handoff packet',
                        'A backup file for staff',
                        'A static takeaway menu when prices rarely change',
                        'A downloadable version generated from the current approved menu',
                    ],
                },
                {
                    id: 'pdf-problems',
                    title: 'Where PDFs create problems',
                    body: [
                        'PDFs keep circulating after the menu changes. A customer may open a saved file from last month and treat it as current.',
                    ],
                    checklist: [
                        'Old prices remain in WhatsApp.',
                        'Large files load slowly on mobile data.',
                        'Text may be hard to zoom and scan.',
                        'Multiple PDF versions create source confusion.',
                    ],
                },
                {
                    id: 'comparison',
                    title: 'Digital menu vs PDF menu',
                    comparisonRows: [
                        { label: 'Mobile reading', left: 'Built for phone browsing', right: 'Often requires zooming' },
                        { label: 'Updates', left: 'Same link can show the latest menu', right: 'New file must replace old copies' },
                        { label: 'Search', left: 'Customers can search and jump sections', right: 'Depends on PDF quality' },
                        { label: 'Print', left: 'Can generate current PDF and printer handoff files', right: 'Good for direct printing' },
                    ],
                },
                {
                    id: 'safe-setup',
                    title: 'The safer setup',
                    body: [
                        'Use a current digital menu page as the main customer source. When you need paper, WhatsApp, or a printer handoff, generate the PDF or packet from that approved menu instead of maintaining a separate file.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'stop-using-pdfs',
                    question: 'Should a business stop using PDFs completely?',
                    answer: 'No. PDFs and print packets still work for print and controlled sharing. They should be generated from the current approved menu, not maintained as the main public source.',
                },
            ],
        },
        {
            slug: 'google-business-profile-menu',
            cluster: 'google-menu',
            title: 'Give Google one clearer menu source to read',
            metaTitle: 'Google Business Profile Menu Source | MenuList',
            metaDescription: 'Use one current menu link for Google Business Profile while avoiding claims about ranking, refresh timing, or automatic Google updates.',
            description: 'A careful owner guide for Google menu links, photos, and old menu cleanup.',
            quickAnswer: 'Google Business Profile can show menu links, menu photos, and customer-uploaded images. A current official menu link reduces confusion, but Google decides what it crawls, shows, and refreshes.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.8,
            primaryCta: { label: 'Use one official menu link', href: '/create-menu' },
            relatedSlugs: ['menu-source-audit', 'restaurant-menu-seo', 'ai-search-menu-discovery'],
            distributionSnippets: [
                'Google cannot fix a scattered menu system by itself. Give it one clearer current source to read.',
            ],
            sections: [
                {
                    id: 'why-outdated',
                    title: 'Why Google menu information becomes outdated',
                    body: [
                        'Google may show business links, menu links, photos, customer-uploaded images, and other discovered content. If old files remain public, customers can still find them.',
                    ],
                },
                {
                    id: 'what-to-check',
                    title: 'What to check in Google Business Profile',
                    checklist: [
                        'Menu URL or website field',
                        'Owner-uploaded menu photos',
                        'Customer-uploaded menu photos',
                        'Old PDF links on the business website',
                        'Preferred menu source settings where available',
                        'Business hours, phone, and address consistency',
                    ],
                },
                {
                    id: 'old-menu-cleanup',
                    title: 'Old menu cleanup',
                    body: [
                        'The owner should remove or replace menu photos and links they control. Customer-uploaded photos may need reporting or owner-side management through Google tools.',
                    ],
                    checklist: [
                        'Replace the menu link with the current official menu URL.',
                        'Remove owner-uploaded outdated menu photos.',
                        'Report customer-uploaded old menu photos when appropriate.',
                        'Check the visible customer view after changes.',
                        'Keep the same current menu URL on QR, Instagram, WhatsApp, and the business website.',
                    ],
                },
                {
                    id: 'claim-limit',
                    title: 'What MenuList does not control',
                    body: [
                        'MenuList does not control Google ranking, Google Maps placement, photo removal decisions, crawl timing, or AI summaries. MenuList prepares a clearer official menu source that owners can place where Google and customers look.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'automatic-google-update',
                    question: 'Will a MenuList link update Google automatically?',
                    answer: 'No. Owners still manage Google Business Profile. MenuList gives them a current official menu link to use.',
                },
                {
                    id: 'old-customer-photos',
                    question: 'Can old customer menu photos remain visible?',
                    answer: 'Yes. Google controls customer-uploaded photos. Owners can manage or report them through Google Business Profile tools.',
                },
            ],
        },
        {
            slug: 'official-menu-source',
            cluster: 'official-source',
            title: 'Customers should not have to guess which menu is correct',
            metaTitle: 'Official Menu Source for Restaurants | MenuList',
            metaDescription: 'Define one approved public menu source for QR codes, Google, WhatsApp, Instagram, websites, print, and multi-location teams.',
            description: 'The core MenuList concept explained in owner language.',
            quickAnswer: 'An official menu source is the owner-approved menu version that every public link and material should point to. Customers should not compare PDFs, photos, and QR links to guess what is current.',
            readingTime: '5 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.8,
            primaryCta: { label: 'Create one official menu source', href: '/create-menu' },
            relatedSlugs: ['menu-source-audit', 'digital-menu-vs-pdf-menu', 'multi-location-menu-management'],
            sections: [
                {
                    id: 'problem',
                    title: 'The problem with menu copies everywhere',
                    body: [
                        'A business can have one current menu internally and many outdated copies publicly. Customers see screenshots, saved PDFs, old QR links, Google photos, Instagram posts, and staff-shared files.',
                        'The official source gives every surface a single place to point.',
                    ],
                },
                {
                    id: 'what-source-includes',
                    title: 'What an official menu source should include',
                    checklist: [
                        'Business name and identity',
                        'Current sections, items, prices, and availability',
                        'Menu update or freshness signals',
                        'Phone-friendly layout',
                        'Call, WhatsApp, directions, order, or reservation handoffs when used',
                        'Stable URL for QR, Google, Instagram, WhatsApp, print, and website links',
                    ],
                },
                {
                    id: 'when-prices-change',
                    title: 'When prices or items change',
                    body: [
                        'The owner updates the approved source. The QR and customer links should keep opening the current version instead of forcing the owner to chase every old file.',
                    ],
                },
                {
                    id: 'how-menulist-fits',
                    title: 'How MenuList fits',
                    body: [
                        'MenuList turns the current menu into a structured public source. The same source can support QR menus, official pages, sharing links, print/PDF assets, screens, and multi-location control.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'official-source-vs-website',
                    question: 'Is an official menu source the same as a website?',
                    answer: 'Not exactly. A website can include many pages. The official menu source is the current menu truth customers should reach from every public surface.',
                },
            ],
        },
        {
            slug: 'restaurant-menu-seo',
            cluster: 'menu-seo',
            title: 'Make your menu easier for customers and search systems to understand',
            metaTitle: 'Restaurant Menu SEO Guide | MenuList',
            metaDescription: 'Learn how visible menu text, stable URLs, headings, metadata, internal links, and structured data support menu discovery without ranking promises.',
            description: 'A practical SEO guide for restaurant menu pages.',
            quickAnswer: 'Restaurant menu SEO starts with visible text, a stable menu URL, clear headings, useful metadata, internal links, and structured data that matches the page. No system can guarantee rankings.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.78,
            primaryCta: { label: 'Publish an official menu page', href: '/create-menu' },
            relatedSlugs: ['google-business-profile-menu', 'ai-search-menu-discovery', 'official-menu-source'],
            sections: [
                {
                    id: 'visible-text',
                    title: 'Visible text matters',
                    body: [
                        'Search systems and answer engines need readable page content. A menu trapped inside an image or old PDF is harder to understand than a structured page with visible item names, sections, prices, and business context.',
                    ],
                },
                {
                    id: 'stable-url',
                    title: 'A stable menu URL matters',
                    body: [
                        'A stable URL lets QR codes, Google fields, social profiles, and customers point to the same place. The content can update behind the link while the link remains familiar.',
                    ],
                },
                {
                    id: 'seo-basics',
                    title: 'Useful menu SEO basics',
                    checklist: [
                        'One H1 for the page.',
                        'Clear section headings.',
                        'Readable item names and descriptions.',
                        'Metadata that matches visible page content.',
                        'Internal links from the homepage or business page to the menu.',
                        'Schema that describes only what the page visibly shows.',
                    ],
                },
                {
                    id: 'claim-limit',
                    title: 'What SEO cannot promise',
                    body: [
                        'Search engines decide crawling, ranking, rich results, and snippets. A better menu page gives them a clearer source, but it does not force placement.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'structured-data-guarantee',
                    question: 'Does structured data guarantee rich results?',
                    answer: 'No. Structured data should match visible content. Search engines decide whether to use it.',
                },
            ],
        },
        {
            slug: 'ai-search-menu-discovery',
            cluster: 'ai-discovery',
            title: 'Make your current menu easier for search and AI systems to understand',
            metaTitle: 'AI Search Menu Discovery | MenuList',
            metaDescription: 'Prepare a clearer public menu source for search and AI systems with visible HTML, schema, sitemap, robots, and LLM context files.',
            description: 'A careful AEO guide without ranking or citation promises.',
            quickAnswer: 'AI search systems work better with clear public sources. A current menu page with visible text, schema, sitemap signals, robots policy, and LLM context is easier to read than scattered PDFs and old images.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.78,
            primaryCta: { label: 'Create one official menu source', href: '/create-menu' },
            relatedSlugs: ['restaurant-menu-seo', 'official-menu-source', 'google-business-profile-menu'],
            sections: [
                {
                    id: 'why-ai-needs-source',
                    title: 'Why AI systems need a clear source',
                    body: [
                        'AI assistants and answer systems may summarize public information from search results, crawled pages, user-triggered fetches, and structured data. When old menu copies remain online, summaries can become uncertain or stale.',
                    ],
                },
                {
                    id: 'what-readable-means',
                    title: 'What readable means',
                    checklist: [
                        'Important menu text is visible in HTML.',
                        'Schema matches visible page content.',
                        'Sitemap lists active public pages.',
                        'Robots policy is intentional.',
                        'LLM context files explain public facts and boundaries.',
                        'The page states what external systems decide for themselves.',
                    ],
                },
                {
                    id: 'scattered-sources',
                    title: 'Why scattered files confuse answers',
                    body: [
                        'A current menu page says one thing. An old PDF, an old Google photo, and an old WhatsApp image say something else. The clearer source should be the one the owner maintains.',
                    ],
                },
                {
                    id: 'claim-limit',
                    title: 'What MenuList does not guarantee',
                    body: [
                        'MenuList does not guarantee Google rankings, ChatGPT citations, AI answer placement, crawl timing, or external platform refreshes. MenuList prepares a clearer public source for those systems to read when they choose to.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'llms-required-google-ai',
                    question: 'Is llms.txt required for Google AI features?',
                    answer: 'No. Google says normal search fundamentals still matter. MenuList uses LLM context files as an additional public-agent contract, not as a Google requirement.',
                },
            ],
        },
        {
            slug: 'menu-update-checklist',
            cluster: 'checklists',
            title: 'Check the public menu before and after every update',
            metaTitle: 'Restaurant Menu Update Checklist | MenuList',
            metaDescription: 'Use this checklist before changing prices, availability, descriptions, QR links, Google menu links, PDFs, and staff-shared menu files.',
            description: 'A working checklist for safe menu changes.',
            quickAnswer: 'A menu update is not finished when the owner changes the internal menu. It is finished when customers can see the current approved version on the public surfaces they use.',
            readingTime: '5 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.76,
            primaryCta: { label: 'Review your menu source', href: '/create-menu' },
            relatedSlugs: ['menu-source-audit', 'official-menu-source', 'digital-menu-vs-pdf-menu'],
            sections: [
                {
                    id: 'before-update',
                    title: 'Before updating',
                    checklist: [
                        'Confirm item names and spelling.',
                        'Confirm current prices and currency.',
                        'Mark unavailable items clearly.',
                        'Check photos still match items.',
                        'Check descriptions are short and useful.',
                        'Confirm categories still make sense.',
                    ],
                },
                {
                    id: 'after-update',
                    title: 'After updating',
                    checklist: [
                        'Open the public menu on a phone.',
                        'Scan the main QR code.',
                        'Open the Google menu link if used.',
                        'Open the Instagram and WhatsApp links.',
                        'Replace old PDFs or print files if they changed.',
                        'Tell staff which link to send customers.',
                    ],
                },
                {
                    id: 'branch-updates',
                    title: 'Branch and outlet updates',
                    body: [
                        'For multi-location businesses, confirm whether the change applies to every outlet or only one location.',
                    ],
                    checklist: [
                        'Shared master menu updated.',
                        'Location-level price differences checked.',
                        'Local unavailable items checked.',
                        'Branch QR links tested.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'biggest-update-mistake',
                    question: 'What is the biggest update mistake?',
                    answer: 'Changing the menu in one place while customers still see old prices in another place.',
                },
            ],
        },
        {
            slug: 'qr-code-placement-checklist',
            cluster: 'checklists',
            title: 'Place QR codes where customers can scan them without asking staff',
            metaTitle: 'QR Code Placement Checklist for Restaurants | MenuList',
            metaDescription: 'Use this checklist for QR code size, table placement, counter placement, packaging, lighting, fallback URLs, and scan testing.',
            description: 'A practical QR placement checklist for owners, staff, and printers.',
            quickAnswer: 'A good QR setup uses the right size, clear placement, good lighting, a readable fallback URL, and scan testing on real customer phones before printing at scale.',
            readingTime: '5 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.76,
            primaryCta: { label: 'Create one QR menu source', href: '/create-menu' },
            relatedSlugs: ['qr-menu-for-restaurants', 'menu-source-audit', 'digital-menu-vs-pdf-menu'],
            sections: [
                {
                    id: 'placement',
                    title: 'Placement checklist',
                    checklist: [
                        'Table card visible from normal seated position.',
                        'Counter QR near ordering or payment point.',
                        'Window QR readable from outside if used.',
                        'Packaging QR placed on a flat visible area.',
                        'Bill-folder or receipt QR does not fold across the code.',
                        'Fallback short URL printed below the code.',
                    ],
                },
                {
                    id: 'size-lighting',
                    title: 'Size and lighting',
                    checklist: [
                        'Print test at the final size before bulk printing.',
                        'Avoid glossy glare where lighting is strong.',
                        'Keep quiet space around the QR.',
                        'Use strong contrast.',
                        'Do not place on curved or heavily textured surfaces.',
                    ],
                },
                {
                    id: 'scan-test',
                    title: 'Scan test',
                    checklist: [
                        'Test iPhone camera.',
                        'Test Android camera.',
                        'Test in-store Wi-Fi and mobile data.',
                        'Confirm the page opens the current menu.',
                        'Ask staff to test before placing cards on tables.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'table-specific-qr',
                    question: 'Should each table have a different QR?',
                    answer: 'Not for the menu source. A single official menu link is simpler. Table-specific codes only matter when a separate ordering system needs table identity.',
                },
            ],
        },
        {
            slug: 'menu-engineering-worksheet',
            cluster: 'menu-engineering',
            title: 'Review menu items with a simple worksheet',
            metaTitle: 'Menu Engineering Worksheet | MenuList',
            metaDescription: 'Use a simple item worksheet for section, price, cost estimate, popularity estimate, margin estimate, clarity, and next action.',
            description: 'An HTML-first worksheet for reviewing menu items before changing public menus.',
            quickAnswer: 'A useful menu worksheet gives each item a section, current price, rough cost, popularity estimate, margin estimate, customer clarity score, and next action.',
            readingTime: '5 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.74,
            primaryCta: { label: 'Start from your current menu', href: '/create-menu' },
            relatedSlugs: ['menu-engineering', 'menu-update-checklist', 'official-menu-source'],
            sections: [
                {
                    id: 'worksheet-fields',
                    title: 'Worksheet fields',
                    checklist: [
                        'Item name',
                        'Section',
                        'Current price',
                        'Cost estimate',
                        'Popularity estimate',
                        'Margin estimate',
                        'Customer clarity',
                        'Action: keep, rewrite, reprice, move, remove, or test',
                    ],
                },
                {
                    id: 'how-to-use',
                    title: 'How to use it',
                    body: [
                        'Use the worksheet after the current public menu is structured. Review one section at a time so the owner is not forced to redesign the full menu at once.',
                    ],
                    checklist: [
                        'Mark best-known items first.',
                        'Mark confusing item names.',
                        'Find items with unclear prices or weak descriptions.',
                        'Decide what should be more visible.',
                        'Update the public menu only after owner approval.',
                    ],
                },
                {
                    id: 'claim-limit',
                    title: 'What this worksheet is not',
                    body: [
                        'This is not a POS profitability report. It is a practical owner review tool. Use food-cost and sales systems for exact margin analysis.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'staff-worksheet',
                    question: 'Can staff fill this worksheet?',
                    answer: 'Staff can add notes, but owner approval should remain the final source before public changes go live.',
                },
            ],
        },
        {
            slug: 'multi-location-menu-management',
            cluster: 'multi-location',
            title: 'Keep outlet menus aligned without hiding local differences',
            metaTitle: 'Multi-location Menu Management | MenuList',
            metaDescription: 'Manage master menus, outlet differences, branch price drift, local availability, and public link consistency from one approved source.',
            description: 'A guide for brands running more than one location.',
            quickAnswer: 'Multi-location menu management needs one approved master source plus controlled outlet differences for price, availability, local items, and branch-specific details.',
            readingTime: '6 min',
            publishedAt,
            updatedAt,
            changeFrequency: 'monthly',
            priority: 0.76,
            primaryCta: { label: 'Set up your first location', href: '/create-menu' },
            relatedSlugs: ['official-menu-source', 'menu-update-checklist', 'menu-source-audit'],
            sections: [
                {
                    id: 'why-branches-drift',
                    title: 'Why branch menus drift',
                    body: [
                        'One outlet changes a price. Another runs out of an item. A third prints old QR material. Over time the brand has many menu versions and no simple way to know what customers see.',
                    ],
                },
                {
                    id: 'master-vs-outlet',
                    title: 'Master menu and outlet menu',
                    comparisonRows: [
                        { label: 'Master menu', left: 'Shared item structure, brand sections, common descriptions', right: 'Used as the approved source' },
                        { label: 'Outlet menu', left: 'Local price, availability, local item, branch details', right: 'Used for customer truth at that branch' },
                    ],
                },
                {
                    id: 'what-to-control',
                    title: 'What to control',
                    checklist: [
                        'Shared item names and sections',
                        'Outlet-level price differences',
                        'Local availability',
                        'Branch-specific service modes',
                        'QR links for each outlet',
                        'Google and social links per outlet',
                        'Printed materials per outlet',
                    ],
                },
                {
                    id: 'how-menulist-fits',
                    title: 'How MenuList fits',
                    body: [
                        'MenuList supports a master menu and outlet-aware control so businesses can keep the shared source stable while preserving local differences where needed.',
                    ],
                },
            ],
            faq: [
                {
                    id: 'same-menu-every-outlet',
                    question: 'Should every outlet show exactly the same menu?',
                    answer: 'Only when the business actually operates that way. The safer setup is shared structure with controlled outlet differences.',
                },
            ],
        },
    ],
};
