export const CANONICA_PRE_ONBOARDING_PROMPT_TITLE = 'Canonica Pre-Onboarding Master Prompt';

export function renderCanonicaPreOnboardingOwnerGuide(): string {
    return [
        '# Canonica Pre-Onboarding Owner Guide',
        '',
        'Use this guide before you run the Canonica pre-onboarding prompt in your AI coding tool.',
        '',
        '## What You Are Preparing',
        '',
        'You are preparing source truth for Canonica Knowledge Intake. The goal is not to make a polished marketing document. The goal is to give Canonica enough reviewed product context to create support drafts, product surface mappings, FAQ seeds, answer proposals, and live-support readiness checks.',
        '',
        '## Minimum Inputs',
        '',
        'At minimum, give the agent:',
        '',
        '- product name;',
        '- public website URL, docs URL, local repo/docs path, or owner-written product notes;',
        '- product stage: public live, private beta, pre-launch, or docs-only;',
        '- source mode: repo and website, multi-product repo, website only, docs only, owner notes only, or mixed;',
        '- support contact or escalation path;',
        '- approval status for legal, pricing, privacy, security, screenshots, and marketing use.',
        '',
        '## Fields You Will Fill In The Prompt',
        '',
        '- `PRODUCT_NAME`: paste the product name.',
        '- `PRODUCT_SLUG`: paste a short lowercase slug for the output folder.',
        '- `PUBLIC_WEBSITE_URL`: paste the website link or `NOT_AVAILABLE`.',
        '- `PRODUCTION_APP_URL`: paste the app/login link or `NOT_AVAILABLE`.',
        '- `REPO_OR_DOCS_PATH`: paste the local repo/docs path or `NOT_AVAILABLE`.',
        '- `TARGET_PRODUCT_PATHS`: paste target app/package/docs paths when a repo contains multiple products, or `NOT_AVAILABLE`.',
        '- `EXCLUDED_PRODUCT_NAMES`: paste sister products that must stay out, or `NOT_AVAILABLE`.',
        '- `HELP_DOCS_URLS`: paste docs/help links or `NOT_AVAILABLE`.',
        '- `OPENAPI_OR_API_SPEC_PATHS`: paste public API spec paths/URLs or `NOT_AVAILABLE`.',
        '- `SUPPORT_EXPORT_PATHS`: paste support macro, FAQ, solved-ticket, or CSV/Markdown export paths or `NOT_AVAILABLE`.',
        '- `DEMO_RECORDING_OR_SCREENSHOT_PATHS`: paste approved demo recording/screenshot paths or `NOT_AVAILABLE`.',
        '- `WEBSITE_ASSET_REQUEST`: choose `none`, `faq`, `website_copy_brief`, `demo_walkthrough`, `screenshots`, or `mixed`.',
        '- `PRICING_URL`, `PRIVACY_URL`, `TERMS_URL`, `REFUND_OR_CANCELLATION_URL`, `SECURITY_TRUST_URL`, `CONTACT_URL`: paste links or `NOT_AVAILABLE`.',
        '- `SUPPORT_EMAIL`: paste the support email or `NOT_AVAILABLE`.',
        '- `SOURCE_MODE`: choose `repo_and_website`, `multi_product_repo`, `website_only`, `docs_only`, `owner_notes_only`, or `mixed`.',
        '- `PRODUCT_STAGE`: choose `public_live`, `private_beta`, `pre_launch`, or `docs_only`.',
        '- `APPROVAL_STATUS`, `SCREENSHOT_MARKETING_PERMISSION`, `CANONICA_WORKSPACE_STATUS`: paste the current approval/workspace status.',
        '- `OWNER_NOTES`: paste a short product summary or `NOT_AVAILABLE`.',
        '',
        '## Best Setup',
        '',
        'Use the strongest source bundle you have. A product repo is helpful, but it is not required. The agent can work from any combination of:',
        '',
        '- product repo files when available;',
        '- docs and help content;',
        '- public website source or live URLs;',
        '- route definitions or page files;',
        '- pricing, terms, privacy, security, and contact pages;',
        '- OpenAPI/API specs for public APIs;',
        '- support exports, macros, solved-ticket patterns, or FAQ files;',
        '- approved recordings for product walkthroughs;',
        '- existing support macros, FAQs, changelogs, and onboarding notes;',
        '- approved screenshots or demo data notes.',
        '',
        '## If You Have A Product Repo',
        '',
        '1. Open the repo in your AI IDE.',
        '2. Make sure current docs are present locally.',
        '3. Paste the master prompt.',
        '4. Fill in the product name, website, app URL, docs URLs, and approval status.',
        '5. Let the agent inspect the repo and public website.',
        '6. Ask it to patch any gaps before final handoff.',
        '7. Review the generated folder before upload.',
        '',
        '## If The Repo Has Multiple Products',
        '',
        'Tell the agent which product Canonica is onboarding. Fill `TARGET_PRODUCT_PATHS` when you know them and `EXCLUDED_PRODUCT_NAMES` for sister products that must stay out. The agent should map the codebase first, include shared infrastructure only when it affects the target product, and document exclusions before upload.',
        '',
        '## If You Do Not Have A Product Repo',
        '',
        'You can still use pre-onboarding. Give the agent:',
        '',
        '- public website URLs;',
        '- help center URLs;',
        '- pricing/legal/security/contact URLs;',
        '- product screenshots;',
        '- support macros or FAQ exports;',
        '- a written list of product pages, roles, plans, integrations, and risky topics.',
        '',
        'The agent should mark repo-code coverage as unavailable and continue from public/docs/owner-provided sources.',
        '',
        '## If You Only Have Owner Notes',
        '',
        'You can still create a starter package. Give the agent a short product summary, role list, key workflows, support email, screenshots if approved, and any known policies. The agent should mark website, repo, docs, and production checks as pending instead of filling gaps with guesses.',
        '',
        '## If You Want FAQ, Demo, Or Website Assets',
        '',
        'Fill `WEBSITE_ASSET_REQUEST` and provide approved recordings, screenshots, support exports, or API specs when available. The agent should prepare source-backed FAQ seeds, demo walkthrough briefs, website claim candidates, capture plans, and scrub rules. Treat these as review-ready briefs, not approved public assets.',
        '',
        '## What This Cannot Guarantee',
        '',
        'This process depends on what the AI tool can actually inspect. Some AI IDEs cannot browse the web, read private repos, open login-only apps, inspect recordings, or access local files without extra permission. If a source is blocked or missing, the generated package should mark that source as pending instead of claiming coverage.',
        '',
        'No prompt can guarantee perfect output for every product, model, IDE, private app, or source shape. Owner review is mandatory before uploading the package to Canonica or using the material for support, website, FAQ, demo, or screenshot assets.',
        '',
        '## What To Review Before Upload',
        '',
        'Check the generated folder for:',
        '',
        '- private customer data;',
        '- API keys, tokens, cookies, secrets, or service accounts;',
        '- payment details, invoices, or raw logs;',
        '- private support conversations;',
        '- screenshots with personal or customer information;',
        '- legal, refund, privacy, or security statements that need approval;',
        '- product claims that are not true in production.',
        '',
        'Remove or correct anything questionable before uploading to Canonica.',
        '',
        '## What To Upload First',
        '',
        'Start with the numbered files in `source-inputs/`. Upload in numeric order when possible. Then use the production onboarding files for product surfaces, live-support tests, screenshot planning, and activation review.',
        '',
        '## When To Enable Live Support',
        '',
        'Do not enable Canonica for live users until:',
        '',
        '- source files are uploaded;',
        '- drafts are reviewed;',
        '- risky topics are escalation-gated;',
        '- product surfaces are mapped;',
        '- widget context is verified;',
        '- common support test questions pass;',
        '- production-only facts are confirmed.',
        '',
        '## What Production Facts Still Need Confirmation',
        '',
        '- Active production host and app URL.',
        '- Active feature flags.',
        '- Plan/account entitlements.',
        '- Current pricing, refund, privacy, and legal text.',
        '- Widget key and allowed origins.',
        '- Approved screenshot/demo tenant.',
        '- Public marketing permission.',
        '',
        '## Good Final Output',
        '',
        'A good agent final response should tell you:',
        '',
        '- folder path;',
        '- source count;',
        '- payload count;',
        '- FAQ and test question counts;',
        '- product surface count;',
        '- screenshot register count;',
        '- largest source size;',
        '- website/docs checked;',
        '- source-access limits or blocked sources;',
        '- products detected and target product boundary if a multi-product repo was inspected;',
        '- sister products or source families excluded;',
        '- gaps found and fixed;',
        '- production confirmations still needed.',
        '',
    ].join('\n');
}

export function renderCanonicaPreOnboardingAgentGuide(): string {
    return [
        '# Canonica Pre-Onboarding Agent Guide',
        '',
        'This guide is for the AI coding agent receiving the Canonica pre-onboarding prompt.',
        '',
        '## Operating Role',
        '',
        'You are not selling Canonica and you are not publishing support answers. You are preparing a source-backed input package that the product owner can review and upload into Canonica Knowledge Intake.',
        '',
        '## First Principles',
        '',
        '1. Source truth first. Read before writing.',
        '2. Current website, current docs, and current code outrank stale plans.',
        '3. Archive or strategy material is context only unless confirmed by current sources.',
        '4. Private data stays out.',
        '5. Risky topics stay escalation-gated.',
        '6. Coverage means available-source coverage, not unchecked production reality.',
        '7. Respect the declared source mode. Do not assume every product has a repo, docs folder, public website, or route map.',
        '8. Do not claim universal compatibility or 100 percent completeness beyond the sources and tools available in the current session.',
        '9. Patch gaps before declaring readiness.',
        '',
        '## Capability Limits',
        '',
        'Before claiming completion, confirm whether you can read the supplied local repo/docs paths, access public website/help/policy URLs, inspect API specs/support exports/screenshots/recordings, and represent login-only app screens through approved exports, screenshots, recordings, or owner notes.',
        '',
        'If any capability is missing, mark that source as pending in the source evidence map and final response. No prompt can guarantee perfect output across every model, AI IDE, private app, source bundle, or product shape.',
        '',
        '## Required Discovery Pass',
        '',
        'Perform these checks when available:',
        '',
        '- live public website pages;',
        '- product/docs/help routes;',
        '- pricing, privacy, terms, refund/cancellation, security/trust, contact pages;',
        '- repo docs and README files;',
        '- product boundary indicators in monorepos or shared workspaces;',
        '- app route definitions and public route maps;',
        '- feature flags and plan/entitlement notes;',
        '- support macros, FAQs, changelogs, known issues;',
        '- screenshots, demo assets, and marketing permissions.',
        '',
        '## How To Think About Missing Context',
        '',
        'If a source is missing, do not invent it. Add a pending-confirmation note and continue with the sources that exist.',
        '',
        'Common missing-source handling:',
        '',
        '- No repo: use website/docs/owner notes and mark repo coverage unavailable.',
        '- No docs folder: use website, product UI notes, screenshots, and owner notes; mark docs coverage unavailable.',
        '- No website access: use local docs and mark website verification pending.',
        '- Multiple products in one repo: identify the target product first, include shared code only when it affects the target product support truth, and exclude sister-product docs/routes/features from Canonica inputs.',
        '- Owner notes only: create a starter package and mark repo, docs, website, legal, pricing, and production facts pending unless supplied.',
        '- No legal policy page: create a risk boundary, not policy wording.',
        '- No screenshots: create a capture plan and scrub rules.',
        '- No production account state: create activation gates.',
        '',
        '## Output Quality Bar',
        '',
        'The package should be useful to Canonica without another long discovery pass. It should include product truth, support coverage, source maps, risk boundaries, test questions, and upload skeletons.',
        '',
        '## Validation Checklist',
        '',
        'Before final handoff, validate:',
        '',
        '- manifest paths exist;',
        '- source count equals payload count;',
        '- JSON and JSONL parse;',
        '- CSV row widths are consistent;',
        '- no raw angle-bracket placeholders remain; `NOT_AVAILABLE` is allowed only with an explicit unavailable-source reason;',
        '- source files stay under the configured size cap;',
        '- support-relevant available sources are represented or explicitly excluded;',
        '- multi-product repo boundaries, target paths, shared-infra inclusions, and sister-product exclusions are documented when relevant;',
        '- website claims are represented or pending;',
        '- private data exclusions exist;',
        '- live support gates are clear.',
        '',
        '## Final Confidence Language',
        '',
        'Use this distinction:',
        '',
        '- "Complete for available source coverage" means the provided website/docs/repo/owner-note material was covered.',
        '- "Production-ready" requires active workspace, live feature flags, approved answers, widget verification, and owner signoff.',
        '',
        'Never claim 100 percent production readiness from static docs alone.',
        '',
        '## Escalation-Gated Topics',
        '',
        'Escalate or mark review-required for:',
        '',
        '- exact pricing, taxes, invoices, refunds, credits;',
        '- legal, privacy, security, compliance;',
        '- account ownership, account merge, deletion/export;',
        '- custom domain DNS values;',
        '- integrations, webhooks, external provider sync;',
        '- production incidents or suspected security issues;',
        '- screenshots or marketing use with real production data.',
        '',
    ].join('\n');
}

export function renderCanonicaPreOnboardingPrompt(): string {
    return [
        '# Canonica Pre-Onboarding Master Prompt',
        '',
        'Use this prompt in Codex, Cursor, Windsurf, Antigravity, Claude Code, or another AI coding agent before starting Canonica onboarding. It works with a full repo, a docs folder, a public website, exported notes, screenshots, or owner-written product context. Do not force every product into one reference-client repo/docs shape.',
        '',
        'Read these companion docs if available:',
        '',
        '- Owner guide: https://canonica.app/pre-onboarding/owner-guide.md',
        '- Agent guide: https://canonica.app/pre-onboarding/agent-guide.md',
        '- Human overview: https://canonica.app/pre-onboarding',
        '',
        '## Copy/Paste Intake Fields',
        '',
        'Replace the values below before starting. Use `NOT_AVAILABLE` when a field does not exist. Use `PENDING_OWNER_APPROVAL` when the fact exists but is not approved for support or marketing.',
        '',
        '```text',
        'PRODUCT_NAME = "<paste product name>"',
        'PRODUCT_SLUG = "<short lowercase slug, for example acme-support>"',
        'PUBLIC_WEBSITE_URL = "<paste website link or NOT_AVAILABLE>"',
        'PRODUCTION_APP_URL = "<paste app/login link or NOT_AVAILABLE>"',
        'REPO_OR_DOCS_PATH = "<local repo/docs path or NOT_AVAILABLE>"',
        'TARGET_PRODUCT_PATHS = "<target app/package/docs paths if repo has many products, or NOT_AVAILABLE>"',
        'EXCLUDED_PRODUCT_NAMES = "<sister products to exclude, or NOT_AVAILABLE>"',
        'HELP_DOCS_URLS = "<paste help/docs links or NOT_AVAILABLE>"',
        'OPENAPI_OR_API_SPEC_PATHS = "<paste API spec paths/URLs or NOT_AVAILABLE>"',
        'SUPPORT_EXPORT_PATHS = "<paste support macro/FAQ/ticket export paths or NOT_AVAILABLE>"',
        'DEMO_RECORDING_OR_SCREENSHOT_PATHS = "<paste approved demo recording/screenshot paths or NOT_AVAILABLE>"',
        'WEBSITE_ASSET_REQUEST = "<none | faq | website_copy_brief | demo_walkthrough | screenshots | mixed>"',
        'PRICING_URL = "<paste pricing link or NOT_AVAILABLE>"',
        'PRIVACY_URL = "<paste privacy link or NOT_AVAILABLE>"',
        'TERMS_URL = "<paste terms link or NOT_AVAILABLE>"',
        'REFUND_OR_CANCELLATION_URL = "<paste refund/cancellation link or NOT_AVAILABLE>"',
        'SECURITY_TRUST_URL = "<paste security/trust/status link or NOT_AVAILABLE>"',
        'CONTACT_URL = "<paste contact/support link or NOT_AVAILABLE>"',
        'SUPPORT_EMAIL = "<paste support email or NOT_AVAILABLE>"',
        'PRODUCT_STAGE = "<public_live | private_beta | pre_launch | docs_only>"',
        'SOURCE_MODE = "<repo_and_website | multi_product_repo | website_only | docs_only | owner_notes_only | mixed>"',
        'APPROVAL_STATUS = "<approved | pending_owner_approval>"',
        'SCREENSHOT_MARKETING_PERMISSION = "<approved | pending_owner_approval | not_allowed>"',
        'CANONICA_WORKSPACE_STATUS = "<not_created | created>"',
        'OWNER_NOTES = "<short product summary, support notes, or NOT_AVAILABLE>"',
        '```',
        '',
        '## Filled Values Checklist',
        '',
        '- Product name: <PRODUCT_NAME>',
        '- Product website URL: <PUBLIC_WEBSITE_URL>',
        '- Production app URL: <PRODUCTION_APP_URL>',
        '- Repo/docs path if available: <REPO_OR_DOCS_PATH>',
        '- Target product paths in multi-product repo: <TARGET_PRODUCT_PATHS>',
        '- Excluded sister products: <EXCLUDED_PRODUCT_NAMES>',
        '- Support/help URLs: <HELP_DOCS_URLS>',
        '- API specs: <OPENAPI_OR_API_SPEC_PATHS>',
        '- Support exports: <SUPPORT_EXPORT_PATHS>',
        '- Demo recordings/screenshots: <DEMO_RECORDING_OR_SCREENSHOT_PATHS>',
        '- Website/FAQ/demo asset request: <WEBSITE_ASSET_REQUEST>',
        '- Pricing URL: <PRICING_URL>',
        '- Privacy URL: <PRIVACY_URL>',
        '- Terms URL: <TERMS_URL>',
        '- Refund/cancellation URL: <REFUND_OR_CANCELLATION_URL>',
        '- Security/trust URL: <SECURITY_TRUST_URL>',
        '- Contact URL: <CONTACT_URL>',
        '- Support email: <SUPPORT_EMAIL>',
        '- Product stage: <PRODUCT_STAGE>',
        '- Source mode: <SOURCE_MODE>',
        '- Product owner approval status: <APPROVAL_STATUS>',
        '- Screenshot/marketing permission: <SCREENSHOT_MARKETING_PERMISSION>',
        '- Canonica workspace status: <CANONICA_WORKSPACE_STATUS>',
        '- Owner notes: <OWNER_NOTES>',
        '',
        '## Source Mode Rules',
        '',
        '- `repo_and_website`: inspect repo/docs/source files and live website/public pages. Use this when the product has both.',
        '- `multi_product_repo`: inspect the repo/workspace to map product boundaries first, then prepare sources only for the target product.',
        '- `website_only`: inspect live website, help docs, public policy pages, and owner notes. Mark repo/code coverage unavailable.',
        '- `docs_only`: inspect local or exported docs. Mark live website verification pending unless public URLs are also provided.',
        '- `owner_notes_only`: create a starter package from owner notes and screenshots only. Mark all unsupported website, docs, repo, pricing, legal, and production facts pending.',
        '- `mixed`: use every provided source, document what was missing, and do not invent unavailable source families.',
        '',
        'Keep the Canonica folder standard even when the product has fewer surfaces. For each required source family, write the best verified content from available sources, or write `Not applicable` / `Not available` with the reason and the source mode. Do not fabricate content to make the folder look complete.',
        '',
        '## Agent / IDE Capability Check',
        '',
        'Before claiming the package is complete, confirm what your current AI tool can actually do:',
        '',
        '- Can it read the local repo/docs paths provided by the owner?',
        '- Can it browse or fetch the public website URLs?',
        '- Can it inspect screenshots, recordings, support exports, and API specs?',
        '- Does it have access to login-only product screens, private repositories, or restricted documents?',
        '',
        'If any answer is no, ask the owner for exported sources, screenshots, notes, or access. If access is still unavailable, mark that source as pending in the source evidence map and final answer. This prompt is designed for capable AI coding agents, but no prompt can guarantee perfect results across every model, IDE, product, private app, or source shape.',
        '',
        '## Multi-Product Codebase Rules',
        '',
        'If the repo, workspace, or docs set contains more than one product, app, brand, tenant product, domain, package, or dashboard, do this before creating Canonica sources:',
        '',
        '1. Identify every product-like surface you can find: app folders, package names, public site folders, route groups, docs folders, domain configs, deployment targets, environment prefixes, product constants, and README files.',
        '2. Confirm the target product by matching `PRODUCT_NAME`, `PRODUCT_SLUG`, `PUBLIC_WEBSITE_URL`, `PRODUCTION_APP_URL`, and `TARGET_PRODUCT_PATHS`.',
        '3. If the target product cannot be identified with high confidence, stop and ask the owner for the target product paths/domains before preparing upload inputs.',
        '4. Include shared infrastructure only when it changes target-product support truth: authentication, billing, account roles, shared settings, shared integrations, shared widget/runtime, shared API contracts, shared legal/trust pages, or shared navigation.',
        '5. Exclude sister-product feature docs, route maps, marketing claims, screenshots, pricing, legal pages, and support flows unless they are explicitly shared with the target product.',
        '6. Add product-boundary evidence to `production-onboarding/product-boundary-and-exclusions.md` and to `source-inputs/25-source-evidence-map.md`.',
        '7. Never mix support answers across products just because they live in the same repo.',
        '',
        '## Market Pattern Handling',
        '',
        'Many products in this category accept repositories, documentation websites, public URLs, API specs, support exports, screen recordings, and screenshots, then prepare docs, FAQs, demos, or website assets. Canonica pre-onboarding should handle those owner expectations, but safely:',
        '',
        '1. Repo/docs input can explain implementation, but support truth must be written as user-facing product behavior, not internal code commentary.',
        '2. Website/import input must include include/exclude decisions. Do not crawl or summarize unrelated marketing pages, sister products, or stale pages as support truth.',
        '3. OpenAPI/API specs are valid support sources only for public or customer-facing APIs. Internal endpoints, admin-only routes, secrets, and provider callbacks stay out.',
        '4. Support exports, solved tickets, macros, and FAQ files can seed questions and coverage gaps, but raw private conversations and user identifiers must be removed.',
        '5. Screen recordings and screenshots can produce a demo walkthrough brief, capture plan, transcript outline, and support-step map. Do not claim a final demo video was produced unless an actual approved video asset exists.',
        '6. Demo/video/website/FAQ outputs must be review-ready briefs, source maps, scripts, and claim matrices. They are not approved public marketing assets until the owner signs off.',
        '7. Demo captures require approved demo data, scrub rules, and a privacy pass for names, emails, prices, analytics, customer data, internal IDs, tokens, and production incidents.',
        '',
        '## Role',
        '',
        'You are preparing a Canonica pre-onboarding input package for this product. Canonica is a Support Knowledge Control Plane. Your job is to organize source truth so Canonica can ingest, review, and govern support knowledge. You are not publishing official answers, replacing support, or uploading private production data.',
        '',
        '## Objective',
        '',
        'Create a root-level folder named, using `PRODUCT_SLUG`:',
        '',
        '    <product-slug>-canonica-pre-onboarding-inputs/',
        '',
        'This folder must contain source inputs, upload payload skeletons, production onboarding notes, product surface mappings, live support test questions, and screenshot/asset planning files that the owner can review and then upload into Canonica Knowledge Intake.',
        '',
        '## Non-Negotiable Rules',
        '',
        '1. Inspect source truth before writing final inputs.',
        '2. Prefer live product website, current docs, current code, and current public policy pages over stale strategy notes.',
        '3. Use archive/history/AI-review docs only as decision context, not as live support truth unless confirmed by current sources.',
        '4. Do not include secrets, API keys, service accounts, cookies, tokens, private customer records, payment details, raw logs, private support messages, or unapproved screenshots.',
        '5. Legal, billing, refund, privacy, security, custom domain, integration, account ownership, and production-incident topics must be escalation-gated unless exact approved source wording exists.',
        '6. If you cannot verify a claim, mark it as pending. Do not invent product behavior.',
        '7. If the user asks for 100 percent confidence, be precise: you can certify available-source coverage, but production runtime facts still require production confirmation.',
        '8. Do not claim Canonica will auto-publish answers. Canonica creates review drafts and governed outputs.',
        '9. Do not claim the prompt works perfectly with every AI IDE, every private source, or every product shape. State source-access limits clearly.',
        '',
        '## Work Plan',
        '',
        '1. Identify product context, source mode, target product boundaries, audience, core workflows, public surfaces, support-sensitive areas, and production risk.',
        '2. Check the live website and public pages when available: homepage, features/product, pricing, docs/help, security/trust, privacy, terms, refund/cancellation, contact, status, changelog.',
        '3. Inventory local repo/docs when available. If there are multiple products, first map products, target paths, shared infrastructure, and excluded sister products. Include active help docs, specs, route maps, public pages, install docs, policies, feature flags, and product-surface files only when they apply to the target product. Exclude unrelated archive/private strategy files from live support truth unless confirmed elsewhere.',
        '4. Build a coverage matrix: product identity, onboarding, core workflows, user roles, product surfaces, integrations, billing, support, policies, troubleshooting, screenshots, and marketing use.',
        '5. Create source files 01 through 26 listed below. Preserve the source-family list for Canonica consistency, but mark unavailable or not-applicable families clearly instead of guessing.',
        '6. Create API payload skeletons and a manifest that match every source file.',
        '7. Create production onboarding inputs and asset/screenshot inputs.',
        '8. Validate JSON, JSONL, CSVs, file references, source sizes, raw placeholders, and coverage.',
        '9. Patch gaps before final handoff.',
        '',
        '## Required Folder Structure',
        '',
        '    <product-slug>-canonica-pre-onboarding-inputs/',
        '      README.md',
        '      canonica-intake-plan.md',
        '      upload-manifest.json',
        '      source-inputs/',
        '      api-payloads/',
        '        README.md',
        '        create-job.json',
        '        add-source-payloads.jsonl',
        '      production-onboarding/',
        '        README.md',
        '        client-profile.json',
        '        onboarding-runbook.md',
        '        product-boundary-and-exclusions.md',
        '        product-surface-map.csv',
        '        live-support-coverage-checklist.md',
        '        live-owner-support-test-questions.csv',
        '        dashboard-demo-data-requirements.md',
        '        production-data-safety.md',
        '      asset-inputs/',
        '        README.md',
        '        screenshot-capture-plan.md',
        '        screenshot-capture-register.csv',
        '        website-asset-slots.md',
        '        demo-walkthrough-brief.md',
        '        website-and-faq-asset-brief.md',
        '        asset-source-map.json',
        '',
        '## Required Source Inputs',
        '',
        'Create these files in source-inputs/. Keep each source focused and uploadable. If a product does not have that source family, keep the file and explain `Not applicable` or `Not available` with the exact reason.',
        '',
        '01-product-context.md - what the product is, who it serves, core positioning, and what it is not.',
        '02-onboarding-and-first-use.md - how users start, import/setup data, review, and reach first value.',
        '03-public-or-customer-surfaces.md - public pages, user-facing surfaces, embed surfaces, app pages, widgets, or shareable outputs.',
        '04-correctness-and-governance.md - review, approval, accuracy, versioning, stale-data, source-of-truth, and change rules.',
        '05-operations-users-and-tenancy.md - owner/admin operations, roles, teams, tenants, locations, workspaces, permissions.',
        '06-canonica-example-story.md - why this product is a good Canonica client and what dashboard story it should show.',
        '07-asset-and-screenshot-context.md - screenshots, safe demo tenant, what can be public, what must be scrubbed.',
        '08-support-faq-seed.csv - at least 40 rows, preferably 50, with question, answer, target, risk_level, tags, source_note.',
        '09-risk-boundaries-and-review-rules.md - what Canonica must not answer without approval.',
        '10-production-onboarding-context.md - workspace, source upload, review, widget, surfaces, activation gates.',
        '11-account-access-and-onboarding-support.md - sign-in, invite, password/reset, claim/access, blocked access.',
        '12-core-workflow-support.md - main product workflows and routine support answers.',
        '13-public-sharing-embed-and-customer-output-support.md - links, embeds, public pages, widgets, exports, or customer outputs.',
        '14-settings-profile-and-configuration-support.md - product/account/profile/settings support.',
        '15-integrations-install-export-and-runtime-support.md - install, SDK/widget/API, integrations, sync, export, webhooks.',
        '16-billing-subscription-payments-and-plan-support.md - plan, payment, credit, usage, billing, refund boundaries.',
        '17-roles-permissions-tenancy-and-ownership-support.md - roles, workspace access, tenants, ownership transfer, account merge boundaries.',
        '18-dashboard-analytics-feedback-and-help-center-support.md - dashboard, analytics, feedback, help center, support board.',
        '19-troubleshooting-escalation-and-risk-review-support.md - safe troubleshooting and when to escalate.',
        '20-live-support-operating-contract.md - rules Canonica must follow before answering live users.',
        '21-live-support-coverage-index.md - coverage matrix mapping support areas to source files.',
        '22-live-website-public-truth.md - current website claims and public positioning.',
        '23-live-website-feature-capability-coverage.md - every website feature claim mapped to support coverage.',
        '24-public-pricing-legal-trust-and-contact-support.md - public pricing, legal, privacy, trust/security, refund, contact facts.',
        '25-source-evidence-map.md - available repo, docs, website, owner notes, screenshots, exports, product-boundary evidence, excluded sister-product evidence, or unavailable-source map and what each source family covers.',
        '26-undercovered-operations-from-available-sources.md - support-relevant features discovered late in available sources that earlier files missed.',
        '',
        '## Required CSV Standards',
        '',
        'FAQ CSV columns:',
        'question,answer,target,risk_level,tags,source_note',
        '',
        'Owner support test CSV columns:',
        'id,question,coverage_area,expected_behavior,risk_level',
        '',
        'Product surface map columns:',
        'surface_key,label,product,route_patterns,feature,page,workflow,user_role,entity_hints,screenshot_priority,notes',
        '',
        'Screenshot register columns:',
        'priority,file_name,product,surface,viewport,source,can_public_use,scrub_level,status,notes',
        '',
        '## Canonica Payload Requirements',
        '',
        'Create api-payloads/create-job.json with:',
        '',
        '- title',
        '- description',
        '- productWebsiteUrl',
        '- appUrl',
        '- targetAudience',
        '',
        'Create api-payloads/add-source-payloads.jsonl with one JSON object per source file. Each line should include:',
        '',
        '- type',
        '- title',
        '- fileName',
        '- mimeType',
        '- tags',
        '- contextKeys',
        '- metadata.packagePath',
        '- metadata.sourceProduct',
        '- sourceUrls when a source came from public URLs',
        '',
        'Do not include contentText by default unless the owner explicitly wants API-ready payloads with source bodies.',
        '',
        '## Production Readiness Gates',
        '',
        'Before live Canonica support is enabled, the package must say that the owner still needs to confirm:',
        '',
        '- active production host and app URL',
        '- Canonica workspace and license',
        '- uploaded source set',
        '- approved canonical answers',
        '- risky-topic escalation rules',
        '- product surfaces',
        '- widget key and allowed origins',
        '- widget runtime last seen',
        '- safe screenshot/demo tenant',
        '- live support test questions',
        '',
        '## Validation Requirements',
        '',
        'Before final handoff, validate:',
        '',
        '- every manifest path exists',
        '- source file count equals payload line count',
        '- JSON and JSONL parse cleanly',
        '- CSV row widths are consistent',
        '- no raw angle-bracket placeholders remain; `NOT_AVAILABLE` is allowed only when the file explains why the source is unavailable',
        '- no source exceeds Canonica runtime source limits; use 40000 characters as the conservative limit unless the owner provides another limit',
        '- all high-risk topics have escalation guidance',
        '- all live website claims are represented or explicitly marked pending',
        '- all available support-relevant sources are represented or explicitly excluded',
        '- source-access limits are listed for blocked private repos, login-only apps, restricted websites, unsupported media, or unavailable files',
        '- if the repo contains multiple products, target product paths and excluded sister products are documented',
        '- if demo, FAQ, website, API, or support-export sources are provided, generated briefs distinguish review-ready material from approved public assets',
        '- private data exclusions are present',
        '- the final answer reports counts and remaining production gates',
        '',
        '## Final Answer Format',
        '',
        'When done, report:',
        '',
        '- folder path',
        '- number of source files',
        '- number of payload lines',
        '- FAQ/test question row counts',
        '- product surface count',
        '- screenshot row count',
        '- demo walkthrough and website/FAQ brief status',
        '- largest source size',
        '- website/docs checked',
        '- source-access limits or blocked sources',
        '- products detected and target product boundary if a multi-product repo was inspected',
        '- sister products or source families excluded',
        '- gaps fixed',
        '- remaining production-only confirmations',
        '',
        'Be direct. If coverage is not complete, patch it before claiming readiness. If a fact cannot be verified from available sources, mark it as a production confirmation gate.',
        '',
    ].join('\n');
}
