import { LuBookOpen, LuKeyRound, LuShieldCheck } from 'react-icons/lu';
import AnimateOnScroll, { AnimateStaggerChild } from '../shared/AnimateOnScroll';
import SectionHeading from '../shared/SectionHeading';
import SectionWrapper from '../shared/SectionWrapper';
import WebsiteButton from '../shared/WebsiteButton';
import WebsiteFeatureCard from '../shared/WebsiteFeatureCard';
import WebsiteHeadline from '../shared/WebsiteHeadline';
import WebsitePageHero from '../shared/WebsitePageHero';
import WebsiteProofStrip from '../shared/WebsiteProofStrip';

const endpoints = [
    {
        path: 'GET /api/public/v1/business',
        description: 'Returns the approved public business profile, including identity, hours, location, contact details, action links, and current public status where available.',
    },
    {
        path: 'GET /api/public/v1/menu',
        description: 'Returns the current published menu or service-list snapshot with stable item IDs, sections, prices, currency, and availability where published.',
    },
];

export default function DevelopersPage() {
    return (
        <main>
            <WebsitePageHero
                eyebrow="Developer integration"
                parts={[
                    { text: 'Read approved business truth through a ' },
                    { text: 'scoped API.', highlight: true },
                ]}
                subtitle="MenuList exposes two read-only pull endpoints for approved business and menu data. Access requires a key generated by the business owner."
                primaryCta="View OpenAPI contract"
                primaryHref="/developers/openapi"
                secondaryCta="Trust and security"
                secondaryHref="/trust-security"
            >
                <WebsiteProofStrip items={['Read only', 'X-API-Key', 'public:read scope']} />
            </WebsitePageHero>

            <SectionWrapper variant="subtle">
                <AnimateOnScroll>
                    <SectionHeading
                        title="Two endpoints. One approved source."
                        subtitle="The API is a pull interface for integrations that need the same business and menu truth MenuList publishes for customers."
                    />
                </AnimateOnScroll>
                <div className="ws-feature-card-grid" style={{ marginTop: 'var(--ws-space-10)' }}>
                    {endpoints.map((endpoint, index) => (
                        <AnimateStaggerChild key={endpoint.path} index={index}>
                            <WebsiteFeatureCard
                                icon={LuBookOpen}
                                title={<code>{endpoint.path}</code>}
                                description={endpoint.description}
                                compact
                            />
                        </AnimateStaggerChild>
                    ))}
                </div>
            </SectionWrapper>

            <SectionWrapper>
                <div className="ws-feature-card-grid">
                    <AnimateStaggerChild index={0}>
                        <WebsiteFeatureCard
                            icon={LuKeyRound}
                            title="Authentication"
                            description="Send the store-generated ml_ key in the X-API-Key header. Keys are shown once when generated in Business Settings and must carry the public:read scope."
                        />
                    </AnimateStaggerChild>
                    <AnimateStaggerChild index={1}>
                        <WebsiteFeatureCard
                            icon={LuShieldCheck}
                            title="Operational limits"
                            description="Each admitted key is limited to 60 requests per 60 seconds. Successful responses provide ETag support; errors remain private and are not cached."
                        />
                    </AnimateStaggerChild>
                </div>
            </SectionWrapper>

            <SectionWrapper variant="subtle">
                <div style={{ maxWidth: 'var(--ws-max-w-text)', margin: '0 auto' }}>
                    <AnimateOnScroll>
                        <WebsiteHeadline as="h2" text="Request example" />
                        <p className="ws-body" style={{ marginTop: 'var(--ws-space-4)' }}>
                            Replace the placeholder with the one-time key supplied by the business owner. Never place a key in browser code, a public repository, logs, or a URL.
                        </p>
                        <pre style={{ marginTop: 'var(--ws-space-6)', overflowX: 'auto', padding: 'var(--ws-space-5)', borderRadius: 'var(--ws-radius-lg)', border: '1px solid var(--ws-border-default)', background: 'var(--ws-bg-primary)' }}>
                            <code>{'curl -H "X-API-Key: ml_your_key" \\\n  https://menulist.ai/api/public/v1/business'}</code>
                        </pre>
                    </AnimateOnScroll>
                </div>
            </SectionWrapper>

            <SectionWrapper>
                <AnimateOnScroll>
                    <div style={{ maxWidth: 'var(--ws-max-w-text)', margin: '0 auto', textAlign: 'center' }}>
                        <WebsiteHeadline as="h2" text="Deliberate boundaries" />
                        <p className="ws-body" style={{ marginTop: 'var(--ws-space-4)' }}>
                            MenuList does not expose anonymous access, write endpoints, OAuth, MCP or WebMCP actions, or an official npm SDK. The similarly named package on npm is not a MenuList integration package.
                        </p>
                        <div style={{ marginTop: 'var(--ws-space-8)' }}>
                            <WebsiteButton href="/contact">Discuss an approved integration</WebsiteButton>
                        </div>
                    </div>
                </AnimateOnScroll>
            </SectionWrapper>
        </main>
    );
}
