import type { AssetSlot } from '../schemas/asset-schema';

const answerlatticeAssetRules = [
  'Use dark infrastructure visual language with restrained teal or verdigris controls.',
  'Show support knowledge governance, canonical answers, hosted help, and page-aware context.',
  'Use product-surface diagrams, status boards, and controlled proof scenes instead of generic SaaS dashboards.',
  'Keep Answerlattice separate from MenuList restaurant visuals and MenuList tenant data.',
];

const answerlatticeRejectionRules = [
  'No restaurant, menu, ordering, POS, or local business visuals.',
  'No claims that Answerlattice is a helpdesk, CMS, autonomous chatbot, or generic AI support tool.',
  'No live customer support data, private tickets, or tenant identifiers.',
  'No bright generic startup gradient art or unrelated dashboard mockups.',
  'No public capability claim that is not present in Answerlattice route/docs/runtime.',
];

export const answerlatticeAssetSlots: AssetSlot[] = [
  {
    id: 'answerlattice.home.og.main',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice website metadata',
    route: '/',
    placement: 'Open Graph and social preview',
    type: 'og-image',
    required: true,
    blocking: true,
    intent: 'Present Answerlattice as governed answer infrastructure.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [{ format: 'png', role: 'og', ratio: '1200x630', maxKb: 500 }],
    destination: 'public/answerlattice-og-image.png',
    component: 'src/app/sites/answerlattice/layout.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'src/app/sites/answerlattice/layout.tsx',
      'src/app/sites/answerlattice/components/HeroSection.tsx',
      'public/answerlattice-logo.svg',
      'public/answerlattice-og-image.svg',
      'scripts/website-assets/generate-answerlattice-logo-assets.js',
    ],
    mobile: {
      required: true,
      maxKb: 500,
      notes: 'Must read cleanly in mobile message previews.',
    },
  },
  {
    id: 'answerlattice.brand.logo.mark',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice brand system',
    route: '/',
    placement: 'static logo mark family',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Keep the Answerlattice mark consistent across metadata and static previews.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [
      { format: 'png', role: 'primary', ratio: 'icon', maxKb: 260 },
      { format: 'svg', role: 'fallback', ratio: 'icon', maxKb: 50 },
    ],
    destination: 'public/answerlattice-logo-mark.png',
    component: 'src/app/sites/answerlattice/components/AnswerlatticeLogoMark.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'src/app/sites/answerlattice/components/AnswerlatticeLogoMark.tsx',
      'src/components/atoms/answerlatticeLogoMark/index.tsx',
      'public/answerlattice-logo.svg',
      'scripts/website-assets/generate-answerlattice-logo-assets.js',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Logo assets must stay crisp in favicon, PWA, and mobile metadata surfaces.',
    },
  },
  {
    id: 'answerlattice.pwa.icons',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice PWA metadata',
    route: '/',
    placement: 'PWA icon family',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Keep installed Answerlattice app icons tied to the approved mark.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [
      { format: 'png', role: 'primary', ratio: 'icon', maxKb: 140 },
      { format: 'png', role: 'fallback', ratio: 'icon', maxKb: 140 },
    ],
    destination: 'public/answerlattice-icon-512.png',
    component: 'src/app/sites/answerlattice/layout.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'public/answerlattice.webmanifest',
      'public/answerlattice-logo.svg',
      'scripts/website-assets/generate-answerlattice-logo-assets.js',
    ],
    mobile: {
      required: true,
      maxKb: 140,
      notes: 'Icons must remain install-safe on iOS and Android.',
    },
  },
  {
    id: 'answerlattice.pwa.splash',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice PWA startup images',
    route: '/',
    placement: 'iOS startup image family',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Keep Answerlattice startup images aligned with the dark infrastructure identity.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [{ format: 'png', role: 'primary', ratio: 'splash', maxKb: 400 }],
    destination: 'public/answerlattice-splash/apple-splash-1290x2796.png',
    component: 'src/lib/answerlattice/pwaAssets.ts',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'src/lib/answerlattice/pwaAssets.ts',
      'public/answerlattice-logo.svg',
      'public/answerlattice-logo-mark-wide.png',
      'scripts/website-assets/generate-answerlattice-logo-assets.js',
      'scripts/website-assets/generate-answerlattice-splash.js',
    ],
    mobile: {
      required: true,
      maxKb: 400,
      notes: 'Splash family must keep the mark visibly separated from the dark background.',
    },
  },
  {
    id: 'answerlattice.home.hero.support-control-motion',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice homepage',
    route: '/',
    placement: 'homepage hero motion layer',
    type: 'abstract-motion-video',
    required: false,
    blocking: false,
    intent: 'Show product pages, approved answers, hosted help, and widget context flowing through the answer layer.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1400 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1800 },
      { format: 'png', role: 'poster', ratio: '16:9', maxKb: 260 },
    ],
    destination: 'public/answerlattice-support-control-motion.webm',
    component: 'src/app/sites/answerlattice/page.tsx',
    approval: 'founder-required',
    autonomyLevel: 3,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'scripts/website-assets/generate-assetos-motion-compositions.mjs',
      'scripts/website-assets/transcode-assetos-motion-assets.mjs',
      '__docs__/videos/hyperframes/answerlattice-support-control-motion/index.html',
      '__docs__/videos/hyperframes/answerlattice-support-control-motion/shot-plan.json',
      'public/answerlattice-logo.svg',
      'src/app/sites/answerlattice/page.tsx',
      'src/app/sites/answerlattice/answerlatticeWebsiteAssets.ts',
      'src/app/sites/answerlattice/components/AnswerlatticeMotionAsset.tsx',
      'src/app/sites/answerlattice/components/HeroSection.tsx',
      'src/app/sites/answerlattice/components/AnswerlatticeFlowDiagram.tsx',
      'src/app/sites/answerlattice/styles.css',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Motion must degrade to a poster on mobile and reduced-motion users.',
    },
  },
  {
    id: 'answerlattice.home.section.authority-transfer',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice homepage',
    route: '/',
    placement: 'support-loop authority-transfer motion',
    type: 'abstract-motion-video',
    required: false,
    blocking: false,
    intent: 'Show questions becoming reviewed support knowledge without implying autonomous support replacement.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1200 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1600 },
      { format: 'png', role: 'poster', ratio: '16:9', maxKb: 240 },
    ],
    destination: 'public/answerlattice-authority-transfer.webm',
    component: 'src/app/sites/answerlattice/page.tsx',
    approval: 'founder-required',
    autonomyLevel: 3,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'scripts/website-assets/generate-assetos-motion-compositions.mjs',
      'scripts/website-assets/transcode-assetos-motion-assets.mjs',
      '__docs__/videos/hyperframes/answerlattice-authority-transfer/index.html',
      '__docs__/videos/hyperframes/answerlattice-authority-transfer/shot-plan.json',
      'public/answerlattice-logo.svg',
      'src/app/sites/answerlattice/page.tsx',
      'src/app/sites/answerlattice/answerlatticeWebsiteAssets.ts',
      'src/app/sites/answerlattice/components/AnswerlatticeMotionAsset.tsx',
      'src/app/sites/answerlattice/components/ClosedLoopSection.tsx',
      'src/app/sites/answerlattice/components/AnswerlatticeProofBlocks.tsx',
      'src/app/sites/answerlattice/styles.css',
    ],
    mobile: {
      required: true,
      maxKb: 240,
      notes: 'Motion must preserve answer-governance clarity on mobile.',
    },
  },
  {
    id: 'answerlattice.product.page-aware-widget.clip',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice product pages',
    route: '/product/page-aware-widget',
    placement: 'page-aware widget proof clip',
    type: 'product-demo-clip',
    required: false,
    blocking: false,
    intent: 'Show page-aware support context with safe route boundaries and approved answers.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1400 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1800 },
      { format: 'png', role: 'poster', ratio: '16:9', maxKb: 260 },
    ],
    destination: 'public/answerlattice-page-aware-widget-clip.webm',
    component: 'src/app/sites/answerlattice/product/page-aware-widget/page.tsx',
    approval: 'founder-review',
    autonomyLevel: 3,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'scripts/website-assets/generate-assetos-motion-compositions.mjs',
      'scripts/website-assets/transcode-assetos-motion-assets.mjs',
      '__docs__/videos/hyperframes/answerlattice-page-aware-widget-clip/index.html',
      '__docs__/videos/hyperframes/answerlattice-page-aware-widget-clip/shot-plan.json',
      'public/answerlattice-logo.svg',
      'src/app/sites/answerlattice/answerlatticeWebsiteAssets.ts',
      'src/app/sites/answerlattice/components/AnswerlatticeMotionAsset.tsx',
      'src/app/sites/answerlattice/components/ProductCapabilityLandingPage.tsx',
      'src/app/sites/answerlattice/product/page-aware-widget/page.tsx',
      'src/app/sites/answerlattice/components/HomePageAwareDemoSection.tsx',
      'src/app/sites/answerlattice/styles.css',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Widget proof must show safe context, not private customer data.',
    },
  },
  {
    id: 'answerlattice.home.owner-decision-system',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice homepage',
    route: '/',
    placement: 'owner decision system proof',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show how a solo founder moves from a bounded daily brief to the exact governed review surface.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: [
      ...answerlatticeRejectionRules,
      'No invented time-saved, deflection, ticket, demand, or customer-count metrics.',
      'No unbounded task queue or claim that Answerlattice makes owner decisions automatically.',
    ],
    outputs: [{ format: 'webp', role: 'primary', ratio: '6:5', maxKb: 220 }],
    destination: 'public/answerlattice-owner-decision-system.webp',
    component: 'src/app/sites/answerlattice/page.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      '__docs__/answerlattice/answerlattice-website/answerlattice-website_assets-preparation.md',
      '__docs__/answerlattice/founder-daily-brief/founder-daily-brief_website.md',
      'scripts/website-assets/generate-answerlattice-website-dummy-assets.js',
      'src/app/sites/answerlattice/page.tsx',
      'src/app/sites/answerlattice/answerlatticeWebsiteAssets.ts',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'The bounded brief-to-decision composition must remain recognizable; surrounding page copy carries the detailed decision labels on narrow screens.',
    },
  },
  {
    id: 'answerlattice.product.knowledge-map',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Knowledge governance product page',
    route: '/product/knowledge-governance',
    placement: 'curated Knowledge Map proof',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show a curated product hierarchy with answer coverage, drift, and review state instead of exposing the raw ontology graph.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: [
      ...answerlatticeRejectionRules,
      'No raw entity graph, unrestricted cross-links, private tickets, or internal candidate entities.',
      'No invented demand score, trend, support-volume count, or customer metric.',
    ],
    outputs: [{ format: 'webp', role: 'primary', ratio: '6:5', maxKb: 220 }],
    destination: 'public/answerlattice-knowledge-map.webp',
    component: 'src/app/sites/answerlattice/product/knowledge-governance/page.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      '__docs__/answerlattice/knowledge-map/README.md',
      '__docs__/answerlattice/knowledge-map/knowledge-map_website.md',
      'scripts/website-assets/generate-answerlattice-website-dummy-assets.js',
      'src/app/sites/answerlattice/product/knowledge-governance/page.tsx',
      'src/components/templates/answerlattice/governance/KnowledgeMapDashboard.tsx',
      'src/app/sites/answerlattice/answerlatticeWebsiteAssets.ts',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'The curated hierarchy and selected-node pattern must remain recognizable without horizontal canvas interaction; surrounding copy carries exact states.',
    },
  },
  {
    id: 'answerlattice.product.release-assurance',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Knowledge governance product page',
    route: '/product/knowledge-governance',
    placement: 'release impact and Answer Tests proof',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show release-linked answer impact and deterministic Answer Test outcomes before owner-controlled activation.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: [
      ...answerlatticeRejectionRules,
      'No claim that a generated fallback certifies critical product truth.',
      'No automatic answer publication, release activation, or rollback.',
    ],
    outputs: [{ format: 'webp', role: 'primary', ratio: '6:5', maxKb: 220 }],
    destination: 'public/answerlattice-release-assurance.webp',
    component: 'src/app/sites/answerlattice/product/knowledge-governance/page.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      '__docs__/answerlattice/answerlattice-website/answerlattice-website_assets-preparation.md',
      '__docs__/answerlattice/founder-support-controls/founder-support-controls_validation.md',
      '__docs__/answerlattice/changelog-system/changelog-system_validation.md',
      'scripts/website-assets/generate-answerlattice-website-dummy-assets.js',
      'src/app/sites/answerlattice/product/knowledge-governance/page.tsx',
      'src/components/templates/answerlattice/answerTests/AnswerlatticeAnswerTests.tsx',
      'src/lib/answerlattice/releaseServer.ts',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'Release change, affected answers, and test outcomes must remain recognizable as one bounded assurance story; surrounding copy carries detail.',
    },
  },
  {
    id: 'answerlattice.product.article-topic-map',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Knowledge Base product feature page',
    route: '/product/knowledge-base',
    placement: 'public article topic-map proof',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show an accessible article-heading topic map that helps end users understand one published guide at a glance.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: [
      ...answerlatticeRejectionRules,
      'No private ontology, draft content, internal relationships, or ticket evidence.',
      'No claim that the topic map replaces governed product navigation or exposes the full knowledge graph.',
    ],
    outputs: [{ format: 'webp', role: 'primary', ratio: '6:5', maxKb: 200 }],
    destination: 'public/answerlattice-article-topic-map.webp',
    component: 'src/app/sites/answerlattice/components/ProductFeatureLandingPage.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      '__docs__/answerlattice/answerlattice-website/answerlattice-website_assets-preparation.md',
      '__docs__/answerlattice/knowledge-map/knowledge-map_website.md',
      'scripts/website-assets/generate-answerlattice-website-dummy-assets.js',
      'src/app/sites/answerlattice/components/ProductFeatureLandingPage.tsx',
      'src/components/templates/answerlattice/hostedHelp/ArticleTopicMap.tsx',
      'src/lib/answerlattice/publicRichText.ts',
    ],
    mobile: {
      required: true,
      maxKb: 200,
      notes: 'The visual must communicate the mobile drill-down mental model without requiring zoom or pan; surrounding copy carries the published-topic detail.',
    },
  },
];
