import type { AssetSlot } from '../schemas/asset-schema';

const answerlatticeAssetRules = [
  'Use dark infrastructure visual language with restrained teal or verdigris controls.',
  'Show support knowledge governance, canonical answers, hosted help, and page-aware context.',
  'Use product-surface diagrams, status boards, and controlled proof scenes instead of generic SaaS dashboards.',
  'Keep Answerlattice separate from MenuList restaurant visuals and MenuList tenant data.',
];

const answerlatticeRejectionRules = [
  'No restaurant, menu, ordering, POS, or local business visuals.',
  'No claims that Answerlattice is a helpdesk, CMS, autonomous chatbot, or generic AI support tool.',
  'No live customer support data, private tickets, or tenant identifiers.',
  'No bright generic startup gradient art or unrelated dashboard mockups.',
  'No public capability claim that is not present in Answerlattice route/docs/runtime.',
];

export const answerlatticeAssetSlots: AssetSlot[] = [
  {
    id: 'answerlattice.home.og.main',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice website metadata',
    route: '/',
    placement: 'Open Graph and social preview',
    type: 'og-image',
    required: true,
    blocking: true,
    intent: 'Present Answerlattice as governed answer infrastructure.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [{ format: 'png', role: 'og', ratio: '1200x630', maxKb: 500 }],
    destination: 'public/answerlattice-og-image.png',
    component: 'src/app/sites/answerlattice/layout.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'src/app/sites/answerlattice/layout.tsx',
      'src/app/sites/answerlattice/components/HeroSection.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 500,
      notes: 'Must read cleanly in mobile message previews.',
    },
  },
  {
    id: 'answerlattice.brand.logo.mark',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice brand system',
    route: '/',
    placement: 'static logo mark family',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Keep the Answerlattice mark consistent across metadata and static previews.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [
      { format: 'png', role: 'primary', ratio: 'icon', maxKb: 260 },
      { format: 'svg', role: 'fallback', ratio: 'icon', maxKb: 50 },
    ],
    destination: 'public/answerlattice-logo-mark.png',
    component: 'src/app/sites/answerlattice/components/AnswerlatticeLogoMark.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'src/app/sites/answerlattice/components/AnswerlatticeLogoMark.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Logo assets must stay crisp in favicon, PWA, and mobile metadata surfaces.',
    },
  },
  {
    id: 'answerlattice.pwa.icons',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice PWA metadata',
    route: '/',
    placement: 'PWA icon family',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Keep installed Answerlattice app icons tied to the approved mark.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [
      { format: 'png', role: 'primary', ratio: 'icon', maxKb: 140 },
      { format: 'png', role: 'fallback', ratio: 'icon', maxKb: 140 },
    ],
    destination: 'public/answerlattice-icon-512.png',
    component: 'src/app/sites/answerlattice/layout.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'public/answerlattice.webmanifest',
      'scripts/website-assets/generate-answerlattice-splash.js',
    ],
    mobile: {
      required: true,
      maxKb: 140,
      notes: 'Icons must remain install-safe on iOS and Android.',
    },
  },
  {
    id: 'answerlattice.pwa.splash',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice PWA startup images',
    route: '/',
    placement: 'iOS startup image family',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Keep Answerlattice startup images aligned with the dark infrastructure identity.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [{ format: 'png', role: 'primary', ratio: 'splash', maxKb: 400 }],
    destination: 'public/answerlattice-splash/apple-splash-1290x2796.png',
    component: 'src/lib/answerlattice/pwaAssets.ts',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'src/lib/answerlattice/pwaAssets.ts',
      'scripts/website-assets/generate-answerlattice-splash.js',
    ],
    mobile: {
      required: true,
      maxKb: 400,
      notes: 'Splash family must keep the mark visibly separated from the dark background.',
    },
  },
  {
    id: 'answerlattice.home.hero.support-control-motion',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice homepage',
    route: '/',
    placement: 'future hero motion layer',
    type: 'abstract-motion-video',
    required: false,
    blocking: false,
    intent: 'Show product pages, approved answers, hosted help, and widget context flowing through the answer layer.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1400 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1800 },
      { format: 'png', role: 'poster', ratio: '16:9', maxKb: 260 },
    ],
    destination: 'public/answerlattice-support-control-motion.webm',
    component: 'src/app/sites/answerlattice/components/HeroSection.tsx',
    approval: 'founder-required',
    autonomyLevel: 3,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'src/app/sites/answerlattice/components/HeroSection.tsx',
      'src/app/sites/answerlattice/components/AnswerlatticeFlowDiagram.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Motion must degrade to a poster on mobile and reduced-motion users.',
    },
  },
  {
    id: 'answerlattice.home.section.authority-transfer',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice homepage',
    route: '/',
    placement: 'future authority-transfer section motion',
    type: 'abstract-motion-video',
    required: false,
    blocking: false,
    intent: 'Show questions becoming reviewed support knowledge without implying autonomous support replacement.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1200 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1600 },
      { format: 'png', role: 'poster', ratio: '16:9', maxKb: 240 },
    ],
    destination: 'public/answerlattice-authority-transfer.webm',
    component: 'src/app/sites/answerlattice/components/ClosedLoopSection.tsx',
    approval: 'founder-required',
    autonomyLevel: 3,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'src/app/sites/answerlattice/components/ClosedLoopSection.tsx',
      'src/app/sites/answerlattice/components/AnswerlatticeProofBlocks.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 240,
      notes: 'Motion must preserve answer-governance clarity on mobile.',
    },
  },
  {
    id: 'answerlattice.product.page-aware-widget.clip',
    brand: 'answerlattice',
    productBoundary: 'internal-product-architecture',
    page: 'Answerlattice product pages',
    route: '/product/page-aware-widget',
    placement: 'future page-aware widget proof clip',
    type: 'product-demo-clip',
    required: false,
    blocking: false,
    intent: 'Show page-aware support context with safe route boundaries and approved answers.',
    narrativeRules: answerlatticeAssetRules,
    rejectionRules: answerlatticeRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1400 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1800 },
      { format: 'png', role: 'poster', ratio: '16:9', maxKb: 260 },
    ],
    destination: 'public/answerlattice-page-aware-widget-clip.webm',
    component: 'src/app/sites/answerlattice/product/page-aware-widget/page.tsx',
    approval: 'founder-review',
    autonomyLevel: 3,
    sources: [
      '__docs__/answerlattice/answerlattice-website/README.md',
      'src/app/sites/answerlattice/product/page-aware-widget/page.tsx',
      'src/app/sites/answerlattice/components/HomePageAwareDemoSection.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Widget proof must show safe context, not private customer data.',
    },
  },
];
