import type { AssetSlot } from '../schemas/asset-schema';

const canonicaAssetRules = [
  'Use dark infrastructure visual language with restrained teal or verdigris controls.',
  'Show support knowledge governance, canonical answers, hosted help, and page-aware context.',
  'Use product-surface diagrams, status boards, and controlled proof scenes instead of generic SaaS dashboards.',
  'Keep Canonica separate from MenuList restaurant visuals and MenuList tenant data.',
];

const canonicaRejectionRules = [
  'No restaurant, menu, ordering, POS, or local business visuals.',
  'No claims that Canonica is a helpdesk, CMS, autonomous chatbot, or generic AI support tool.',
  'No live customer support data, private tickets, or tenant identifiers.',
  'No bright generic startup gradient art or unrelated dashboard mockups.',
  'No public capability claim that is not present in Canonica route/docs/runtime.',
];

export const canonicaAssetSlots: AssetSlot[] = [
  {
    id: 'canonica.home.og.main',
    brand: 'canonica',
    productBoundary: 'internal-product-architecture',
    page: 'Canonica website metadata',
    route: '/',
    placement: 'Open Graph and social preview',
    type: 'og-image',
    required: true,
    blocking: true,
    intent: 'Present Canonica as a governed support knowledge control plane.',
    narrativeRules: canonicaAssetRules,
    rejectionRules: canonicaRejectionRules,
    outputs: [{ format: 'png', role: 'og', ratio: '1200x630', maxKb: 500 }],
    destination: 'public/canonica-og-image.png',
    component: 'src/app/sites/canonica/layout.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/canonica/canonica-website/README.md',
      'src/app/sites/canonica/layout.tsx',
      'src/app/sites/canonica/components/HeroSection.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 500,
      notes: 'Must read cleanly in mobile message previews.',
    },
  },
  {
    id: 'canonica.brand.logo.mark',
    brand: 'canonica',
    productBoundary: 'internal-product-architecture',
    page: 'Canonica brand system',
    route: '/',
    placement: 'static logo mark family',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Keep the Canonica mark consistent across metadata and static previews.',
    narrativeRules: canonicaAssetRules,
    rejectionRules: canonicaRejectionRules,
    outputs: [
      { format: 'png', role: 'primary', ratio: 'icon', maxKb: 260 },
      { format: 'svg', role: 'fallback', ratio: 'icon', maxKb: 50 },
    ],
    destination: 'public/canonica-logo-mark.png',
    component: 'src/app/sites/canonica/components/CanonicaLogoMark.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/canonica/canonica-website/README.md',
      'src/app/sites/canonica/components/CanonicaLogoMark.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Logo assets must stay crisp in favicon, PWA, and mobile metadata surfaces.',
    },
  },
  {
    id: 'canonica.pwa.icons',
    brand: 'canonica',
    productBoundary: 'internal-product-architecture',
    page: 'Canonica PWA metadata',
    route: '/',
    placement: 'PWA icon family',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Keep installed Canonica app icons tied to the approved mark.',
    narrativeRules: canonicaAssetRules,
    rejectionRules: canonicaRejectionRules,
    outputs: [
      { format: 'png', role: 'primary', ratio: 'icon', maxKb: 140 },
      { format: 'png', role: 'fallback', ratio: 'icon', maxKb: 140 },
    ],
    destination: 'public/canonica-icon-512.png',
    component: 'src/app/sites/canonica/layout.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/canonica/canonica-website/README.md',
      'public/canonica.webmanifest',
      'scripts/website-assets/generate-canonica-splash.js',
    ],
    mobile: {
      required: true,
      maxKb: 140,
      notes: 'Icons must remain install-safe on iOS and Android.',
    },
  },
  {
    id: 'canonica.pwa.splash',
    brand: 'canonica',
    productBoundary: 'internal-product-architecture',
    page: 'Canonica PWA startup images',
    route: '/',
    placement: 'iOS startup image family',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Keep Canonica startup images aligned with the dark infrastructure identity.',
    narrativeRules: canonicaAssetRules,
    rejectionRules: canonicaRejectionRules,
    outputs: [{ format: 'png', role: 'primary', ratio: 'splash', maxKb: 400 }],
    destination: 'public/canonica-splash/apple-splash-1290x2796.png',
    component: 'src/lib/canonica/pwaAssets.ts',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/canonica/canonica-website/README.md',
      'src/lib/canonica/pwaAssets.ts',
      'scripts/website-assets/generate-canonica-splash.js',
    ],
    mobile: {
      required: true,
      maxKb: 400,
      notes: 'Splash family must keep the mark visibly separated from the dark background.',
    },
  },
  {
    id: 'canonica.home.hero.support-control-motion',
    brand: 'canonica',
    productBoundary: 'internal-product-architecture',
    page: 'Canonica homepage',
    route: '/',
    placement: 'future hero motion layer',
    type: 'abstract-motion-video',
    required: false,
    blocking: false,
    intent: 'Show product pages, approved answers, hosted help, and widget context flowing through the control plane.',
    narrativeRules: canonicaAssetRules,
    rejectionRules: canonicaRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1400 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1800 },
      { format: 'png', role: 'poster', ratio: '16:9', maxKb: 260 },
    ],
    destination: 'public/canonica-support-control-motion.webm',
    component: 'src/app/sites/canonica/components/HeroSection.tsx',
    approval: 'founder-required',
    autonomyLevel: 3,
    sources: [
      '__docs__/canonica/canonica-website/README.md',
      'src/app/sites/canonica/components/HeroSection.tsx',
      'src/app/sites/canonica/components/CanonicaFlowDiagram.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Motion must degrade to a poster on mobile and reduced-motion users.',
    },
  },
  {
    id: 'canonica.home.section.authority-transfer',
    brand: 'canonica',
    productBoundary: 'internal-product-architecture',
    page: 'Canonica homepage',
    route: '/',
    placement: 'future authority-transfer section motion',
    type: 'abstract-motion-video',
    required: false,
    blocking: false,
    intent: 'Show questions becoming reviewed support knowledge without implying autonomous support replacement.',
    narrativeRules: canonicaAssetRules,
    rejectionRules: canonicaRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1200 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1600 },
      { format: 'png', role: 'poster', ratio: '16:9', maxKb: 240 },
    ],
    destination: 'public/canonica-authority-transfer.webm',
    component: 'src/app/sites/canonica/components/ClosedLoopSection.tsx',
    approval: 'founder-required',
    autonomyLevel: 3,
    sources: [
      '__docs__/canonica/canonica-website/README.md',
      'src/app/sites/canonica/components/ClosedLoopSection.tsx',
      'src/app/sites/canonica/components/CanonicaProofBlocks.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 240,
      notes: 'Motion must preserve answer-governance clarity on mobile.',
    },
  },
  {
    id: 'canonica.product.page-aware-widget.clip',
    brand: 'canonica',
    productBoundary: 'internal-product-architecture',
    page: 'Canonica product pages',
    route: '/product/page-aware-widget',
    placement: 'future page-aware widget proof clip',
    type: 'product-demo-clip',
    required: false,
    blocking: false,
    intent: 'Show page-aware support context with safe route boundaries and approved answers.',
    narrativeRules: canonicaAssetRules,
    rejectionRules: canonicaRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1400 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1800 },
      { format: 'png', role: 'poster', ratio: '16:9', maxKb: 260 },
    ],
    destination: 'public/canonica-page-aware-widget-clip.webm',
    component: 'src/app/sites/canonica/product/page-aware-widget/page.tsx',
    approval: 'founder-review',
    autonomyLevel: 3,
    sources: [
      '__docs__/canonica/canonica-website/README.md',
      'src/app/sites/canonica/product/page-aware-widget/page.tsx',
      'src/app/sites/canonica/components/HomePageAwareDemoSection.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Widget proof must show safe context, not private customer data.',
    },
  },
];
