import type { AssetSlot } from '../schemas/asset-schema';

const menuListAssetRules = [
  'Use concrete MenuList product surfaces, not generic restaurant stock visuals.',
  'Reinforce one owner-approved public source for menu and business truth.',
  'Use fictional or founder-approved demo data only.',
  'Keep customer-facing proof calm, direct, and implementation-backed.',
];

const menuListRejectionRules = [
  'No fake customer testimonials, logos, metrics, or reviews.',
  'No automatic Google, Instagram, WhatsApp, POS, payroll, CRM, or delivery-platform sync claims unless the source page implements that exact capability.',
  'No visible private tenant IDs, owner emails, phone numbers, or real customer data.',
  'No AI-themed visual language, prompt bubbles, robots, or generic glowing dashboards.',
  'No campaign/canvas/post-workbench UI inside MenuList.',
];

const menuListLaunchFrameSources = [
  '__docs__/main-website/main-website_image-assets.md',
  '__docs__/main-website/asset-production/launch-pack-2026-07/menulist-launch-pack.md',
  'scripts/website-assets/extract-menulist-launch-frames.mjs',
  'public/images/website/menulist-business-truth-loop.mp4',
  '__docs__/videos/hyperframes/menulist-business-truth-loop/shot-plan.json',
];

const menuListLaunchFrameSlots: AssetSlot[] = [
  {
    id: 'menulist.launch.video.frame.approved-source',
    filename: '01-approved-source.png',
    placement: 'launch-film opening frame',
    intent: 'Open the launch sequence on MenuList as the owner-approved public source.',
  },
  {
    id: 'menulist.launch.video.frame.public-surfaces',
    filename: '02-public-surfaces.png',
    placement: 'launch-film public-surfaces frame',
    intent: 'Show the approved source reaching the public menu, Official Business Page, QR, and screen surfaces.',
  },
  {
    id: 'menulist.launch.video.frame.stable-loop',
    filename: '03-stable-loop.png',
    placement: 'launch-film stable-loop frame',
    intent: 'Show the public truth loop stabilizing without adding owner monitoring or unsupported sync claims.',
  },
  {
    id: 'menulist.launch.video.frame.final-proof',
    filename: '04-final-proof.png',
    placement: 'launch-film closing proof frame',
    intent: 'Close on the calm final state where the approved public source remains in control.',
  },
].map((frame) => ({
  id: frame.id,
  brand: 'menulist',
  productBoundary: 'internal-product-architecture',
  page: 'MenuList coordinated launch pack',
  route: '/',
  placement: frame.placement,
  type: 'static-image',
  required: false,
  blocking: false,
  intent: frame.intent,
  narrativeRules: menuListAssetRules,
  rejectionRules: menuListRejectionRules,
  outputs: [{ format: 'png', role: 'primary', ratio: '16:9', maxKb: 500 }],
  destination: `packages/asset-factory/published/menulist/launch-video-frames/${frame.filename}`,
  approval: 'automatic',
  autonomyLevel: 2,
  sources: menuListLaunchFrameSources,
  mobile: {
    required: true,
    maxKb: 500,
    notes: 'Keep the central source-to-surface story readable when the frame is adapted for vertical launch edits.',
  },
}));

type MenuListPublicMediaSlotConfig = {
  id: string;
  page: string;
  route: string;
  placement: string;
  intent: string;
  destination: string;
  component?: string;
  format: 'webp' | 'jpg' | 'svg';
  ratio: '16:9' | '4:3' | '1:1' | '9:16';
  maxKb: number;
  sources: string[];
  mobileNotes: string;
  required?: boolean;
  blocking?: boolean;
  extraRejectionRules?: string[];
};

const menuListPublicMediaSlotConfigs: MenuListPublicMediaSlotConfig[] = [
  {
    id: 'menulist.industry.service-businesses.hero-source',
    page: 'MenuList service-business industry pages',
    route: '/industries/salons-spas',
    placement: 'service-business industry hero proof',
    intent:
      'Show an owner-approved service list becoming a believable public customer page without reusing restaurant menu proof.',
    destination: 'public/images/website/menulist-hero-service-source.webp',
    component: 'src/components/website/industries/IndustryLandingPage.tsx',
    format: 'webp',
    ratio: '16:9',
    maxKb: 350,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/content/websiteIndustries.ts',
      'src/components/website/industries/IndustryLandingPage.tsx',
      'src/styles/website.css',
    ],
    mobileNotes:
      'Keep the service-list hierarchy, owner-approved source, and customer-facing page recognizable behind mobile hero copy.',
    extraRejectionRules: [
      'Do not show restaurant dishes, menu-only language, unsupported appointments, or invented service-business activity metrics.',
    ],
  },
  {
    id: 'menulist.industry.salons-spas.demo-placeholder',
    page: 'Salons and spas industry page',
    route: '/industries/salons-spas',
    placement: 'bounded service-list demo proof',
    intent: 'Show the shape of a fictional salon service-list page while routed demo screenshots remain pending.',
    destination: 'public/images/website/demo-placeholders/glow-blade-service-list-placeholder.svg',
    component: 'src/content/websiteIndustries.ts',
    format: 'svg',
    ratio: '16:9',
    maxKb: 10,
    sources: [
      '__docs__/menulist-marketing-distribution/menulist-marketing-distribution_demo-placeholder-assets.md',
      'src/content/websiteIndustries.ts',
    ],
    mobileNotes: 'Keep the demo label and fictional-data boundary readable on narrow industry pages.',
    extraRejectionRules: [
      'Temporary placeholder only; do not reuse as customer proof, Product Hunt proof, paid media, or final campaign creative.',
    ],
  },
  {
    id: 'menulist.marketing.launch-video.poster-placeholder',
    page: 'MenuList marketing distribution planning',
    route: '/',
    placement: 'unmounted walkthrough-video poster placeholder',
    intent: 'Retain a governed vertical planning placeholder until an approved walkthrough poster or thumbnail replaces it.',
    destination: 'public/images/website/demo-placeholders/launch-video-poster-placeholder.svg',
    format: 'svg',
    ratio: '9:16',
    maxKb: 10,
    sources: [
      '__docs__/menulist-marketing-distribution/menulist-marketing-distribution_demo-placeholder-assets.md',
    ],
    mobileNotes: 'Keep the planning-only label readable in a vertical preview.',
    required: false,
    blocking: false,
    extraRejectionRules: [
      'Planning placeholder only; do not mount, publish, distribute, or present it as an approved launch-video poster.',
    ],
  },
  {
    id: 'menulist.industry.service-list-businesses.proof-placeholder',
    page: 'Service-list businesses industry page',
    route: '/industries/service-list-businesses',
    placement: 'bounded multi-category demo proof',
    intent: 'Show the shape of fictional service-list categories while routed demo screenshots remain pending.',
    destination: 'public/images/website/demo-placeholders/service-list-proof-grid-placeholder.svg',
    component: 'src/content/websiteIndustries.ts',
    format: 'svg',
    ratio: '16:9',
    maxKb: 10,
    sources: [
      '__docs__/menulist-marketing-distribution/menulist-marketing-distribution_demo-placeholder-assets.md',
      'src/content/websiteIndustries.ts',
    ],
    mobileNotes: 'Preserve the sample-business boundary and category hierarchy on mobile.',
    extraRejectionRules: [
      'Temporary placeholder only; do not reuse as customer proof, Product Hunt proof, paid media, or final campaign creative.',
    ],
  },
  {
    id: 'menulist.industry.local-service-businesses.demo-placeholder',
    page: 'Local service businesses industry page',
    route: '/industries/local-service-businesses',
    placement: 'bounded rate-card demo proof',
    intent: 'Show the shape of a fictional local-service rate card while routed demo screenshots remain pending.',
    destination: 'public/images/website/demo-placeholders/spark-detailing-rate-card-placeholder.svg',
    component: 'src/content/websiteIndustries.ts',
    format: 'svg',
    ratio: '16:9',
    maxKb: 10,
    sources: [
      '__docs__/menulist-marketing-distribution/menulist-marketing-distribution_demo-placeholder-assets.md',
      'src/content/websiteIndustries.ts',
    ],
    mobileNotes: 'Keep the sample-business label and package hierarchy readable on mobile.',
    extraRejectionRules: [
      'Temporary placeholder only; do not reuse as customer proof, Product Hunt proof, paid media, or final campaign creative.',
    ],
  },
  {
    id: 'menulist.feature.customer-feedback-loop.public-form',
    page: 'Customer Feedback Loop feature page',
    route: '/features/customer-feedback-loop',
    placement: 'public feedback form proof',
    intent: 'Show the public feedback report form as a bounded customer workflow.',
    destination: 'public/images/website/features/customer-feedback-loop/public-feedback-form.webp',
    component: 'src/components/website/features/FeatureScreenshotProofGallery.tsx',
    format: 'webp',
    ratio: '1:1',
    maxKb: 40,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/features/FeatureScreenshotProofGallery.tsx',
    ],
    mobileNotes: 'Keep form labels and the public-report context readable on mobile.',
  },
  {
    id: 'menulist.feature.menu-import.source-link',
    page: 'Menu Import feature page',
    route: '/features/menu-import',
    placement: 'owner source-link import proof',
    intent: 'Show the cropped owner source-link input used to prepare a menu import.',
    destination: 'public/images/website/features/menu-import/source-menu-link.webp',
    component: 'src/components/website/features/FeatureScreenshotProofGallery.tsx',
    format: 'webp',
    ratio: '9:16',
    maxKb: 30,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/features/FeatureScreenshotProofGallery.tsx',
    ],
    mobileNotes: 'Preserve input labels and source-link context at the native portrait proportion.',
  },
  {
    id: 'menulist.feature.public-discovery.presence-checklist',
    page: 'Public Discovery feature page',
    route: '/features/public-discovery',
    placement: 'public placement and source checklist proof',
    intent: 'Show the bounded placement/source checklist without implying automatic third-party distribution.',
    destination: 'public/images/website/features/public-discovery/presence-checklist.webp',
    component: 'src/components/website/features/FeatureScreenshotProofGallery.tsx',
    format: 'webp',
    ratio: '16:9',
    maxKb: 40,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/features/FeatureScreenshotProofGallery.tsx',
    ],
    mobileNotes: 'Checklist labels must remain readable without suggesting automatic external sync.',
  },
  {
    id: 'menulist.feature.qr-menu-links.share-kit',
    page: 'QR Menu Links feature page',
    route: '/features/qr-menu-links',
    placement: 'owner share and QR kit proof',
    intent: 'Show the bounded owner share, QR, and presence controls used to distribute the approved link.',
    destination: 'public/images/website/features/qr-menu-links/share-kit.webp',
    component: 'src/components/website/features/FeatureScreenshotProofGallery.tsx',
    format: 'webp',
    ratio: '4:3',
    maxKb: 50,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/features/FeatureScreenshotProofGallery.tsx',
      'src/components/mobile/screens/MobileShareScreen.tsx',
    ],
    mobileNotes: 'Keep QR and share controls readable while preserving the owner-placement boundary.',
  },
  {
    id: 'menulist.feature.print-ready-kit.dashboard',
    page: 'Print-ready Kit feature page',
    route: '/features/print-ready-kit',
    placement: 'print assets dashboard proof',
    intent: 'Show the cropped print-assets template list with account-header details removed.',
    destination: 'public/images/website/print-ready-kit/print-assets-dashboard.jpg',
    component: 'src/components/website/features/PrintReadyKitProofGallery.tsx',
    format: 'jpg',
    ratio: '4:3',
    maxKb: 220,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/features/PrintReadyKitProofGallery.tsx',
      'src/components/templates/main-app/printableAssetTemplates/PrintableAssetTemplatesRoute.tsx',
    ],
    mobileNotes: 'The template list must remain inspectable without exposing account or tenant details.',
  },
  {
    id: 'menulist.feature.print-ready-kit.editor',
    page: 'Print-ready Kit feature page',
    route: '/features/print-ready-kit',
    placement: 'print asset editor proof',
    intent: 'Show the dedicated print asset editor as deterministic fictional product proof.',
    destination: 'public/images/website/print-ready-kit/print-assets-editor.jpg',
    component: 'src/components/website/features/PrintReadyKitProofGallery.tsx',
    format: 'jpg',
    ratio: '16:9',
    maxKb: 200,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'scripts/website-assets/generate-product-proof-assets.mjs',
      'src/components/website/features/PrintReadyKitProofGallery.tsx',
      'src/components/templates/main-app/printableAssetTemplates/PrintableAssetTemplatesRoute.tsx',
    ],
    mobileNotes: 'The editor canvas and main controls must remain recognizable on a narrow feature page.',
  },
  {
    id: 'menulist.home.owner-proof.ai-menu-manager',
    page: 'MenuList homepage and AI Menu Manager page',
    route: '/ai-menu-manager',
    placement: 'owner approval product proof',
    intent: 'Show a fictional message-to-prepared-card workflow with owner approval kept explicit.',
    destination: 'public/images/website/product-proof/ai-menu-manager-approval-card.webp',
    component: 'src/components/website/home/OwnerProofSection.tsx',
    format: 'webp',
    ratio: '4:3',
    maxKb: 100,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      '__docs__/main-website/asset-production/stage-08-product-proof/stage-08-product-proof-demo-assets.md',
      'scripts/website-assets/generate-product-proof-assets.mjs',
      'src/components/website/home/OwnerProofSection.tsx',
      'src/components/website/ai-menu-manager/AiMenuManagerPage.tsx',
    ],
    mobileNotes: 'Keep owner approval visibly separate from the prepared suggestion on mobile.',
  },
  {
    id: 'menulist.home.owner-proof.business-health',
    page: 'MenuList homepage and Business Health feature page',
    route: '/features/business-health',
    placement: 'stable business-health product proof',
    intent: 'Show a fictional stable check with a clear no-action-needed state and no invented performance metrics.',
    destination: 'public/images/website/product-proof/business-health-stable-check.webp',
    component: 'src/components/website/home/OwnerProofSection.tsx',
    format: 'webp',
    ratio: '4:3',
    maxKb: 110,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      '__docs__/main-website/asset-production/stage-08-product-proof/stage-08-product-proof-demo-assets.md',
      'scripts/website-assets/generate-product-proof-assets.mjs',
      'src/components/website/home/OwnerProofSection.tsx',
      'src/components/website/features/BusinessHealthFeaturePage.tsx',
    ],
    mobileNotes: 'Keep the stable state readable without implying guaranteed correctness or continuous monitoring.',
  },
];

const menuListPublicMediaSlots: AssetSlot[] = menuListPublicMediaSlotConfigs.map((slot) => ({
  id: slot.id,
  brand: 'menulist',
  productBoundary: 'internal-product-architecture',
  page: slot.page,
  route: slot.route,
  placement: slot.placement,
  type: 'static-image',
  required: slot.required ?? true,
  blocking: slot.blocking ?? true,
  intent: slot.intent,
  narrativeRules: menuListAssetRules,
  rejectionRules: [...menuListRejectionRules, ...(slot.extraRejectionRules ?? [])],
  outputs: [{ format: slot.format, role: 'primary', ratio: slot.ratio, maxKb: slot.maxKb }],
  destination: slot.destination,
  component: slot.component,
  approval: 'automatic',
  autonomyLevel: 2,
  sources: slot.sources,
  mobile: {
    required: true,
    maxKb: slot.maxKb,
    notes: slot.mobileNotes,
  },
}));

export const menuListAssetSlots: AssetSlot[] = [
  {
    id: 'menulist.home.hero.official-source',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/',
    placement: 'homepage static background fallback and OG source',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show MenuList as the official public source for menu and business truth.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '16:9', maxKb: 350 }],
    destination: 'public/images/website/menulist-hero-official-source.webp',
    component: 'src/styles/website.css',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'scripts/website-assets/generate-stage6-assets.mjs',
      'src/styles/website.css',
    ],
    mobile: {
      required: true,
      maxKb: 350,
      notes: 'Must remain legible when the hero visual stacks below copy on mobile.',
    },
  },
  {
    id: 'menulist.home.og.official-source',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage metadata',
    route: '/',
    placement: 'Open Graph and social preview',
    type: 'og-image',
    required: true,
    blocking: true,
    intent: 'Provide a share preview derived from the official-source homepage visual.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [
      { format: 'png', role: 'og', ratio: '1200x630', maxKb: 500 },
      { format: 'png', role: 'fallback', ratio: '1200x630', maxKb: 500 },
    ],
    destination: 'public/images/website/menulist-og-official-source.png',
    component: 'src/app/(website)/layout.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      '__docs__/main-website/asset-production/launch-pack-2026-07/menulist-launch-pack.md',
      'scripts/website-assets/generate-stage6-assets.mjs',
      'public/images/website/menulist-hero-official-source.webp',
    ],
    mobile: {
      required: true,
      maxKb: 500,
      notes: 'Must remain readable in messaging previews and social cards.',
    },
  },
  {
    id: 'menulist.home.customer-browse.mobile-menu',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage and QR Menu Links feature page',
    route: '/features/qr-menu-links',
    placement: 'customer browsing section and QR Menu Links public-menu proof',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show the public menu experience customers see on a phone.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '9:16', maxKb: 220 }],
    destination: 'public/images/website/menulist-public-menu-mobile.webp',
    component: 'src/components/website/home/CustomerBrowseSection.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/home/CustomerBrowseSection.tsx',
      'src/components/website/features/FeatureScreenshotProofGallery.tsx',
      'src/app/client/[[...slug]]/page.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'This is the primary mobile customer proof asset.',
    },
  },
  {
    id: 'menulist.home.public-presence.obp-browser',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/',
    placement: 'Official Business Page browser proof',
    type: 'static-image',
    required: false,
    blocking: false,
    intent: 'Show the Official Business Page as part of MenuList public presence.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '16:9', maxKb: 220 }],
    destination: 'public/images/website/menulist-obp-browser.webp',
    component: 'src/components/website/home/BusinessSection.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/home/BusinessSection.tsx',
      'src/app/client/obp/OBPContent.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'OBP browser proof must stay readable when scaled down on mobile.',
    },
  },
  {
    id: 'menulist.home.setup-relief.workflow',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/',
    placement: 'setup relief workflow',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show upload, review, and publish as a low-effort owner workflow.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '16:9', maxKb: 220 }],
    destination: 'public/images/website/menulist-setup-relief-workflow.webp',
    component: 'src/components/website/home/SetupReliefSection.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/home/SetupReliefSection.tsx',
      'src/components/templates/main-app/projects/jobScreens/ExtractionJobReviewScreen.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'Workflow labels must not become unreadable on small screens.',
    },
  },
  {
    id: 'menulist.home.public-surfaces.matrix',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/#public-proof',
    placement: 'public surfaces proof matrix',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show that the same approved truth appears across public surfaces.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '16:9', maxKb: 260 }],
    destination: 'public/images/website/menulist-public-surfaces-matrix.webp',
    component: 'src/components/website/home/SurfacesSection.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/home/SurfacesSection.tsx',
      'src/components/mobile/screens/MobileShareScreen.tsx',
      'src/app/client/obp/OBPContent.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Matrix must preserve proof hierarchy without horizontal overflow.',
    },
  },
  {
    id: 'menulist.home.analytics.status-proof',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/',
    placement: 'analytics and status proof',
    type: 'static-image',
    required: false,
    blocking: false,
    intent: 'Support the idea that public menu state can be monitored without inventing customer metrics.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '16:9', maxKb: 220 }],
    destination: 'public/images/website/menulist-analytics-proof.webp',
    component: 'src/components/website/home/AnalyticsInsightsSection.tsx',
    approval: 'founder-review',
    autonomyLevel: 3,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/home/AnalyticsInsightsSection.tsx',
      'src/components/templates/main-app/dashboard/OwnerDashboard/index.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'Synthetic status signals must not be confused with real customer analytics.',
    },
  },
  {
    id: 'menulist.launch.social.square',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList launch assets',
    route: '/',
    placement: 'square launch/social image',
    type: 'static-image',
    required: false,
    blocking: false,
    intent: 'Provide a square launch image derived from approved homepage proof.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'png', role: 'social', ratio: '1:1', maxKb: 500 }],
    destination: 'public/images/website/menulist-launch-square.png',
    approval: 'founder-review',
    autonomyLevel: 3,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      '__docs__/main-website/asset-production/launch-pack-2026-07/menulist-launch-pack.md',
      'scripts/website-assets/generate-stage6-assets.mjs',
    ],
    mobile: {
      required: true,
      maxKb: 500,
      notes: 'Must read clearly in mobile social previews.',
    },
  },
  {
    id: 'menulist.launch.device.owner-pwa-dashboard',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList launch assets and Owner PWA Dashboard feature page',
    route: '/features/owner-phone-dashboard',
    placement: 'owner-device launch mockup and feature-page proof',
    type: 'static-image',
    required: false,
    blocking: false,
    intent: 'Show the real MenuList owner-mobile information hierarchy inside a restrained phone composition.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '9:16', maxKb: 220 }],
    destination: 'public/images/website/product-proof/owner-phone-dashboard.webp',
    component: 'src/components/website/features/FeatureScreenshotProofGallery.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      '__docs__/main-website/asset-production/stage-08-product-proof/stage-08-product-proof-demo-assets.md',
      '__docs__/main-website/asset-production/launch-pack-2026-07/menulist-launch-pack.md',
      'scripts/website-assets/generate-product-proof-assets.mjs',
      'src/components/website/features/FeatureScreenshotProofGallery.tsx',
      'src/components/mobile/MobileShell.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'The phone screen must remain readable and clearly labeled as fictional demo data.',
    },
  },
  {
    id: 'menulist.launch.social.linkedin',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList launch assets',
    route: '/',
    placement: 'LinkedIn launch image',
    type: 'static-image',
    required: false,
    blocking: false,
    intent: 'Provide a professional launch preview for founder distribution.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'png', role: 'social', ratio: '1200x630', maxKb: 500 }],
    destination: 'public/images/website/menulist-linkedin-launch.png',
    approval: 'founder-review',
    autonomyLevel: 3,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      '__docs__/main-website/asset-production/launch-pack-2026-07/menulist-launch-pack.md',
      'scripts/website-assets/generate-stage6-assets.mjs',
    ],
    mobile: {
      required: true,
      maxKb: 500,
      notes: 'Must avoid tiny product text that becomes unreadable in feed cards.',
    },
  },
  {
    id: 'menulist.home.hero.business-truth-loop',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/',
    placement: 'homepage hero motion layer',
    type: 'loop-video',
    required: false,
    blocking: false,
    intent: 'Show the menu truth loop across owner approval, public menu, OBP, QR, and screen surfaces.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1200 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1800 },
      { format: 'webp', role: 'poster', ratio: '16:9', maxKb: 220 },
    ],
    destination: 'public/images/website/menulist-business-truth-loop.webm',
    component: 'src/components/website/home/HeroSection.tsx',
    approval: 'founder-required',
    autonomyLevel: 3,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'scripts/website-assets/generate-assetos-motion-compositions.mjs',
      'scripts/website-assets/transcode-assetos-motion-assets.mjs',
      '__docs__/videos/hyperframes/menulist-business-truth-loop/index.html',
      '__docs__/videos/hyperframes/menulist-business-truth-loop/shot-plan.json',
      'public/icons/icon-512x512.png',
      'src/components/website/home/HeroSection.tsx',
      'src/components/website/home/SurfacesSection.tsx',
      'src/styles/website.css',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'Motion must have a static poster and reduced-motion fallback.',
    },
  },
  ...menuListPublicMediaSlots,
  ...menuListLaunchFrameSlots,
];
