import type { AssetSlot } from '../schemas/asset-schema';

const menuListAssetRules = [
  'Use concrete MenuList product surfaces, not generic restaurant stock visuals.',
  'Reinforce one owner-approved public source for menu and business truth.',
  'Use fictional or founder-approved demo data only.',
  'Keep customer-facing proof calm, direct, and implementation-backed.',
];

const menuListRejectionRules = [
  'No fake customer testimonials, logos, metrics, or reviews.',
  'No automatic Google, Instagram, WhatsApp, POS, payroll, CRM, or delivery-platform sync claims unless the source page implements that exact capability.',
  'No visible private tenant IDs, owner emails, phone numbers, or real customer data.',
  'No AI-themed visual language, prompt bubbles, robots, or generic glowing dashboards.',
  'No campaign/canvas/post-workbench UI inside MenuList.',
];

const menuListLaunchFrameSources = [
  '__docs__/main-website/main-website_image-assets.md',
  '__docs__/main-website/asset-production/launch-pack-2026-07/menulist-launch-pack.md',
  'scripts/website-assets/extract-menulist-launch-frames.mjs',
  'public/images/website/menulist-business-truth-loop.mp4',
  '__docs__/videos/hyperframes/menulist-business-truth-loop/shot-plan.json',
];

const menuListLaunchFrameSlots: AssetSlot[] = [
  {
    id: 'menulist.launch.video.frame.approved-source',
    filename: '01-approved-source.png',
    placement: 'launch-film opening frame',
    intent: 'Open the launch sequence on MenuList as the owner-approved public source.',
  },
  {
    id: 'menulist.launch.video.frame.public-surfaces',
    filename: '02-public-surfaces.png',
    placement: 'launch-film public-surfaces frame',
    intent: 'Show the approved source reaching the public menu, Official Business Page, QR, and screen surfaces.',
  },
  {
    id: 'menulist.launch.video.frame.stable-loop',
    filename: '03-stable-loop.png',
    placement: 'launch-film stable-loop frame',
    intent: 'Show the public truth loop stabilizing without adding owner monitoring or unsupported sync claims.',
  },
  {
    id: 'menulist.launch.video.frame.final-proof',
    filename: '04-final-proof.png',
    placement: 'launch-film closing proof frame',
    intent: 'Close on the calm final state where the approved public source remains in control.',
  },
].map((frame) => ({
  id: frame.id,
  brand: 'menulist',
  productBoundary: 'internal-product-architecture',
  page: 'MenuList coordinated launch pack',
  route: '/',
  placement: frame.placement,
  type: 'static-image',
  required: false,
  blocking: false,
  intent: frame.intent,
  narrativeRules: menuListAssetRules,
  rejectionRules: menuListRejectionRules,
  outputs: [{ format: 'png', role: 'primary', ratio: '16:9', maxKb: 500 }],
  destination: `packages/asset-factory/published/menulist/launch-video-frames/${frame.filename}`,
  approval: 'automatic',
  autonomyLevel: 2,
  sources: menuListLaunchFrameSources,
  mobile: {
    required: true,
    maxKb: 500,
    notes: 'Keep the central source-to-surface story readable when the frame is adapted for vertical launch edits.',
  },
}));

export const menuListAssetSlots: AssetSlot[] = [
  {
    id: 'menulist.home.hero.official-source',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/',
    placement: 'homepage static background fallback and OG source',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show MenuList as the official public source for menu and business truth.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '16:9', maxKb: 350 }],
    destination: 'public/images/website/menulist-hero-official-source.webp',
    component: 'src/styles/website.css',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'scripts/website-assets/generate-stage6-assets.mjs',
      'src/styles/website.css',
    ],
    mobile: {
      required: true,
      maxKb: 350,
      notes: 'Must remain legible when the hero visual stacks below copy on mobile.',
    },
  },
  {
    id: 'menulist.home.og.official-source',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage metadata',
    route: '/',
    placement: 'Open Graph and social preview',
    type: 'og-image',
    required: true,
    blocking: true,
    intent: 'Provide a share preview derived from the official-source homepage visual.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [
      { format: 'png', role: 'og', ratio: '1200x630', maxKb: 500 },
      { format: 'png', role: 'fallback', ratio: '1200x630', maxKb: 500 },
    ],
    destination: 'public/images/website/menulist-og-official-source.png',
    component: 'src/app/(website)/layout.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      '__docs__/main-website/asset-production/launch-pack-2026-07/menulist-launch-pack.md',
      'scripts/website-assets/generate-stage6-assets.mjs',
      'public/images/website/menulist-hero-official-source.webp',
    ],
    mobile: {
      required: true,
      maxKb: 500,
      notes: 'Must remain readable in messaging previews and social cards.',
    },
  },
  {
    id: 'menulist.home.customer-browse.mobile-menu',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/#customer-demo',
    placement: 'customer browsing section',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show the public menu experience customers see on a phone.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '9:16', maxKb: 220 }],
    destination: 'public/images/website/menulist-public-menu-mobile.webp',
    component: 'src/components/website/home/CustomerBrowseSection.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/home/CustomerBrowseSection.tsx',
      'src/app/client/[[...slug]]/page.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'This is the primary mobile customer proof asset.',
    },
  },
  {
    id: 'menulist.home.public-presence.obp-browser',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/',
    placement: 'Official Business Page browser proof',
    type: 'static-image',
    required: false,
    blocking: false,
    intent: 'Show the Official Business Page as part of MenuList public presence.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '16:9', maxKb: 220 }],
    destination: 'public/images/website/menulist-obp-browser.webp',
    component: 'src/components/website/home/BusinessSection.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/home/BusinessSection.tsx',
      'src/app/client/obp/OBPContent.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'OBP browser proof must stay readable when scaled down on mobile.',
    },
  },
  {
    id: 'menulist.home.setup-relief.workflow',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/',
    placement: 'setup relief workflow',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show upload, review, and publish as a low-effort owner workflow.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '16:9', maxKb: 220 }],
    destination: 'public/images/website/menulist-setup-relief-workflow.webp',
    component: 'src/components/website/home/SetupReliefSection.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/home/SetupReliefSection.tsx',
      'src/components/templates/main-app/projects/jobScreens/ExtractionJobReviewScreen.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'Workflow labels must not become unreadable on small screens.',
    },
  },
  {
    id: 'menulist.home.public-surfaces.matrix',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/#public-proof',
    placement: 'public surfaces proof matrix',
    type: 'static-image',
    required: true,
    blocking: true,
    intent: 'Show that the same approved truth appears across public surfaces.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '16:9', maxKb: 260 }],
    destination: 'public/images/website/menulist-public-surfaces-matrix.webp',
    component: 'src/components/website/home/SurfacesSection.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/home/SurfacesSection.tsx',
      'src/components/mobile/screens/MobileShareScreen.tsx',
      'src/app/client/obp/OBPContent.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 260,
      notes: 'Matrix must preserve proof hierarchy without horizontal overflow.',
    },
  },
  {
    id: 'menulist.home.analytics.status-proof',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/',
    placement: 'analytics and status proof',
    type: 'static-image',
    required: false,
    blocking: false,
    intent: 'Support the idea that public menu state can be monitored without inventing customer metrics.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '16:9', maxKb: 220 }],
    destination: 'public/images/website/menulist-analytics-proof.webp',
    component: 'src/components/website/home/AnalyticsInsightsSection.tsx',
    approval: 'founder-review',
    autonomyLevel: 3,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'src/components/website/home/AnalyticsInsightsSection.tsx',
      'src/components/templates/main-app/dashboard/OwnerDashboard/index.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'Synthetic status signals must not be confused with real customer analytics.',
    },
  },
  {
    id: 'menulist.launch.social.square',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList launch assets',
    route: '/',
    placement: 'square launch/social image',
    type: 'static-image',
    required: false,
    blocking: false,
    intent: 'Provide a square launch image derived from approved homepage proof.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'png', role: 'social', ratio: '1:1', maxKb: 500 }],
    destination: 'public/images/website/menulist-launch-square.png',
    approval: 'founder-review',
    autonomyLevel: 3,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      '__docs__/main-website/asset-production/launch-pack-2026-07/menulist-launch-pack.md',
      'scripts/website-assets/generate-stage6-assets.mjs',
    ],
    mobile: {
      required: true,
      maxKb: 500,
      notes: 'Must read clearly in mobile social previews.',
    },
  },
  {
    id: 'menulist.launch.device.owner-pwa-dashboard',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList launch assets and Owner PWA Dashboard feature page',
    route: '/features/owner-phone-dashboard',
    placement: 'owner-device launch mockup and feature-page proof',
    type: 'static-image',
    required: false,
    blocking: false,
    intent: 'Show the real MenuList owner-mobile information hierarchy inside a restrained phone composition.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'webp', role: 'primary', ratio: '9:16', maxKb: 220 }],
    destination: 'public/images/website/product-proof/owner-phone-dashboard.webp',
    component: 'src/components/website/features/FeatureScreenshotProofGallery.tsx',
    approval: 'automatic',
    autonomyLevel: 2,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      '__docs__/main-website/asset-production/stage-08-product-proof/stage-08-product-proof-demo-assets.md',
      '__docs__/main-website/asset-production/launch-pack-2026-07/menulist-launch-pack.md',
      'scripts/website-assets/generate-product-proof-assets.mjs',
      'src/components/website/features/FeatureScreenshotProofGallery.tsx',
      'src/components/mobile/MobileShell.tsx',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'The phone screen must remain readable and clearly labeled as fictional demo data.',
    },
  },
  {
    id: 'menulist.launch.social.linkedin',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList launch assets',
    route: '/',
    placement: 'LinkedIn launch image',
    type: 'static-image',
    required: false,
    blocking: false,
    intent: 'Provide a professional launch preview for founder distribution.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [{ format: 'png', role: 'social', ratio: '1200x630', maxKb: 500 }],
    destination: 'public/images/website/menulist-linkedin-launch.png',
    approval: 'founder-review',
    autonomyLevel: 3,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      '__docs__/main-website/asset-production/launch-pack-2026-07/menulist-launch-pack.md',
      'scripts/website-assets/generate-stage6-assets.mjs',
    ],
    mobile: {
      required: true,
      maxKb: 500,
      notes: 'Must avoid tiny product text that becomes unreadable in feed cards.',
    },
  },
  {
    id: 'menulist.home.hero.business-truth-loop',
    brand: 'menulist',
    productBoundary: 'internal-product-architecture',
    page: 'MenuList homepage',
    route: '/',
    placement: 'homepage hero motion layer',
    type: 'loop-video',
    required: false,
    blocking: false,
    intent: 'Show the menu truth loop across owner approval, public menu, OBP, QR, and screen surfaces.',
    narrativeRules: menuListAssetRules,
    rejectionRules: menuListRejectionRules,
    outputs: [
      { format: 'webm', role: 'primary', ratio: '16:9', maxKb: 1200 },
      { format: 'mp4', role: 'fallback', ratio: '16:9', maxKb: 1800 },
      { format: 'webp', role: 'poster', ratio: '16:9', maxKb: 220 },
    ],
    destination: 'public/images/website/menulist-business-truth-loop.webm',
    component: 'src/components/website/home/HeroSection.tsx',
    approval: 'founder-required',
    autonomyLevel: 3,
    sources: [
      '__docs__/main-website/main-website_image-assets.md',
      'scripts/website-assets/generate-assetos-motion-compositions.mjs',
      'scripts/website-assets/transcode-assetos-motion-assets.mjs',
      '__docs__/videos/hyperframes/menulist-business-truth-loop/index.html',
      '__docs__/videos/hyperframes/menulist-business-truth-loop/shot-plan.json',
      'public/icons/icon-512x512.png',
      'src/components/website/home/HeroSection.tsx',
      'src/components/website/home/SurfacesSection.tsx',
      'src/styles/website.css',
    ],
    mobile: {
      required: true,
      maxKb: 220,
      notes: 'Motion must have a static poster and reduced-motion fallback.',
    },
  },
  ...menuListLaunchFrameSlots,
];
