import { GEMINI_MODELS } from '@constant/AI/models';
import {
    ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG,
    ANSWERLATTICE_EMBEDDING_CONFIGS,
    ANSWERLATTICE_EMBEDDING_VERSIONS,
    ANSWERLATTICE_LEGACY_EMBEDDING_CONFIG,
} from '@data/shared/answerlatticeEmbedding';

export {
    ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG,
    ANSWERLATTICE_EMBEDDING_CONFIGS,
    ANSWERLATTICE_EMBEDDING_VERSIONS,
    ANSWERLATTICE_LEGACY_EMBEDDING_CONFIG,
};

export const ANSWERLATTICE_AI_ENV = {
    GEMINI_AI_KEY: 'ANSWERLATTICE_GEMINI_AI_KEY',
    GEMINI_AI_KEY_2: 'ANSWERLATTICE_GEMINI_AI_KEY_2',
    GEMINI_AI_KEY_3: 'ANSWERLATTICE_GEMINI_AI_KEY_3',
    GEMINI_AI_KEY_4: 'ANSWERLATTICE_GEMINI_AI_KEY_4',
} as const;

export const ANSWERLATTICE_TEXT_MODEL = GEMINI_MODELS.TEXT_GEN;
export const ANSWERLATTICE_VISION_CONTEXT_MODEL = GEMINI_MODELS.TEXT_GEN;

export const ANSWERLATTICE_EMBEDDING_MODEL = ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.model;
export const ANSWERLATTICE_EMBEDDING_OUTPUT_DIMENSIONALITY =
    ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.outputDimensionality;
export const ANSWERLATTICE_EMBEDDING_CACHE_VERSION = ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.cacheVersion;
export const ANSWERLATTICE_EMBEDDING_VECTOR_FIELD = ANSWERLATTICE_ACTIVE_EMBEDDING_CONFIG.vectorField;
