import { GEMINI_MODELS } from '@constant/AI/models';

export const ANSWERLATTICE_TEXT_MODEL = GEMINI_MODELS.TEXT_GEN;
export const ANSWERLATTICE_VISION_CONTEXT_MODEL = GEMINI_MODELS.TEXT_GEN;

// Keep this model until existing article/query vectors are re-embedded.
export const ANSWERLATTICE_EMBEDDING_MODEL = GEMINI_MODELS.TEXT_EMBEDDING;
export const ANSWERLATTICE_EMBEDDING_OUTPUT_DIMENSIONALITY = 768;
export const ANSWERLATTICE_EMBEDDING_CACHE_VERSION =
    `${ANSWERLATTICE_EMBEDDING_MODEL}:${ANSWERLATTICE_EMBEDDING_OUTPUT_DIMENSIONALITY}:v1`;

