import type { AnswerlatticeVisualAsset } from './types';

export const ANSWERLATTICE_VISUAL_ASSETS: AnswerlatticeVisualAsset[] = [
    {
        id: 'home.hero.product-loop',
        route: '/',
        placement: 'Homepage hero product scene',
        status: 'implemented-vector',
        format: 'animated-vector-diagram',
        currentAsset: 'AnswerlatticeHeroAutomationDiagram',
        futureAssetName: 'answerlattice-home-hero-automation-scene',
        visualDirection: 'A low floating automation scene where labeled product-source tiles move into the AnswerLattice logo target and slim approved-support cards emerge from that center.',
        mustShow: ['labeled source tiles', 'AnswerLattice logo target', 'input motion paths', 'queued output cards', 'widget and hosted help outputs', 'FAQ, changelog, fallback, feedback, Support Board, custom domain, workflow update, future-context, and gap outputs'],
        mustAvoid: ['fake customer logos', 'autonomous support claims', 'helpdesk replacement framing'],
    },
    {
        id: 'home.support-surfaces.sticky-story',
        route: '/',
        placement: 'Sticky support-surface story cards',
        status: 'generated-product-scene',
        format: 'sequence-screens',
        currentAsset: 'knowledge-intake, product-area-widget, support-control, tickets, governance generated PNG slots',
        futureAssetName: 'answerlattice-home-support-surface-story',
        visualDirection: 'A five-step source-to-support-surface sequence with subtle movement between cards.',
        mustShow: ['owner inputs', 'in-product help', 'hosted help', 'fallback gaps', 'approved-answer review'],
        mustAvoid: ['cartoon mascots', 'busy confetti motion', 'claiming tickets publish answers automatically'],
    },
    {
        id: 'home.product-overview.feature-cards',
        route: '/',
        placement: 'Feature-wise product overview cards',
        status: 'generated-product-scene',
        format: 'feature-card-screens',
        currentAsset: 'product-area and feature generated PNG slots',
        futureAssetName: 'answerlattice-home-product-overview-feature-set',
        visualDirection: 'Feature cards should feel like a product control surface, not decorative illustrations.',
        mustShow: ['widget', 'hosted help', 'tickets', 'FAQ', 'changelog', 'feedback', 'Support Board', 'knowledge intake'],
        mustAvoid: ['marketing-only icons', 'unimplemented integrations', 'fake analytics numbers'],
    },
    {
        id: 'home.owner-decision-system',
        route: '/',
        placement: 'Owner decision system proof',
        status: 'generated-product-scene',
        format: 'screen-or-short-loop',
        currentAsset: 'answerlattice-owner-decision-system.webp',
        futureAssetName: 'answerlattice-owner-decision-system',
        visualDirection: 'A bounded Daily Brief routes qualified work to retained evidence, exact product context, and one owner-controlled review action.',
        mustShow: ['bounded brief', 'qualified evidence', 'retained product context', 'owner decision', 'quiet state'],
        mustAvoid: ['invented metrics', 'automatic decisions', 'unbounded task queue', 'fake customer activity'],
    },
    {
        id: 'home.support-loop.diagram',
        route: '/',
        placement: 'Support improvement loop diagram',
        status: 'implemented-vector',
        format: 'animated-vector-diagram',
        currentAsset: 'AnswerlatticeLoopDiagram',
        futureAssetName: 'answerlattice-home-support-loop-motion',
        visualDirection: 'Keep the current governed loop, then tune pacing and captions if needed.',
        mustShow: ['user asks', 'approved answer check', 'fallback', 'review work', 'approved improvement'],
        mustAvoid: ['LLM autopilot', 'automatic publishing', 'ticket automation as the center'],
    },
    {
        id: 'product.source-to-answer.illustration',
        route: '/product',
        placement: 'Product hero concept illustration',
        status: 'implemented-vector',
        format: 'static-vector-illustration',
        currentAsset: 'AnswerlatticeConceptIllustration: source-to-answer',
        futureAssetName: 'answerlattice-product-source-to-answer-illustration',
        visualDirection: 'Show source material flowing into the governed answer layer, then out to widget, hosted help, and review work.',
        mustShow: ['docs and FAQ', 'tickets and feedback', 'governed answer layer', 'widget', 'hosted help', 'review queue'],
        mustAvoid: ['raw AI generation as authority', 'unreviewed publishing', 'decorative-only icons'],
    },
    {
        id: 'product.governance-loop.illustration',
        route: '/product',
        placement: 'Approved-answer governance section',
        status: 'implemented-vector',
        format: 'static-vector-illustration',
        currentAsset: 'AnswerlatticeConceptIllustration: governance-loop',
        futureAssetName: 'answerlattice-product-governance-loop-illustration',
        visualDirection: 'Show missing answers moving into review, owner approval, and future trusted support.',
        mustShow: ['fallback', 'review queue', 'owner approval', 'future trusted answer', 'canonical-first boundary'],
        mustAvoid: ['automatic publishing', 'AI confidence as truth', 'direct canonical edits'],
    },
    {
        id: 'install.verification-flow',
        route: '/install',
        placement: 'Install and framework quickstart surfaces',
        status: 'implemented-vector',
        format: 'static-vector-illustration',
        currentAsset: 'AnswerlatticeConceptIllustration: install-verification',
        futureAssetName: 'answerlattice-install-verification-flow',
        visualDirection: 'Show script install, allowed origin, blocked route, widget active, and fallback ready.',
        mustShow: ['framework install', 'origin allowlist', 'safe context', 'verification passed'],
        mustAvoid: ['exposing widget keys', 'private route content', 'enterprise implementation complexity'],
    },
    {
        id: 'security.safe-context-boundary',
        route: '/security',
        placement: 'Safe page context and runtime controls',
        status: 'implemented-vector',
        format: 'static-vector-illustration',
        currentAsset: 'AnswerlatticeConceptIllustration: safe-context-boundary',
        futureAssetName: 'answerlattice-security-safe-context-boundary',
        visualDirection: 'A boundary diagram separating allowed page context from blocked private data.',
        mustShow: ['allowed public context', 'blocked private data', 'owner-approved answers', 'fallback path'],
        mustAvoid: ['SOC/GDPR certification claims', 'raw console logs', 'full app screen capture'],
    },
    {
        id: 'comparisons.positioning-boundary.illustration',
        route: '/comparisons',
        placement: 'Comparisons hero category-boundary panel',
        status: 'implemented-vector',
        format: 'static-vector-illustration',
        currentAsset: 'AnswerlatticeConceptIllustration: positioning-boundary',
        futureAssetName: 'answerlattice-comparisons-positioning-boundary-illustration',
        visualDirection: 'Show AnswerLattice as the answer authority layer between chatbots, helpdesks, docs, and ticket fallback.',
        mustShow: ['chatbot boundary', 'helpdesk boundary', 'docs boundary', 'answer authority layer', 'works with tools'],
        mustAvoid: ['vendor ranking', 'fake ratings', 'replacement claims'],
    },
    {
        id: 'demo.page-aware-widget',
        route: '/demo',
        placement: 'Account-free page-aware demo',
        status: 'generated-product-scene',
        format: 'short-loop',
        currentAsset: 'answerlattice-demo-surface-*.png',
        futureAssetName: 'answerlattice-demo-page-aware-widget',
        visualDirection: 'Billing, onboarding, settings, and release questions should each show a different governed answer path.',
        mustShow: ['surface-specific question', 'approved answer', 'fallback when uncovered'],
        mustAvoid: ['real customer data', 'live AI calls', 'promising perfect answers'],
    },
    {
        id: 'product.area.launch-setup',
        route: '/product/launch-setup',
        placement: 'Product-area hero canvas',
        status: 'generated-product-scene',
        format: 'screen-or-short-loop',
        currentAsset: 'answerlattice-product-area-launch-setup.png',
        futureAssetName: 'answerlattice-product-area-launch-setup',
        visualDirection: 'First-session setup from sources to mapped product pages and widget readiness.',
        mustShow: ['starter sources', 'product pages', 'reviewed answers', 'widget readiness'],
        mustAvoid: ['unbounded crawling', 'auto-publishing', 'multi-week enterprise rollout'],
    },
    {
        id: 'product.area.page-aware-widget',
        route: '/product/page-aware-widget',
        placement: 'Product-area hero canvas',
        status: 'generated-product-scene',
        format: 'screen-or-short-loop',
        currentAsset: 'answerlattice-product-area-widget.png',
        futureAssetName: 'answerlattice-product-area-page-aware-widget',
        visualDirection: 'Widget context follows the product page while staying inside safe boundaries.',
        mustShow: ['page context', 'allowed origins', 'approved answer', 'fallback ticket'],
        mustAvoid: ['full DOM scraping', 'private customer data', 'always-on autonomous behavior'],
    },
    {
        id: 'product.area.support-control',
        route: '/product/support-control',
        placement: 'Product-area hero canvas',
        status: 'generated-product-scene',
        format: 'screen-or-short-loop',
        currentAsset: 'answerlattice-product-area-support-control.png',
        futureAssetName: 'answerlattice-product-area-support-control',
        visualDirection: 'Hosted help, FAQ, changelog, tickets, and feedback as connected surfaces.',
        mustShow: ['hosted help', 'FAQ', 'changelog', 'ticket fallback', 'feedback review'],
        mustAvoid: ['helpdesk replacement positioning', 'agent routing', 'omnichannel ownership'],
    },
    {
        id: 'product.knowledge-map',
        route: '/product/knowledge-governance',
        placement: 'Product-area hero canvas',
        status: 'generated-product-scene',
        format: 'screen-or-short-loop',
        currentAsset: 'answerlattice-knowledge-map.webp',
        futureAssetName: 'answerlattice-knowledge-map',
        visualDirection: 'A curated product hierarchy exposes answer coverage, drift, and review state while keeping raw ontology and private evidence out of the public scene.',
        mustShow: ['primary product hierarchy', 'approved-answer coverage', 'freshness state', 'selected product area', 'owner review path'],
        mustAvoid: ['raw graph', 'all cross-links', 'private tickets', 'invented demand metrics', 'automatic rewriting'],
    },
    {
        id: 'product.release-assurance',
        route: '/product/knowledge-governance',
        placement: 'Release impact and Answer Tests workflow proof',
        status: 'generated-product-scene',
        format: 'screen-or-short-loop',
        currentAsset: 'answerlattice-release-assurance.webp',
        futureAssetName: 'answerlattice-release-assurance',
        visualDirection: 'A release change points to directly linked approved answers and deterministic Answer Test outcomes before owner-controlled activation.',
        mustShow: ['release change', 'linked approved answers', 'stale guidance', 'passed check', 'needs-review check', 'safe abstention', 'owner confirmation'],
        mustAvoid: ['automatic activation', 'automatic rollback', 'provider fallback as critical proof', 'invented pass-rate metrics'],
    },
    {
        id: 'product.article-topic-map',
        route: '/product/knowledge-base',
        placement: 'Knowledge Base hero proof',
        status: 'generated-product-scene',
        format: 'screen-or-short-loop',
        currentAsset: 'answerlattice-article-topic-map.webp',
        futureAssetName: 'answerlattice-article-topic-map',
        visualDirection: 'Published article headings form an accessible topic path with an approved summary and related public guides.',
        mustShow: ['published headings', 'selected topic', 'approved summary', 'related published guides', 'mobile drill-down'],
        mustAvoid: ['private Knowledge Map data', 'draft content', 'ticket evidence', 'raw ontology', 'canvas-only mobile interaction'],
    },
    {
        id: 'feature.template.hero-scene',
        route: '/product/*',
        placement: 'Feature-page hero and proof canvas',
        status: 'generated-product-scene',
        format: 'feature-screen-set',
        currentAsset: 'answerlattice-feature-*.png',
        futureAssetName: 'answerlattice-feature-screen-set',
        visualDirection: 'Each feature page needs one concrete product scene and one workflow proof, using the same visual language.',
        mustShow: ['feature-specific screen', 'connected support layer', 'owner control'],
        mustAvoid: ['one-off art styles', 'unsupported feature depth', 'decorative-only SVGs'],
    },
];
