/**
 * Multi-Product Platform Types
 * 
 * Types for cross-product integration, CCT tokens, and platform context.
 * 
 * @see __docs__/answerlattice/doctrine/07-multi-product-tenancy.md v4.3.0
 */

import { ProductId } from "@constant/product";

/**
 * sourceContext — stored on cross-product Answerlattice documents.
 * Contains user identity (always) and source product scope (cross-product only).
 */
export interface SourceContext {
    uId: number | string;
    name: string;
    email: string;
    phone?: string;
    pId?: ProductId;
    tId?: number;
    sId?: number;
}

/**
 * Answerlattice Client Token (CCT) payload.
 * Signed JWT generated by client product, verified by Answerlattice.
 */
export interface AnswerlatticeClientTokenPayload {
    clientId: string;
    traceId: string;
    requestId: string;
    pId?: ProductId;
    tId?: number;
    sId?: number;
    uId: number | string;
    name: string;
    email: string;
    phone?: string;
    iat: number;
    exp: number;
}

/**
 * AnswerlatticePlatformContext — the ONLY way Answerlattice features access identity.
 * Built after CCT decode + client registry lookup.
 */
export interface AnswerlatticePlatformContext {
    traceId: string;
    requestId: string;
    client: {
        clientId: string;
        tId: number;
        sId: number;
    };
    source: SourceContext;
    issuedAt: number;
}

/**
 * Answerlattice Client Registry entry.
 * Stored in answerlattice_clients collection in Answerlattice Firestore.
 */
export interface AnswerlatticeClient {
    clientId: string;
    clientName: string;
    tId: number;
    sId: number;
    secretKey: string;
    sourcePId: ProductId | null;
    active: boolean;
    createdOn?: any;
    modifiedOn?: any;
}
