/**
 * Multi-Product Platform Types
 * 
 * Types for cross-product integration, CCT tokens, and platform context.
 * 
 * @see __docs__/canonica/doctrine/07-multi-product-tenancy.md v4.3.0
 */

import { ProductId } from "@constant/product";

/**
 * sourceContext — stored on cross-product Canonica documents.
 * Contains user identity (always) and source product scope (cross-product only).
 */
export interface SourceContext {
    uId: number;
    name: string;
    email: string;
    phone?: string;
    pId?: ProductId;
    tId?: number;
    sId?: number;
}

/**
 * Canonica Client Token (CCT) payload.
 * Signed JWT generated by client product, verified by Canonica.
 */
export interface CanonicaClientTokenPayload {
    clientId: string;
    traceId: string;
    requestId: string;
    pId?: ProductId;
    tId?: number;
    sId?: number;
    uId: number;
    name: string;
    email: string;
    phone?: string;
    iat: number;
    exp: number;
}

/**
 * CanonicaPlatformContext — the ONLY way Canonica features access identity.
 * Built after CCT decode + client registry lookup.
 */
export interface CanonicaPlatformContext {
    traceId: string;
    requestId: string;
    client: {
        clientId: string;
        tId: number;
        sId: number;
    };
    source: SourceContext;
    issuedAt: number;
}

/**
 * Canonica Client Registry entry.
 * Stored in canonica_clients collection in Canonica Firestore.
 */
export interface CanonicaClient {
    clientId: string;
    clientName: string;
    tId: number;
    sId: number;
    secretKey: string;
    sourcePId: ProductId | null;
    active: boolean;
    createdOn?: any;
    modifiedOn?: any;
}
