import type { AiMenuManagerActionDefinition, AiMenuManagerActionType } from '@type/aiMenuManager';

export const AI_MENU_MANAGER_ACTION_TYPES = {
    ITEM_PRICE_UPDATE: 'item_price_update',
    ITEM_CREATE: 'item_create',
    ITEM_UPDATE: 'item_update',
    ITEM_NAME_UPDATE: 'item_name_update',
    ITEM_DESCRIPTION_UPDATE: 'item_description_update',
    ITEM_DESCRIPTION_GENERATE: 'item_description_generate',
    ITEM_DESCRIPTION_REFRESH: 'item_description_refresh',
    ITEM_CATEGORY_UPDATE: 'item_category_update',
    ITEM_AVAILABILITY_UPDATE: 'item_availability_update',
    ITEM_VISIBILITY_UPDATE: 'item_visibility_update',
    ITEM_ATTRIBUTE_CREATE: 'item_attribute_create',
    ITEM_ATTRIBUTE_UPDATE: 'item_attribute_update',
    ITEM_ATTRIBUTE_DELETE: 'item_attribute_delete',
    ITEM_ATTRIBUTE_NAME_UPDATE: 'item_attribute_name_update',
    ITEM_ATTRIBUTE_PRICE_UPDATE: 'item_attribute_price_update',
    ITEM_ATTRIBUTE_VISIBILITY_UPDATE: 'item_attribute_visibility_update',
    ITEM_ATTRIBUTE_ORDER_UPDATE: 'item_attribute_order_update',
    ITEM_BESTSELLER_UPDATE: 'item_bestseller_update',
    ITEM_PREP_TIME_UPDATE: 'item_prep_time_update',
    ITEM_PROMOTION_WEIGHT_UPDATE: 'item_promotion_weight_update',
    ITEM_METADATA_UPDATE: 'item_metadata_update',
    ITEM_METADATA_GENERATE: 'item_metadata_generate',
    ITEM_TRANSLATION_REPAIR: 'item_translation_repair',
    ITEM_IMAGE_UPDATE: 'item_image_update',
    ITEM_ORDER_UPDATE: 'item_order_update',
    ITEM_QUALITY_REVIEW_UPDATE: 'item_quality_review_update',
    ITEM_IDENTITY_REFERENCE: 'item_identity_reference',
    ITEM_DELETE: 'item_delete',
    CATEGORY_CREATE: 'category_create',
    CATEGORY_UPDATE: 'category_update',
    CATEGORY_NAME_UPDATE: 'category_name_update',
    CATEGORY_VISIBILITY_UPDATE: 'category_visibility_update',
    CATEGORY_ICON_UPDATE: 'category_icon_update',
    CATEGORY_IMAGE_UPDATE: 'category_image_update',
    CATEGORY_TIME_SLOT_UPDATE: 'category_time_slot_update',
    CATEGORY_TIME_SLOT_PRESET_CREATE: 'category_time_slot_preset_create',
    CATEGORY_TRANSLATION_REPAIR: 'category_translation_repair',
    CATEGORY_ORDER_UPDATE: 'category_order_update',
    CATEGORY_IDENTITY_REFERENCE: 'category_identity_reference',
    CATEGORY_DELETE: 'category_delete',
    DECISION_BLOCKS_UPDATE: 'decision_blocks_update',
    MENU_SPECIAL_NOTE_UPDATE: 'menu_special_note_update',
    MENU_DESIGN_MOOD_UPDATE: 'menu_design_mood_update',
    BULK_PRICE_UPDATE: 'bulk_price_update',
    BULK_AVAILABILITY_UPDATE: 'bulk_availability_update',
    IMAGE_ITEM_GENERATE: 'image_item_generate',
    IMAGE_ITEM_APPLY_GENERATED: 'image_item_apply_generated',
    MENU_FILE_UPLOAD: 'menu_file_upload',
    MENU_LINK_IMPORT: 'menu_link_import',
    MENU_IMPORT_REVIEW_APPLY: 'menu_import_review_apply',
    SPECIAL_MENU_CREATE: 'special_menu_create',
    SPECIAL_MENU_ACTIVATE: 'special_menu_activate',
    MENU_PUBLISH: 'menu_publish',
    SYSTEM_MANUAL_TASK_CREATE: 'system_manual_task_create',
    SYSTEM_CLARIFICATION_REQUEST: 'system_clarification_request',
    SYSTEM_UNSUPPORTED_ACTION: 'system_unsupported_action',
} as const satisfies Record<string, AiMenuManagerActionType>;

export const AI_MENU_MANAGER_EXECUTABLE_ACTIONS: AiMenuManagerActionType[] = [
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_PRICE_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_NAME_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_CATEGORY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_AVAILABILITY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_VISIBILITY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_NAME_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_PRICE_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_VISIBILITY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_ORDER_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_BESTSELLER_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_PREP_TIME_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_PROMOTION_WEIGHT_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_ORDER_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_QUALITY_REVIEW_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_NAME_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_VISIBILITY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_ICON_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_TIME_SLOT_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_ORDER_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.DECISION_BLOCKS_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.MENU_SPECIAL_NOTE_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_MOOD_UPDATE,
];

export type AiMenuManagerFieldHandling =
    | 'direct_project_patch'
    | 'existing_api_job'
    | 'manual_task'
    | 'read_only'
    | 'system_protected';

export const AI_MENU_MANAGER_CATEGORY_FIELD_ACTION_COVERAGE = [
    { field: 'id', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_IDENTITY_REFERENCE, handling: 'system_protected' },
    { field: 'active', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_VISIBILITY_UPDATE, handling: 'direct_project_patch' },
    { field: 'name', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_NAME_UPDATE, handling: 'direct_project_patch' },
    { field: 'extractionIdAliases', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_IDENTITY_REFERENCE, handling: 'system_protected' },
    { field: 'icon', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_ICON_UPDATE, handling: 'direct_project_patch' },
    { field: 'images', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_IMAGE_UPDATE, handling: 'manual_task' },
    { field: 'timeSlots', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_TIME_SLOT_UPDATE, handling: 'direct_project_patch' },
    { field: 'orderIndex', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_ORDER_UPDATE, handling: 'direct_project_patch' },
] as const satisfies ReadonlyArray<{
    field: string;
    actionType: AiMenuManagerActionType;
    handling: AiMenuManagerFieldHandling;
}>;

export const AI_MENU_MANAGER_ATTRIBUTE_FIELD_ACTION_COVERAGE = [
    { field: 'id', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IDENTITY_REFERENCE, handling: 'system_protected' },
    { field: 'name', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_NAME_UPDATE, handling: 'direct_project_patch' },
    { field: 'price', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_PRICE_UPDATE, handling: 'direct_project_patch' },
    { field: 'active', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_VISIBILITY_UPDATE, handling: 'direct_project_patch' },
    { field: 'orderIndex', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_ORDER_UPDATE, handling: 'direct_project_patch' },
] as const satisfies ReadonlyArray<{
    field: string;
    actionType: AiMenuManagerActionType;
    handling: AiMenuManagerFieldHandling;
}>;

export const AI_MENU_MANAGER_ITEM_FIELD_ACTION_COVERAGE = [
    { field: 'id', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IDENTITY_REFERENCE, handling: 'system_protected' },
    { field: 'extractionIdAliases', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IDENTITY_REFERENCE, handling: 'system_protected' },
    { field: 'attributes', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_UPDATE, handling: 'direct_project_patch' },
    { field: 'category', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_CATEGORY_UPDATE, handling: 'direct_project_patch' },
    { field: 'name', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_NAME_UPDATE, handling: 'direct_project_patch' },
    { field: 'description', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_UPDATE, handling: 'direct_project_patch' },
    { field: 'descriptionSource', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_UPDATE, handling: 'system_protected' },
    { field: 'price', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PRICE_UPDATE, handling: 'direct_project_patch' },
    { field: 'images', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IMAGE_UPDATE, handling: 'manual_task' },
    { field: 'tags', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'active', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_VISIBILITY_UPDATE, handling: 'direct_project_patch' },
    { field: 'available', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_AVAILABILITY_UPDATE, handling: 'direct_project_patch' },
    { field: 'isBestSeller', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_BESTSELLER_UPDATE, handling: 'direct_project_patch' },
    { field: 'decisionFacts', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'allergens', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'dietaryTags', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'spiceLevel', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'nutritionInfo', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'skillLevel', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'targetAudience', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'materials', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'warranty', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'duration', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PREP_TIME_UPDATE, handling: 'direct_project_patch' },
    { field: 'ownerBoost', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PROMOTION_WEIGHT_UPDATE, handling: 'direct_project_patch' },
    { field: 'orderIndex', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ORDER_UPDATE, handling: 'direct_project_patch' },
    { field: 'qualityReview', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_QUALITY_REVIEW_UPDATE, handling: 'direct_project_patch' },
] as const satisfies ReadonlyArray<{
    field: string;
    actionType: AiMenuManagerActionType;
    handling: AiMenuManagerFieldHandling;
}>;

export const AI_MENU_MANAGER_ACTION_DEFINITIONS: AiMenuManagerActionDefinition[] = [
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PRICE_UPDATE,
        ownerLabel: 'Update price',
        manualEquivalent: 'Item price field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:351'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_CREATE,
        ownerLabel: 'Add item',
        manualEquivalent: 'Add item in menu editor',
        executionMode: 'manual_task_card',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/utils/editorOperations.ts:64'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_UPDATE,
        ownerLabel: 'Update item details',
        manualEquivalent: 'Edit item modal save',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:554'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_NAME_UPDATE,
        ownerLabel: 'Rename item',
        manualEquivalent: 'Item name field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:351'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_UPDATE,
        ownerLabel: 'Update item description',
        manualEquivalent: 'Item description field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:351'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_GENERATE,
        ownerLabel: 'Generate item description',
        manualEquivalent: 'Item metadata/description generation',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Draft card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:496'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_REFRESH,
        ownerLabel: 'Refresh item descriptions',
        manualEquivalent: 'Description generation modal',
        executionMode: 'existing_api_job',
        approvalLevel: 'bulk_confirm',
        risk: 'high',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Summary card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/DescriptionGenerationModal.tsx'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_CATEGORY_UPDATE,
        ownerLabel: 'Move item to category',
        manualEquivalent: 'Item category selector',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:57'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_AVAILABILITY_UPDATE,
        ownerLabel: 'Update availability',
        manualEquivalent: 'Availability toggle',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:673'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_VISIBILITY_UPDATE,
        ownerLabel: 'Show or hide item',
        manualEquivalent: 'Item active field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:673'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_CREATE,
        ownerLabel: 'Add item variation',
        manualEquivalent: 'Attribute add helper',
        executionMode: 'manual_task_card',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:425'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_UPDATE,
        ownerLabel: 'Update item variation',
        manualEquivalent: 'Attribute field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:351'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_DELETE,
        ownerLabel: 'Delete item variation',
        manualEquivalent: 'Attribute delete helper',
        executionMode: 'manual_task_card',
        approvalLevel: 'destructive_confirm',
        risk: 'high',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/utils/editorOperations.ts:212'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_NAME_UPDATE,
        ownerLabel: 'Rename item variation',
        manualEquivalent: 'Attribute name field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:373'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_PRICE_UPDATE,
        ownerLabel: 'Update variation price',
        manualEquivalent: 'Attribute price field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:387'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_VISIBILITY_UPDATE,
        ownerLabel: 'Show or hide variation',
        manualEquivalent: 'Attribute active toggle',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/components/mobile/sheets/ItemEditSheet.tsx:821'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_ORDER_UPDATE,
        ownerLabel: 'Reorder item variations',
        manualEquivalent: 'Attribute order in item editor',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/sheets/ItemEditSheet.tsx:637'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_BESTSELLER_UPDATE,
        ownerLabel: 'Update bestseller flag',
        manualEquivalent: 'Best Seller toggle',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:696'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PREP_TIME_UPDATE,
        ownerLabel: 'Update prep or service time',
        manualEquivalent: 'Prep time field',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:727'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PROMOTION_WEIGHT_UPDATE,
        ownerLabel: 'Update promotion weight',
        manualEquivalent: 'Promotion slider',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:747'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE,
        ownerLabel: 'Update item details',
        manualEquivalent: 'Business-aware item detail fields',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:769'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_GENERATE,
        ownerLabel: 'Generate item details',
        manualEquivalent: 'New item metadata API',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Draft card',
        sourceEvidence: ['src/app/api/new-item-metadata/route.ts'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_TRANSLATION_REPAIR,
        ownerLabel: 'Repair item translation',
        manualEquivalent: 'Retry item translation',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Draft card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:402'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IMAGE_UPDATE,
        ownerLabel: 'Update item image',
        manualEquivalent: 'Item image upload/apply flow',
        executionMode: 'manual_task_card',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C5 manual only',
        mobileBehavior: 'Image task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/uploadedImagesList.tsx'],
        readiness: 'manual_task_only',
        requiredFlags: ['ENABLE_AI_MENU_MANAGER_IMAGE_ACTIONS'],
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ORDER_UPDATE,
        ownerLabel: 'Reorder item',
        manualEquivalent: 'Reorder menu modal',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/ReorderMenuModal.tsx:200'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_QUALITY_REVIEW_UPDATE,
        ownerLabel: 'Mark item review checked',
        manualEquivalent: 'Price warning review marker',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/components/mobile/screens/MobileMenuScreen.tsx:995'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IDENTITY_REFERENCE,
        ownerLabel: 'Read item identity',
        manualEquivalent: 'System item identity reference',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Read-only card',
        sourceEvidence: ['src/components/templates/main-app/projects/types/extractedData.types.ts:70'],
        readiness: 'blocked',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DELETE,
        ownerLabel: 'Delete item',
        manualEquivalent: 'Item delete confirmation',
        executionMode: 'manual_task_card',
        approvalLevel: 'destructive_confirm',
        risk: 'high',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Destructive task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/utils/editorOperations.ts:191'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_CREATE,
        ownerLabel: 'Add category',
        manualEquivalent: 'Create category helper',
        executionMode: 'manual_task_card',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/utils/editorOperations.ts:28'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_UPDATE,
        ownerLabel: 'Update category',
        manualEquivalent: 'Category modal save',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:219'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_NAME_UPDATE,
        ownerLabel: 'Rename category',
        manualEquivalent: 'Category name field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:584'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_VISIBILITY_UPDATE,
        ownerLabel: 'Show or hide category',
        manualEquivalent: 'Category active toggle',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: [
            'src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:437',
            'src/components/mobile/screens/MobileMenuScreen.tsx:3450',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_ICON_UPDATE,
        ownerLabel: 'Update category icon',
        manualEquivalent: 'Category icon picker',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:448'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_IMAGE_UPDATE,
        ownerLabel: 'Update category image',
        manualEquivalent: 'Category image data field',
        executionMode: 'manual_task_card',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/types/extractedData.types.ts:35'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_TIME_SLOT_UPDATE,
        ownerLabel: 'Update category time slot',
        manualEquivalent: 'Category time-slot controls',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:131'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_TIME_SLOT_PRESET_CREATE,
        ownerLabel: 'Create category time preset',
        manualEquivalent: 'Create time slot preset',
        executionMode: 'existing_client_dal',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:166'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_TRANSLATION_REPAIR,
        ownerLabel: 'Repair category translations',
        manualEquivalent: 'Category translation generation',
        executionMode: 'existing_api_job',
        approvalLevel: 'bulk_confirm',
        risk: 'high',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Summary card',
        sourceEvidence: ['src/components/templates/main-app/projects/utils/translationsUtils.ts:396'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_ORDER_UPDATE,
        ownerLabel: 'Reorder category',
        manualEquivalent: 'Reorder menu modal',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/ReorderMenuModal.tsx:190'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_IDENTITY_REFERENCE,
        ownerLabel: 'Read category identity',
        manualEquivalent: 'System category identity reference',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Read-only card',
        sourceEvidence: ['src/components/templates/main-app/projects/types/extractedData.types.ts:30'],
        readiness: 'blocked',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_DELETE,
        ownerLabel: 'Delete category',
        manualEquivalent: 'Category delete confirmation',
        executionMode: 'manual_task_card',
        approvalLevel: 'destructive_confirm',
        risk: 'high',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Destructive task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/utils/editorOperations.ts:160'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.DECISION_BLOCKS_UPDATE,
        ownerLabel: 'Update Featured section',
        manualEquivalent: 'Featured section settings',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: [
            'src/components/templates/main-app/projects/editorView/DecisionBlocksSettingsModal.tsx:243',
            'src/components/templates/main-app/projects/editorView/decisionBlocks.shared.ts:191',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_SPECIAL_NOTE_UPDATE,
        ownerLabel: 'Update menu note',
        manualEquivalent: 'Menu page settings special note',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/components/templates/main-app/projects/b2cView/menuPage/menuPageSettingsNew.tsx:211'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_MOOD_UPDATE,
        ownerLabel: 'Apply menu style',
        manualEquivalent: 'Menu design preset',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: [
            'src/components/templates/main-app/projects/b2cView/menuPage/menuPageSettingsNew.tsx:75',
            'src/components/templates/main-app/projects/b2cView/menuPage/menuPageSettingsNew.tsx:110',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.BULK_PRICE_UPDATE,
        ownerLabel: 'Bulk price update',
        manualEquivalent: 'Menu Command Center bulk pricing',
        executionMode: 'client_project_mutation',
        approvalLevel: 'bulk_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Summary card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/CommandCenterModal/utils/bulkOperations.ts:130'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.BULK_AVAILABILITY_UPDATE,
        ownerLabel: 'Bulk availability update',
        manualEquivalent: 'Menu Command Center bulk availability',
        executionMode: 'client_project_mutation',
        approvalLevel: 'bulk_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Summary card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/CommandCenterModal/utils/bulkOperations.ts:316'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.IMAGE_ITEM_GENERATE,
        ownerLabel: 'Generate item image',
        manualEquivalent: 'AI Image Generator',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Draft card',
        sourceEvidence: [
            'src/app/api/image-generation/route.ts',
            'src/components/templates/main-app/projects/editorView/AiImageGenerator/index.tsx',
        ],
        readiness: 'existing_api_only',
        requiredFlags: ['ENABLE_AI_MENU_MANAGER_IMAGE_ACTIONS'],
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.IMAGE_ITEM_APPLY_GENERATED,
        ownerLabel: 'Use generated image',
        manualEquivalent: 'Apply generated image to item',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Image/card approve',
        sourceEvidence: [
            'src/components/templates/main-app/projects/editorView/editItemModal.tsx:351',
            'src/lib/ai-menu-manager/actions/projectPatches.ts',
        ],
        readiness: 'needs_adapter_glue',
        requiredFlags: ['ENABLE_AI_MENU_MANAGER_IMAGE_ACTIONS'],
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_FILE_UPLOAD,
        ownerLabel: 'Upload menu file',
        manualEquivalent: 'Menu extraction upload',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Upload card',
        sourceEvidence: ['src/components/templates/main-app/projects/index.tsx:1737'],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_LINK_IMPORT,
        ownerLabel: 'Import menu link',
        manualEquivalent: 'Menu link import',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Upload card',
        sourceEvidence: ['src/components/templates/main-app/projects/index.tsx:1737'],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_IMPORT_REVIEW_APPLY,
        ownerLabel: 'Apply reviewed import',
        manualEquivalent: 'Menu extraction review apply',
        executionMode: 'client_project_mutation',
        approvalLevel: 'bulk_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Review card',
        sourceEvidence: [
            'src/components/templates/main-app/projects/jobScreens/ExtractionJobReviewScreen.tsx:304',
            'src/lib/extraction/applyChanges.ts:422',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SPECIAL_MENU_CREATE,
        ownerLabel: 'Create special menu',
        manualEquivalent: 'Special menu create',
        executionMode: 'existing_api_job',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Native mobile screen',
        sourceEvidence: [
            'src/hooks/useSpecialMenus.ts:127',
            'src/database/projects/index.ts:2234',
        ],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SPECIAL_MENU_ACTIVATE,
        ownerLabel: 'Activate special menu',
        manualEquivalent: 'Special menu activation',
        executionMode: 'existing_api_job',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Native mobile screen',
        sourceEvidence: [
            'src/hooks/useSpecialMenus.ts:223',
            'src/database/projects/index.ts:2547',
        ],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_PUBLISH,
        ownerLabel: 'Publish menu',
        manualEquivalent: 'Publish/share menu flow',
        executionMode: 'existing_api_job',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/database/projects/index.ts:1315'],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SYSTEM_MANUAL_TASK_CREATE,
        ownerLabel: 'Create manual task',
        manualEquivalent: 'Manual checklist/export task',
        executionMode: 'manual_task_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/lib/ai-menu-manager/cardBuilder.ts'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SYSTEM_CLARIFICATION_REQUEST,
        ownerLabel: 'Ask a question',
        manualEquivalent: 'Clarify before editing',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Conversation card',
        sourceEvidence: ['src/lib/ai-menu-manager/cardBuilder.ts'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SYSTEM_UNSUPPORTED_ACTION,
        ownerLabel: 'Unsupported external action',
        manualEquivalent: 'Manual task or existing screen handoff',
        executionMode: 'manual_task_card',
        approvalLevel: 'none',
        risk: 'high',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/lib/ai-menu-manager/cardBuilder.ts'],
        readiness: 'ready_adapter',
    },
];

export const AI_MENU_MANAGER_ACTION_DEFINITION_BY_TYPE: Record<AiMenuManagerActionType, AiMenuManagerActionDefinition> =
    Object.fromEntries(AI_MENU_MANAGER_ACTION_DEFINITIONS.map((definition) => [definition.actionType, definition])) as Record<AiMenuManagerActionType, AiMenuManagerActionDefinition>;
