import type { AiMenuManagerActionDefinition, AiMenuManagerActionType } from '@type/aiMenuManager';

export const AI_MENU_MANAGER_ACTION_TYPES = {
    ITEM_PRICE_UPDATE: 'item_price_update',
    ITEM_CREATE: 'item_create',
    ITEM_UPDATE: 'item_update',
    ITEM_NAME_UPDATE: 'item_name_update',
    ITEM_DESCRIPTION_UPDATE: 'item_description_update',
    ITEM_DESCRIPTION_GENERATE: 'item_description_generate',
    ITEM_DESCRIPTION_REFRESH: 'item_description_refresh',
    ITEM_CATEGORY_UPDATE: 'item_category_update',
    ITEM_AVAILABILITY_UPDATE: 'item_availability_update',
    ITEM_VISIBILITY_UPDATE: 'item_visibility_update',
    ITEM_ATTRIBUTE_CREATE: 'item_attribute_create',
    ITEM_ATTRIBUTE_UPDATE: 'item_attribute_update',
    ITEM_ATTRIBUTE_DELETE: 'item_attribute_delete',
    ITEM_ATTRIBUTE_NAME_UPDATE: 'item_attribute_name_update',
    ITEM_ATTRIBUTE_PRICE_UPDATE: 'item_attribute_price_update',
    ITEM_ATTRIBUTE_VISIBILITY_UPDATE: 'item_attribute_visibility_update',
    ITEM_ATTRIBUTE_ORDER_UPDATE: 'item_attribute_order_update',
    ITEM_BESTSELLER_UPDATE: 'item_bestseller_update',
    ITEM_PREP_TIME_UPDATE: 'item_prep_time_update',
    ITEM_PROMOTION_WEIGHT_UPDATE: 'item_promotion_weight_update',
    ITEM_METADATA_UPDATE: 'item_metadata_update',
    ITEM_METADATA_GENERATE: 'item_metadata_generate',
    ITEM_TRANSLATION_REPAIR: 'item_translation_repair',
    ITEM_IMAGE_UPDATE: 'item_image_update',
    ITEM_ORDER_UPDATE: 'item_order_update',
    ITEM_QUALITY_REVIEW_UPDATE: 'item_quality_review_update',
    ITEM_IDENTITY_REFERENCE: 'item_identity_reference',
    ITEM_DELETE: 'item_delete',
    CATEGORY_CREATE: 'category_create',
    CATEGORY_UPDATE: 'category_update',
    CATEGORY_NAME_UPDATE: 'category_name_update',
    CATEGORY_VISIBILITY_UPDATE: 'category_visibility_update',
    CATEGORY_ICON_UPDATE: 'category_icon_update',
    CATEGORY_IMAGE_UPDATE: 'category_image_update',
    CATEGORY_TIME_SLOT_UPDATE: 'category_time_slot_update',
    CATEGORY_TIME_SLOT_PRESET_CREATE: 'category_time_slot_preset_create',
    CATEGORY_TRANSLATION_REPAIR: 'category_translation_repair',
    CATEGORY_ORDER_UPDATE: 'category_order_update',
    CATEGORY_IDENTITY_REFERENCE: 'category_identity_reference',
    CATEGORY_DELETE: 'category_delete',
    DECISION_BLOCKS_UPDATE: 'decision_blocks_update',
    MENU_SPECIAL_NOTE_UPDATE: 'menu_special_note_update',
    MENU_DESIGN_MOOD_UPDATE: 'menu_design_mood_update',
    MENU_DESIGN_LAYOUT_UPDATE: 'menu_design_layout_update',
    MENU_DESIGN_PRESET_APPLY: 'menu_design_preset_apply',
    MENU_DESIGN_VISIBILITY_UPDATE: 'menu_design_visibility_update',
    MENU_DESIGN_COLOR_UPDATE: 'menu_design_color_update',
    MENU_DESIGN_BACKGROUND_UPDATE: 'menu_design_background_update',
    MENU_DESIGN_SETTINGS_OPEN: 'menu_design_settings_open',
    MENU_TEMP_STATUS_SET: 'menu_temp_status_set',
    MENU_TEMP_STATUS_CLEAR: 'menu_temp_status_clear',
    BULK_PRICE_UPDATE: 'bulk_price_update',
    BULK_AVAILABILITY_UPDATE: 'bulk_availability_update',
    IMAGE_ITEM_GENERATE: 'image_item_generate',
    IMAGE_ITEM_APPLY_GENERATED: 'image_item_apply_generated',
    MENU_FILE_UPLOAD: 'menu_file_upload',
    MENU_LINK_IMPORT: 'menu_link_import',
    MENU_IMPORT_REVIEW_APPLY: 'menu_import_review_apply',
    SPECIAL_MENU_CREATE: 'special_menu_create',
    SPECIAL_MENU_ACTIVATE: 'special_menu_activate',
    MENU_PUBLISH: 'menu_publish',
    MENU_QR_DOWNLOAD: 'menu_qr_download',
    MENU_SHARE_COPY_LINK: 'menu_share_copy_link',
    STORE_BUSINESS_PROFILE_UPDATE: 'store_business_profile_update',
    STORE_LOCALE_REGION_UPDATE: 'store_locale_region_update',
    STORE_WORKING_HOURS_UPDATE: 'store_working_hours_update',
    STORE_TIME_SLOT_PRESET_CREATE: 'store_time_slot_preset_create',
    STORE_TIME_SLOT_PRESET_UPDATE: 'store_time_slot_preset_update',
    STORE_TIME_SLOT_PRESET_DELETE: 'store_time_slot_preset_delete',
    STORE_ADDRESS_CONTACT_UPDATE: 'store_address_contact_update',
    PUBLIC_PRESENCE_TEXT_UPDATE: 'public_presence_text_update',
    PUBLIC_PRESENCE_LINK_UPDATE: 'public_presence_link_update',
    PUBLIC_PRESENCE_LINK_SHARE: 'public_presence_link_share',
    PUBLIC_PRESENCE_QR_DOWNLOAD: 'public_presence_qr_download',
    PUBLIC_PRESENCE_SOCIAL_LINKS_UPDATE: 'public_presence_social_links_update',
    PUBLIC_PRESENCE_BUSINESS_ATTRIBUTES_UPDATE: 'public_presence_business_attributes_update',
    PUBLIC_PRESENCE_BUSINESS_COPY_GENERATE: 'public_presence_business_copy_generate',
    SEO_SETTINGS_UPDATE: 'seo_settings_update',
    ANALYTICS_TRACKING_UPDATE: 'analytics_tracking_update',
    DOMAIN_SUBDOMAIN_UPDATE: 'domain_subdomain_update',
    CUSTOMER_APP_SETTINGS_UPDATE: 'customer_app_settings_update',
    CUSTOMER_APP_ICON_UPDATE: 'customer_app_icon_update',
    CUSTOMER_APP_INSTALL_LINK_SHARE: 'customer_app_install_link_share',
    DIGITAL_SCREEN_STATUS_CARD: 'digital_screen_status_card',
    DIGITAL_SCREEN_LINK_SHARE: 'digital_screen_link_share',
    DIGITAL_SCREEN_OVERRIDE_UPDATE: 'digital_screen_override_update',
    DIGITAL_SCREEN_SLIDE_UPLOAD: 'digital_screen_slide_upload',
    FEEDBACK_INBOX_LIST: 'feedback_inbox_list',
    FEEDBACK_REPLY_SAVE: 'feedback_reply_save',
    FEEDBACK_LINK_SHARE: 'feedback_link_share',
    FEEDBACK_QR_DOWNLOAD: 'feedback_qr_download',
    POS_SYNC_SETTINGS_UPDATE: 'pos_sync_settings_update',
    POS_SYNC_SETUP_INFO_COPY: 'pos_sync_setup_info_copy',
    POS_SYNC_TECHNICAL_SUMMARY_COPY: 'pos_sync_technical_summary_copy',
    POS_SYNC_SAMPLE_PAYLOAD_DOWNLOAD: 'pos_sync_sample_payload_download',
    INTEGRATION_STATUS_REVIEW: 'integration_status_review',
    LOCATIONS_SCREEN_OPEN: 'locations_screen_open',
    STAFF_ACCESS_OPEN: 'staff_access_open',
    ROLES_PERMISSIONS_OPEN: 'roles_permissions_open',
    BILLING_SCREEN_OPEN: 'billing_screen_open',
    TRANSACTIONS_SCREEN_OPEN: 'transactions_screen_open',
    BUSINESS_HEALTH_OPEN: 'business_health_open',
    PAST_ACTIVITY_OPEN: 'past_activity_open',
    PRINT_ASSETS_OPEN: 'print_assets_open',
    PRINT_MENU_OPEN: 'print_menu_open',
    HELP_SCREEN_OPEN: 'help_screen_open',
    SYSTEM_MANUAL_TASK_CREATE: 'system_manual_task_create',
    SYSTEM_CONTEXT_ANSWER: 'system_context_answer',
    SYSTEM_CLARIFICATION_REQUEST: 'system_clarification_request',
    SYSTEM_UNSUPPORTED_ACTION: 'system_unsupported_action',
} as const satisfies Record<string, AiMenuManagerActionType>;

export const AI_MENU_MANAGER_EXECUTABLE_ACTIONS: AiMenuManagerActionType[] = [
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_PRICE_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_NAME_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_CATEGORY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_AVAILABILITY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_VISIBILITY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_BESTSELLER_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.ITEM_PREP_TIME_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_NAME_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_VISIBILITY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.DECISION_BLOCKS_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.MENU_SPECIAL_NOTE_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_MOOD_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_LAYOUT_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_PRESET_APPLY,
    AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_VISIBILITY_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_COLOR_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.BULK_PRICE_UPDATE,
    AI_MENU_MANAGER_ACTION_TYPES.BULK_AVAILABILITY_UPDATE,
];

export type AiMenuManagerFieldHandling =
    | 'direct_project_patch'
    | 'existing_api_job'
    | 'manual_task'
    | 'read_only'
    | 'system_protected';

export const AI_MENU_MANAGER_CATEGORY_FIELD_ACTION_COVERAGE = [
    { field: 'id', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_IDENTITY_REFERENCE, handling: 'system_protected' },
    { field: 'active', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_VISIBILITY_UPDATE, handling: 'direct_project_patch' },
    { field: 'name', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_NAME_UPDATE, handling: 'direct_project_patch' },
    { field: 'extractionIdAliases', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_IDENTITY_REFERENCE, handling: 'system_protected' },
    { field: 'icon', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_ICON_UPDATE, handling: 'direct_project_patch' },
    { field: 'images', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_IMAGE_UPDATE, handling: 'manual_task' },
    { field: 'timeSlots', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_TIME_SLOT_UPDATE, handling: 'direct_project_patch' },
    { field: 'orderIndex', actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_ORDER_UPDATE, handling: 'direct_project_patch' },
] as const satisfies ReadonlyArray<{
    field: string;
    actionType: AiMenuManagerActionType;
    handling: AiMenuManagerFieldHandling;
}>;

export const AI_MENU_MANAGER_ATTRIBUTE_FIELD_ACTION_COVERAGE = [
    { field: 'id', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IDENTITY_REFERENCE, handling: 'system_protected' },
    { field: 'name', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_NAME_UPDATE, handling: 'direct_project_patch' },
    { field: 'price', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_PRICE_UPDATE, handling: 'direct_project_patch' },
    { field: 'active', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_VISIBILITY_UPDATE, handling: 'direct_project_patch' },
    { field: 'orderIndex', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_ORDER_UPDATE, handling: 'direct_project_patch' },
] as const satisfies ReadonlyArray<{
    field: string;
    actionType: AiMenuManagerActionType;
    handling: AiMenuManagerFieldHandling;
}>;

export const AI_MENU_MANAGER_ITEM_FIELD_ACTION_COVERAGE = [
    { field: 'id', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IDENTITY_REFERENCE, handling: 'system_protected' },
    { field: 'extractionIdAliases', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IDENTITY_REFERENCE, handling: 'system_protected' },
    { field: 'attributes', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_UPDATE, handling: 'direct_project_patch' },
    { field: 'category', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_CATEGORY_UPDATE, handling: 'direct_project_patch' },
    { field: 'name', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_NAME_UPDATE, handling: 'direct_project_patch' },
    { field: 'description', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_UPDATE, handling: 'direct_project_patch' },
    { field: 'descriptionSource', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_UPDATE, handling: 'system_protected' },
    { field: 'price', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PRICE_UPDATE, handling: 'direct_project_patch' },
    { field: 'images', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IMAGE_UPDATE, handling: 'manual_task' },
    { field: 'tags', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'active', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_VISIBILITY_UPDATE, handling: 'direct_project_patch' },
    { field: 'available', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_AVAILABILITY_UPDATE, handling: 'direct_project_patch' },
    { field: 'isBestSeller', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_BESTSELLER_UPDATE, handling: 'direct_project_patch' },
    { field: 'decisionFacts', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'allergens', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'dietaryTags', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'spiceLevel', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'nutritionInfo', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'skillLevel', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'targetAudience', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'materials', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'warranty', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE, handling: 'direct_project_patch' },
    { field: 'duration', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PREP_TIME_UPDATE, handling: 'direct_project_patch' },
    { field: 'ownerBoost', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PROMOTION_WEIGHT_UPDATE, handling: 'direct_project_patch' },
    { field: 'orderIndex', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ORDER_UPDATE, handling: 'direct_project_patch' },
    { field: 'qualityReview', actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_QUALITY_REVIEW_UPDATE, handling: 'direct_project_patch' },
] as const satisfies ReadonlyArray<{
    field: string;
    actionType: AiMenuManagerActionType;
    handling: AiMenuManagerFieldHandling;
}>;

export const AI_MENU_MANAGER_ACTION_DEFINITIONS: AiMenuManagerActionDefinition[] = [
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PRICE_UPDATE,
        ownerLabel: 'Update price',
        manualEquivalent: 'Item price field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:351'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_CREATE,
        ownerLabel: 'Add item',
        manualEquivalent: 'Add item in menu editor',
        executionMode: 'manual_task_card',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/utils/editorOperations.ts:64'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_UPDATE,
        ownerLabel: 'Update item details',
        manualEquivalent: 'Edit item modal save',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:554'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_NAME_UPDATE,
        ownerLabel: 'Rename item',
        manualEquivalent: 'Item name field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:351'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_UPDATE,
        ownerLabel: 'Update item description',
        manualEquivalent: 'Item description field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:351'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_GENERATE,
        ownerLabel: 'Generate item description',
        manualEquivalent: 'Item metadata/description generation',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Draft card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:496'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DESCRIPTION_REFRESH,
        ownerLabel: 'Refresh item descriptions',
        manualEquivalent: 'Description generation modal',
        executionMode: 'existing_api_job',
        approvalLevel: 'bulk_confirm',
        risk: 'high',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Summary card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/DescriptionGenerationModal.tsx'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_CATEGORY_UPDATE,
        ownerLabel: 'Move item to category',
        manualEquivalent: 'Item category selector',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:57'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_AVAILABILITY_UPDATE,
        ownerLabel: 'Update availability',
        manualEquivalent: 'Availability toggle',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:673'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_VISIBILITY_UPDATE,
        ownerLabel: 'Show or hide item',
        manualEquivalent: 'Item active field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:673'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_CREATE,
        ownerLabel: 'Add item variation',
        manualEquivalent: 'Attribute add helper',
        executionMode: 'manual_task_card',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:425'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_UPDATE,
        ownerLabel: 'Update item variation',
        manualEquivalent: 'Attribute field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:351'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_DELETE,
        ownerLabel: 'Delete item variation',
        manualEquivalent: 'Attribute delete helper',
        executionMode: 'manual_task_card',
        approvalLevel: 'destructive_confirm',
        risk: 'high',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/utils/editorOperations.ts:212'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_NAME_UPDATE,
        ownerLabel: 'Rename item variation',
        manualEquivalent: 'Attribute name field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:373'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_PRICE_UPDATE,
        ownerLabel: 'Update variation price',
        manualEquivalent: 'Attribute price field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:387'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_VISIBILITY_UPDATE,
        ownerLabel: 'Show or hide variation',
        manualEquivalent: 'Attribute active toggle',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/components/mobile/sheets/ItemEditSheet.tsx:821'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ATTRIBUTE_ORDER_UPDATE,
        ownerLabel: 'Reorder item variations',
        manualEquivalent: 'Attribute order in item editor',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/sheets/ItemEditSheet.tsx:637'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_BESTSELLER_UPDATE,
        ownerLabel: 'Update bestseller flag',
        manualEquivalent: 'Best Seller toggle',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:696'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PREP_TIME_UPDATE,
        ownerLabel: 'Update prep or service time',
        manualEquivalent: 'Prep time field',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:727'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_PROMOTION_WEIGHT_UPDATE,
        ownerLabel: 'Update promotion weight',
        manualEquivalent: 'Promotion slider',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:747'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_UPDATE,
        ownerLabel: 'Update item details',
        manualEquivalent: 'Business-aware item detail fields',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:769'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_METADATA_GENERATE,
        ownerLabel: 'Generate item details',
        manualEquivalent: 'New item metadata API',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Draft card',
        sourceEvidence: ['src/app/api/new-item-metadata/route.ts'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_TRANSLATION_REPAIR,
        ownerLabel: 'Repair item translation',
        manualEquivalent: 'Retry item translation',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Draft card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editItemModal.tsx:402'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IMAGE_UPDATE,
        ownerLabel: 'Update item image',
        manualEquivalent: 'Item image upload/apply flow',
        executionMode: 'manual_task_card',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C5 manual only',
        mobileBehavior: 'Image task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/uploadedImagesList.tsx'],
        readiness: 'manual_task_only',
        requiredFlags: ['ENABLE_AI_MENU_MANAGER_IMAGE_ACTIONS'],
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_ORDER_UPDATE,
        ownerLabel: 'Reorder item',
        manualEquivalent: 'Reorder menu modal',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/ReorderMenuModal.tsx:200'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_QUALITY_REVIEW_UPDATE,
        ownerLabel: 'Mark item review checked',
        manualEquivalent: 'Price warning review marker',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/components/mobile/screens/MobileMenuScreen.tsx:995'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_IDENTITY_REFERENCE,
        ownerLabel: 'Read item identity',
        manualEquivalent: 'System item identity reference',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Read-only card',
        sourceEvidence: ['src/components/templates/main-app/projects/types/extractedData.types.ts:70'],
        readiness: 'blocked',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ITEM_DELETE,
        ownerLabel: 'Delete item',
        manualEquivalent: 'Item delete confirmation',
        executionMode: 'manual_task_card',
        approvalLevel: 'destructive_confirm',
        risk: 'high',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Destructive task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/utils/editorOperations.ts:191'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_CREATE,
        ownerLabel: 'Add category',
        manualEquivalent: 'Create category helper',
        executionMode: 'manual_task_card',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/utils/editorOperations.ts:28'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_UPDATE,
        ownerLabel: 'Update category',
        manualEquivalent: 'Category modal save',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:219'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_NAME_UPDATE,
        ownerLabel: 'Rename category',
        manualEquivalent: 'Category name field edit',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:584'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_VISIBILITY_UPDATE,
        ownerLabel: 'Show or hide category',
        manualEquivalent: 'Category active toggle',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: [
            'src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:437',
            'src/components/mobile/screens/MobileMenuScreen.tsx:3450',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_ICON_UPDATE,
        ownerLabel: 'Update category icon',
        manualEquivalent: 'Category icon picker',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:448'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_IMAGE_UPDATE,
        ownerLabel: 'Update category image',
        manualEquivalent: 'Category image data field',
        executionMode: 'manual_task_card',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/types/extractedData.types.ts:35'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_TIME_SLOT_UPDATE,
        ownerLabel: 'Update category time slot',
        manualEquivalent: 'Category time-slot controls',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:131'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_TIME_SLOT_PRESET_CREATE,
        ownerLabel: 'Create category time preset',
        manualEquivalent: 'Create time slot preset',
        executionMode: 'existing_client_dal',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/editCategoryModal.tsx:166'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_TRANSLATION_REPAIR,
        ownerLabel: 'Repair category translations',
        manualEquivalent: 'Category translation generation',
        executionMode: 'existing_api_job',
        approvalLevel: 'bulk_confirm',
        risk: 'high',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Summary card',
        sourceEvidence: ['src/components/templates/main-app/projects/utils/translationsUtils.ts:396'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_ORDER_UPDATE,
        ownerLabel: 'Reorder category',
        manualEquivalent: 'Reorder menu modal',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/ReorderMenuModal.tsx:190'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_IDENTITY_REFERENCE,
        ownerLabel: 'Read category identity',
        manualEquivalent: 'System category identity reference',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Read-only card',
        sourceEvidence: ['src/components/templates/main-app/projects/types/extractedData.types.ts:30'],
        readiness: 'blocked',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CATEGORY_DELETE,
        ownerLabel: 'Delete category',
        manualEquivalent: 'Category delete confirmation',
        executionMode: 'manual_task_card',
        approvalLevel: 'destructive_confirm',
        risk: 'high',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Destructive task card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/utils/editorOperations.ts:160'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.DECISION_BLOCKS_UPDATE,
        ownerLabel: 'Update Featured section',
        manualEquivalent: 'Featured section settings',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: [
            'src/components/templates/main-app/projects/editorView/DecisionBlocksSettingsModal.tsx:243',
            'src/components/templates/main-app/projects/editorView/decisionBlocks.shared.ts:191',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_SPECIAL_NOTE_UPDATE,
        ownerLabel: 'Update menu note',
        manualEquivalent: 'Menu page settings special note',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/components/templates/main-app/projects/b2cView/menuPage/menuPageSettingsNew.tsx:211'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_MOOD_UPDATE,
        ownerLabel: 'Update presentation tone',
        manualEquivalent: 'Menu design presentation tone',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: [
            'src/components/templates/main-app/projects/b2cView/menuPage/menuPageSettingsNew.tsx:75',
            'src/components/mobile/screens/MobileDesignEditorScreen.tsx:520',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_LAYOUT_UPDATE,
        ownerLabel: 'Update menu layout',
        manualEquivalent: 'Menu design item layout',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: [
            'src/components/templates/main-app/projects/b2cView/menuPage/menuPageSettingsNew.tsx:92',
            'src/components/mobile/screens/MobileDesignEditorScreen.tsx:546',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_PRESET_APPLY,
        ownerLabel: 'Apply menu style preset',
        manualEquivalent: 'Menu design preset',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: [
            'src/components/templates/main-app/projects/b2cView/menuPage/menuPageSettingsNew.tsx:110',
            'src/components/mobile/screens/MobileDesignEditorScreen.tsx:485',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_VISIBILITY_UPDATE,
        ownerLabel: 'Update menu display option',
        manualEquivalent: 'Menu design display options',
        executionMode: 'client_project_mutation',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: [
            'src/components/templates/main-app/projects/b2cView/menuPage/menuPageSettingsNew.tsx:131',
            'src/components/mobile/screens/MobileDesignEditorScreen.tsx:607',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_COLOR_UPDATE,
        ownerLabel: 'Update theme color',
        manualEquivalent: 'Menu design theme color',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: [
            'src/components/templates/main-app/projects/b2cView/designSystem/BrandColorPicker.tsx:67',
            'src/components/mobile/screens/MobileDesignEditorScreen.tsx:583',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.BULK_PRICE_UPDATE,
        ownerLabel: 'Bulk price update',
        manualEquivalent: 'Menu Command Center bulk pricing',
        executionMode: 'client_project_mutation',
        approvalLevel: 'bulk_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Summary card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/CommandCenterModal/utils/bulkOperations.ts:130'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.BULK_AVAILABILITY_UPDATE,
        ownerLabel: 'Bulk availability update',
        manualEquivalent: 'Menu Command Center bulk availability',
        executionMode: 'client_project_mutation',
        approvalLevel: 'bulk_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Summary card',
        sourceEvidence: ['src/components/templates/main-app/projects/editorView/CommandCenterModal/utils/bulkOperations.ts:316'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.IMAGE_ITEM_GENERATE,
        ownerLabel: 'Generate item image',
        manualEquivalent: 'AI Image Generator',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Draft card',
        sourceEvidence: [
            'src/app/api/image-generation/route.ts',
            'src/components/templates/main-app/projects/editorView/AiImageGenerator/index.tsx',
        ],
        readiness: 'existing_api_only',
        requiredFlags: ['ENABLE_AI_MENU_MANAGER_IMAGE_ACTIONS'],
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.IMAGE_ITEM_APPLY_GENERATED,
        ownerLabel: 'Use generated image',
        manualEquivalent: 'Apply generated image to item',
        executionMode: 'client_project_mutation',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C1 single project save',
        mobileBehavior: 'Image/card approve',
        sourceEvidence: [
            'src/components/templates/main-app/projects/editorView/editItemModal.tsx:351',
            'src/lib/ai-menu-manager/actions/projectPatches.ts',
        ],
        readiness: 'needs_adapter_glue',
        requiredFlags: ['ENABLE_AI_MENU_MANAGER_IMAGE_ACTIONS'],
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_FILE_UPLOAD,
        ownerLabel: 'Upload menu file',
        manualEquivalent: 'Menu extraction upload',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Upload card',
        sourceEvidence: ['src/components/templates/main-app/projects/index.tsx:1737'],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_LINK_IMPORT,
        ownerLabel: 'Import menu link',
        manualEquivalent: 'Menu link import',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Upload card',
        sourceEvidence: ['src/components/templates/main-app/projects/index.tsx:1737'],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_IMPORT_REVIEW_APPLY,
        ownerLabel: 'Apply reviewed import',
        manualEquivalent: 'Menu extraction review apply',
        executionMode: 'client_project_mutation',
        approvalLevel: 'bulk_confirm',
        risk: 'high',
        costClass: 'C1 single project save',
        mobileBehavior: 'Review card',
        sourceEvidence: [
            'src/components/templates/main-app/projects/jobScreens/ExtractionJobReviewScreen.tsx:304',
            'src/lib/extraction/applyChanges.ts:422',
        ],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SPECIAL_MENU_CREATE,
        ownerLabel: 'Create special menu',
        manualEquivalent: 'Special menu create',
        executionMode: 'existing_api_job',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Native mobile screen',
        sourceEvidence: [
            'src/hooks/useSpecialMenus.ts:127',
            'src/database/projects/index.ts:2234',
        ],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SPECIAL_MENU_ACTIVATE,
        ownerLabel: 'Activate special menu',
        manualEquivalent: 'Special menu activation',
        executionMode: 'existing_api_job',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Native mobile screen',
        sourceEvidence: [
            'src/hooks/useSpecialMenus.ts:223',
            'src/database/projects/index.ts:2547',
        ],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_PUBLISH,
        ownerLabel: 'Publish menu',
        manualEquivalent: 'Publish/share menu flow',
        executionMode: 'existing_api_job',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/database/projects/index.ts:1315'],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_SHARE_COPY_LINK,
        ownerLabel: 'Copy menu link',
        manualEquivalent: 'Share modal copy URL',
        executionMode: 'browser_local_export',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Share card',
        sourceEvidence: [
            'src/components/templates/main-app/projects/b2cView/shareModal/index.tsx:479',
            'src/components/mobile/screens/MobileShareScreen.tsx:1257',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_QR_DOWNLOAD,
        ownerLabel: 'Download menu QR',
        manualEquivalent: 'Share modal QR download',
        executionMode: 'browser_local_export',
        approvalLevel: 'external_confirm',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Download card',
        sourceEvidence: [
            'src/components/templates/main-app/projects/b2cView/shareModal/index.tsx:143',
            'src/components/mobile/screens/MobileShareScreen.tsx:1272',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_BACKGROUND_UPDATE,
        ownerLabel: 'Update menu background',
        manualEquivalent: 'Menu design background image setting',
        executionMode: 'manual_task_card',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/templates/main-app/projects/b2cView/menuPage/menuPageSettingsNew.tsx:195'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_DESIGN_SETTINGS_OPEN,
        ownerLabel: 'Open menu design',
        manualEquivalent: 'Existing Menu Design screen',
        executionMode: 'manual_task_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileDesignEditorScreen.tsx'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_TEMP_STATUS_SET,
        ownerLabel: 'Set temporary status',
        manualEquivalent: 'Temporary status API',
        executionMode: 'existing_server_api',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C4 guarded server mutation',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/app/api/store/temp-status/route.ts:43'],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.MENU_TEMP_STATUS_CLEAR,
        ownerLabel: 'Clear temporary status',
        manualEquivalent: 'Temporary status clear API',
        executionMode: 'existing_server_api',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C4 guarded server mutation',
        mobileBehavior: 'Fast card',
        sourceEvidence: ['src/app/api/store/temp-status/route.ts:103'],
        readiness: 'existing_api_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.STORE_BUSINESS_PROFILE_UPDATE,
        ownerLabel: 'Update business profile',
        manualEquivalent: 'Mobile basic settings save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileBasicSettingsScreen.tsx:149'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.STORE_LOCALE_REGION_UPDATE,
        ownerLabel: 'Update language and region',
        manualEquivalent: 'Mobile locale settings save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileLocaleSettingsScreen.tsx:150'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.STORE_WORKING_HOURS_UPDATE,
        ownerLabel: 'Update working hours',
        manualEquivalent: 'Working hours store save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileHoursScreen.tsx:294'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.STORE_TIME_SLOT_PRESET_CREATE,
        ownerLabel: 'Create time slot preset',
        manualEquivalent: 'Mobile time slot preset create',
        executionMode: 'existing_client_dal',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileTimeSlotsScreen.tsx:101'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.STORE_TIME_SLOT_PRESET_UPDATE,
        ownerLabel: 'Update time slot preset',
        manualEquivalent: 'Mobile time slot preset update',
        executionMode: 'existing_client_dal',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileTimeSlotsScreen.tsx:101'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.STORE_TIME_SLOT_PRESET_DELETE,
        ownerLabel: 'Delete time slot preset',
        manualEquivalent: 'Mobile time slot preset delete',
        executionMode: 'existing_client_dal',
        approvalLevel: 'destructive_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileTimeSlotsScreen.tsx:212'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.STORE_ADDRESS_CONTACT_UPDATE,
        ownerLabel: 'Update address and contact',
        manualEquivalent: 'Store profile address/contact save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/database/stores/index.tsx:375'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.PUBLIC_PRESENCE_TEXT_UPDATE,
        ownerLabel: 'Update official page text',
        manualEquivalent: 'Official Page text fields',
        executionMode: 'existing_client_dal',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/businessSettings/tabs/OfficialPageTab.tsx:578'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.PUBLIC_PRESENCE_LINK_UPDATE,
        ownerLabel: 'Update official page links',
        manualEquivalent: 'Official Page link fields',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/templates/main-app/businessSettings/tabs/OfficialPageTab.tsx:702'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.PUBLIC_PRESENCE_LINK_SHARE,
        ownerLabel: 'Copy official page link',
        manualEquivalent: 'Mobile share official page copy link',
        executionMode: 'browser_local_export',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Share card',
        sourceEvidence: ['src/components/mobile/screens/MobileShareScreen.tsx:1225'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.PUBLIC_PRESENCE_QR_DOWNLOAD,
        ownerLabel: 'Download official page QR',
        manualEquivalent: 'Mobile share official page QR',
        executionMode: 'browser_local_export',
        approvalLevel: 'external_confirm',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Download card',
        sourceEvidence: ['src/components/mobile/screens/MobileShareScreen.tsx:1240'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.PUBLIC_PRESENCE_SOCIAL_LINKS_UPDATE,
        ownerLabel: 'Update social links',
        manualEquivalent: 'Mobile social settings save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileAdvancedSettingsScreen.tsx:407'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.PUBLIC_PRESENCE_BUSINESS_ATTRIBUTES_UPDATE,
        ownerLabel: 'Update business attributes',
        manualEquivalent: 'Mobile business attributes save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileBusinessAttributesScreen.tsx:36'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.PUBLIC_PRESENCE_BUSINESS_COPY_GENERATE,
        ownerLabel: 'Generate business copy',
        manualEquivalent: 'Mobile business copy generation',
        executionMode: 'existing_api_job',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Draft card',
        sourceEvidence: ['src/components/mobile/screens/MobileBusinessCopySetupScreen.tsx:82'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SEO_SETTINGS_UPDATE,
        ownerLabel: 'Update SEO settings',
        manualEquivalent: 'Mobile SEO settings save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileSeoAnalyticsScreen.tsx:476'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ANALYTICS_TRACKING_UPDATE,
        ownerLabel: 'Update analytics tracking',
        manualEquivalent: 'Mobile analytics settings save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileSeoAnalyticsScreen.tsx:425'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.DOMAIN_SUBDOMAIN_UPDATE,
        ownerLabel: 'Update public link',
        manualEquivalent: 'Domain/subdomain settings',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileDomainSettingsScreen.tsx:145'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CUSTOMER_APP_SETTINGS_UPDATE,
        ownerLabel: 'Update customer app settings',
        manualEquivalent: 'Mobile customer app settings save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileCustomerAppScreen.tsx:131'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CUSTOMER_APP_ICON_UPDATE,
        ownerLabel: 'Update customer app icon',
        manualEquivalent: 'Mobile customer app icon flow',
        executionMode: 'existing_client_dal',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Image/card approve',
        sourceEvidence: ['src/components/mobile/screens/MobileCustomerAppScreen.tsx:170'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.CUSTOMER_APP_INSTALL_LINK_SHARE,
        ownerLabel: 'Share customer app install link',
        manualEquivalent: 'Customer app install link copy/share',
        executionMode: 'browser_local_export',
        approvalLevel: 'external_confirm',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Copy/open/download card',
        sourceEvidence: [
            'src/components/mobile/screens/MobileCustomerAppScreen.tsx:281',
            'src/components/mobile/screens/MobileShareScreen.tsx:1277',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.DIGITAL_SCREEN_STATUS_CARD,
        ownerLabel: 'Show screen status',
        manualEquivalent: 'Digital Screens status screen',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Status card',
        sourceEvidence: ['src/components/mobile/screens/MobileDigitalScreensScreen.tsx:224'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.DIGITAL_SCREEN_LINK_SHARE,
        ownerLabel: 'Share digital screen link',
        manualEquivalent: 'Digital screen copy/open actions',
        executionMode: 'browser_local_export',
        approvalLevel: 'external_confirm',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Share card',
        sourceEvidence: [
            'src/components/mobile/screens/MobileDigitalScreensScreen.tsx:390',
            'src/components/mobile/screens/MobileShareScreen.tsx:1584',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.DIGITAL_SCREEN_OVERRIDE_UPDATE,
        ownerLabel: 'Update digital screen override',
        manualEquivalent: 'Digital screen override settings',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileDigitalScreensScreen.tsx:260'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.DIGITAL_SCREEN_SLIDE_UPLOAD,
        ownerLabel: 'Update digital screen slides',
        manualEquivalent: 'Digital screen slide upload flow',
        executionMode: 'existing_client_dal',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C2 job/storage',
        mobileBehavior: 'Upload card',
        sourceEvidence: ['src/components/mobile/screens/MobileDigitalScreensScreen.tsx:305'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.FEEDBACK_INBOX_LIST,
        ownerLabel: 'Open feedback inbox',
        manualEquivalent: 'Mobile feedback list',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Summary card',
        sourceEvidence: ['src/components/mobile/screens/MobileFeedbackScreen.tsx:56'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.FEEDBACK_REPLY_SAVE,
        ownerLabel: 'Prepare feedback reply',
        manualEquivalent: 'Mobile feedback reply save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'confirm',
        risk: 'medium',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobileFeedbackDetail.tsx:40'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.FEEDBACK_LINK_SHARE,
        ownerLabel: 'Share feedback link',
        manualEquivalent: 'Mobile feedback link copy/share',
        executionMode: 'browser_local_export',
        approvalLevel: 'external_confirm',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Copy/open/download card',
        sourceEvidence: [
            'src/components/mobile/screens/MobileFeedbackScreen.tsx:110',
            'src/components/mobile/screens/MobileShareScreen.tsx:1305',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.FEEDBACK_QR_DOWNLOAD,
        ownerLabel: 'Download feedback QR',
        manualEquivalent: 'Mobile feedback QR download',
        executionMode: 'browser_local_export',
        approvalLevel: 'external_confirm',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Download/copy card',
        sourceEvidence: [
            'src/components/mobile/screens/MobileFeedbackScreen.tsx:302',
            'src/components/mobile/screens/MobileShareScreen.tsx:826',
        ],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.POS_SYNC_SETTINGS_UPDATE,
        ownerLabel: 'Update POS sync settings',
        manualEquivalent: 'Mobile POS sync settings save',
        executionMode: 'existing_client_dal',
        approvalLevel: 'high_confirm',
        risk: 'high',
        costClass: 'C3 summary/store write',
        mobileBehavior: 'Card approve/edit',
        sourceEvidence: ['src/components/mobile/screens/MobilePosSyncScreen.tsx:133'],
        readiness: 'needs_adapter_glue',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.POS_SYNC_SETUP_INFO_COPY,
        ownerLabel: 'Copy POS setup details',
        manualEquivalent: 'Mobile POS setup info copy',
        executionMode: 'browser_local_export',
        approvalLevel: 'external_confirm',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Copy card',
        sourceEvidence: ['src/components/mobile/screens/MobileShareScreen.tsx:866'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.POS_SYNC_TECHNICAL_SUMMARY_COPY,
        ownerLabel: 'Copy POS technical summary',
        manualEquivalent: 'Desktop POS technical summary copy',
        executionMode: 'browser_local_export',
        approvalLevel: 'external_confirm',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Copy card',
        sourceEvidence: ['src/components/templates/main-app/businessSettings/tabs/PosSyncTab.tsx:338'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.POS_SYNC_SAMPLE_PAYLOAD_DOWNLOAD,
        ownerLabel: 'Download POS sample payload',
        manualEquivalent: 'Desktop POS sample payload download',
        executionMode: 'browser_local_export',
        approvalLevel: 'external_confirm',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Download card',
        sourceEvidence: ['src/components/templates/main-app/businessSettings/tabs/PosSyncTab.tsx:343'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.INTEGRATION_STATUS_REVIEW,
        ownerLabel: 'Show integration status',
        manualEquivalent: 'Mobile integrations status screen',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Status card',
        sourceEvidence: ['src/components/mobile/screens/MobileIntegrationsScreen.tsx:89'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.LOCATIONS_SCREEN_OPEN,
        ownerLabel: 'Open locations',
        manualEquivalent: 'Existing Locations screen',
        executionMode: 'manual_task_card',
        approvalLevel: 'none',
        risk: 'medium',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileMoreScreen.tsx:492'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.STAFF_ACCESS_OPEN,
        ownerLabel: 'Open staff access',
        manualEquivalent: 'Existing Staff screen',
        executionMode: 'manual_task_card',
        approvalLevel: 'none',
        risk: 'high',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileMoreScreen.tsx:492'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.ROLES_PERMISSIONS_OPEN,
        ownerLabel: 'Open roles and permissions',
        manualEquivalent: 'Existing Roles & Permissions screen',
        executionMode: 'manual_task_card',
        approvalLevel: 'none',
        risk: 'high',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileMoreScreen.tsx:492'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.BILLING_SCREEN_OPEN,
        ownerLabel: 'Open billing',
        manualEquivalent: 'Existing Billing screen',
        executionMode: 'manual_task_card',
        approvalLevel: 'none',
        risk: 'high',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileMoreScreen.tsx:492'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.TRANSACTIONS_SCREEN_OPEN,
        ownerLabel: 'Open transactions',
        manualEquivalent: 'Existing Transactions screen',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'medium',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileMoreScreen.tsx:492'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.BUSINESS_HEALTH_OPEN,
        ownerLabel: 'Open Business Health',
        manualEquivalent: 'Existing Business Health screen',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileMoreScreen.tsx:492'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.PAST_ACTIVITY_OPEN,
        ownerLabel: 'Open past activity',
        manualEquivalent: 'Existing Past Activity screen',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileMoreScreen.tsx:492'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.PRINT_ASSETS_OPEN,
        ownerLabel: 'Open print assets',
        manualEquivalent: 'Existing Assets screen',
        executionMode: 'manual_task_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileShareScreen.tsx:608'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.PRINT_MENU_OPEN,
        ownerLabel: 'Open print menu',
        manualEquivalent: 'Existing Print Menu flow',
        executionMode: 'manual_task_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/hooks/useMenuCardExportController.ts:494'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.HELP_SCREEN_OPEN,
        ownerLabel: 'Open help',
        manualEquivalent: 'Existing Help screen',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C5 manual only',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/components/mobile/screens/MobileMoreScreen.tsx:492'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SYSTEM_MANUAL_TASK_CREATE,
        ownerLabel: 'Create manual task',
        manualEquivalent: 'Manual checklist/export task',
        executionMode: 'manual_task_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'Compact proposal/session write',
        mobileBehavior: 'Task card',
        sourceEvidence: ['src/lib/ai-menu-manager/cardBuilder.ts'],
        readiness: 'manual_task_only',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SYSTEM_CONTEXT_ANSWER,
        ownerLabel: 'Answer from MenuList context',
        manualEquivalent: 'Read current selected menu context',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C0 local plus compact session doc',
        mobileBehavior: 'Answer card',
        sourceEvidence: ['src/lib/ai-menu-manager/domainConversationRouter.ts'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SYSTEM_CLARIFICATION_REQUEST,
        ownerLabel: 'Ask a question',
        manualEquivalent: 'Clarify before editing',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'low',
        costClass: 'C0 local',
        mobileBehavior: 'Conversation card',
        sourceEvidence: ['src/lib/ai-menu-manager/cardBuilder.ts'],
        readiness: 'ready_adapter',
    },
    {
        actionType: AI_MENU_MANAGER_ACTION_TYPES.SYSTEM_UNSUPPORTED_ACTION,
        ownerLabel: 'Unsupported external action',
        manualEquivalent: 'No supported MenuList operation',
        executionMode: 'read_only_card',
        approvalLevel: 'none',
        risk: 'high',
        costClass: 'C0 local plus compact session doc',
        mobileBehavior: 'Unsupported card',
        sourceEvidence: ['src/lib/ai-menu-manager/cardBuilder.ts'],
        readiness: 'ready_adapter',
    },
];

export const AI_MENU_MANAGER_ACTION_DEFINITION_BY_TYPE: Record<AiMenuManagerActionType, AiMenuManagerActionDefinition> =
    Object.fromEntries(AI_MENU_MANAGER_ACTION_DEFINITIONS.map((definition) => [definition.actionType, definition])) as Record<AiMenuManagerActionType, AiMenuManagerActionDefinition>;
