'use client'

import MessageBubble from './MessageBubble';
import SuggestedQuestions from './SuggestedQuestions';
import { ChatState } from './chatState';
import { ChatMessage } from './types';

interface MessageListProps {
    messages: ChatMessage[];
    conversationSearchQuery: string;
    chatState?: ChatState;
    messageFeedback?: Record<string, 'up' | 'down' | null>;
    onCopy?: (messageId: string) => void;
    onRegenerate?: (messageId: string) => void;
    onFeedback?: (messageId: string, type: 'up' | 'down') => void;
    onSkipTyping?: () => void;
    onSendMessage: (message: string) => void;
    mode?: 'qna' | 'assistant';
    onStartFollowUp?: () => void;
    onEscalate?: (message: ChatMessage) => void;
}

/**
 * Get AI-generated suggested questions for the last assistant message
 * Questions are now generated by Gemini during answer generation for better context awareness
 */
function getSuggestedQuestions(
    message: ChatMessage,
    messageIndex: number,
    allMessages: ChatMessage[]
): string[] {
    // Only show suggestions for the last assistant message
    const isLastMessage = messageIndex === allMessages.length - 1;
    if (!isLastMessage) return [];

    // Return AI-generated questions if available
    // Otherwise return empty array (no fallback - let AI handle it)
    return message.suggestedQuestions || [];
}

const MessageList = ({
    messages,
    conversationSearchQuery,
    chatState,
    messageFeedback,
    onCopy,
    onRegenerate,
    onFeedback,
    onSkipTyping,
    onSendMessage,
    mode,
    onStartFollowUp,
    onEscalate
}: MessageListProps) => {
    // Handler for suggested question clicks
    // Automatically switches to assistant mode if in QnA mode (follow-up context)
    const handleSuggestedQuestionClick = (question: string) => {
        if (mode === 'qna' && onStartFollowUp) {
            // ✅ FIX: Switch UI to assistant mode AND pass mode to onSendMessage
            // This avoids React state race condition
            onStartFollowUp();

            // Pass 'assistant' mode explicitly to ensure DB update
            // @ts-ignore - targetMode parameter added to fix race condition
            onSendMessage(question, undefined, 'assistant');
        } else {
            onSendMessage(question);
        }
    };

    const displayMessages = messages;

    return (
        <div style={{ maxWidth: 900, margin: '0 auto' }}>
            {/* Filter messages based on search query */}
            {displayMessages
                .filter((message) => {
                    if (!conversationSearchQuery) return true;

                    // Word-by-word matching (like LocalSearchResults)
                    const queryWords = conversationSearchQuery.toLowerCase().split(' ').filter(Boolean);
                    const messageText = (message.content || message.craftedAnswer || '').toLowerCase();

                    // Match if ANY word from query is found in message
                    return queryWords.some(word => messageText.includes(word));
                })
                .map((message, messageIndex, filteredMessages) => {
                    const isTypingMessage = chatState?.typingMessageId === message.id;

                    // Use feedback from message data (persisted) or local state (temporary)
                    const feedbackState = message.feedback?.isGood
                        ? 'up'
                        : message.feedback?.isGood === false
                            ? 'down'
                            : messageFeedback?.[message.id];

                    // Get AI-generated suggested questions for assistant messages
                    // Don't show during typing animation
                    const suggestedQuestions = message.role === 'assistant' && !isTypingMessage
                        ? getSuggestedQuestions(message, messageIndex, filteredMessages)
                        : [];

                    return (
                        <div key={message.id}>
                            <MessageBubble
                                message={message}
                                onCopy={() => onCopy?.(message.id)}
                                onRegenerate={() => onRegenerate?.(message.id)}
                                onFeedback={(type) => onFeedback?.(message.id, type)}
                                isTyping={isTypingMessage}
                                onSkipTyping={isTypingMessage ? onSkipTyping : undefined}
                                feedbackState={feedbackState}
                                searchQuery={conversationSearchQuery}
                                onEscalate={message.escalation?.suggested ? () => onEscalate?.(message) : undefined}
                            />
                            {/* Suggested follow-up questions */}
                            {suggestedQuestions.length > 0 && (
                                <SuggestedQuestions
                                    questions={suggestedQuestions}
                                    onQuestionClick={handleSuggestedQuestionClick}
                                    disabled={chatState?.status === 'loading' || chatState?.status === 'typing'}
                                />
                            )}
                        </div>
                    );
                })}
        </div>
    );
};

export default MessageList;
