export {
    NEELVARA_LOCAL_DEV_PATH_PREFIX as NEELVARA_LOCAL_PATH_PREFIX,
    NEELVARA_PRODUCTION_DOMAINS,
    NEELVARA_STAGING_DOMAINS,
} from '@constant/neelvara/domains';

export {
    NEELVARA_ANSWERLATTICE_URL,
    NEELVARA_CONTACT_EMAIL,
    NEELVARA_LEGAL_EMAIL,
    NEELVARA_LOGO_PATH,
    NEELVARA_MENULIST_URL,
    NEELVARA_OG_IMAGE_PATH,
    NEELVARA_PRIVACY_EMAIL,
    NEELVARA_PRODUCT_LINEUP,
    NEELVARA_PUBLIC_PAGES,
    NEELVARA_RELATIONSHIP_LINE,
    NEELVARA_SITE_DESCRIPTION,
    NEELVARA_SITE_TITLE,
    NEELVARA_SITE_URL,
    buildNeelvaraUrl,
} from '@constant/neelvara/website';
