export const SIGNALDESK_COLLECTIONS = {
  SYSTEM: "_system",
  APPROVAL_PACKETS: "signaldeskApprovalPackets",
  APPROVAL_QUEUE: "signaldeskApprovalQueue",
  AI_WORKER_RUNS: "signaldeskAiWorkerRuns",
  AUDIT_EVENTS: "signaldeskAuditEvents",
  CONTACT_IDENTITIES: "signaldeskContactIdentities",
  CHANNEL_WINDOW_STATES: "signaldeskChannelWindowStates",
  CONTENT_ASSETS: "signaldeskContentAssets",
  CONTENT_CALENDAR_ITEMS: "signaldeskContentCalendarItems",
  CONTENT_DISTRIBUTION_DRAFTS: "signaldeskContentDistributionDrafts",
  CONTROL_ROOM_SUMMARIES: "signaldeskControlRoomSummaries",
  CONVERSATION_SUMMARIES: "signaldeskConversationSummaries",
  COST_DAILY_SUMMARIES: "signaldeskCostDailySummaries",
  DRAFT_SUMMARIES: "signaldeskDraftSummaries",
  DECISION_SNAPSHOTS: "signaldeskDecisionSnapshots",
  ENRICHMENT_RESULTS: "signaldeskEnrichmentResults",
  EVIDENCE_PACKETS: "signaldeskEvidencePackets",
  EVIDENCE_PACKET_SUMMARIES: "signaldeskEvidencePacketSummaries",
  IDEMPOTENCY_KEYS: "signaldeskIdempotencyKeys",
  INCIDENTS: "signaldeskIncidents",
  KILL_SWITCHES: "signaldeskKillSwitches",
  MESSAGES: "signaldeskMessages",
  MESSAGE_EXPORTS: "signaldeskMessageExports",
  OUTCOME_EVENTS: "signaldeskOutcomeEvents",
  OUTCOME_SUMMARIES: "signaldeskOutcomeSummaries",
  PROOF_PERMISSIONS: "signaldeskProofPermissions",
  PROVIDER_SOURCE_RETENTION: "signaldeskProviderSourceRetention",
  QUEUE_SUMMARIES: "signaldeskQueueSummaries",
  REPLY_CLASSIFICATIONS: "signaldeskReplyClassifications",
  RESEARCH_TABLE_ROWS: "signaldeskResearchTableRows",
  ROUTE_TOKENS: "signaldeskRouteTokens",
  RUN_TIMELINES: "signaldeskRunTimelines",
  SEQUENCER_HANDOFFS: "signaldeskSequencerHandoffs",
  SEQUENCER_STEPS: "signaldeskSequencerSteps",
  SOURCE_CANDIDATES: "signaldeskSourceCandidates",
  SOURCE_POLICIES: "signaldeskSourcePolicies",
  SOURCE_RUN_SUMMARIES: "signaldeskSourceRunSummaries",
  SUPPRESSION_LEDGER: "signaldeskSuppressionLedger",
  TARGETS: "signaldeskTargets",
  TARGET_SUMMARIES: "signaldeskTargetSummaries",
  VENDOR_RUNS: "signaldeskVendorRuns",
  REVENUE_ACCOUNTS: "signaldeskRevenueAccounts",
  COMMERCIAL_OPPORTUNITIES: "signaldeskCommercialOpportunities",
  REVENUE_CONTROL_SUMMARIES: "signaldeskRevenueControlSummaries",
  WEBHOOK_EVENTS: "signaldeskWebhookEvents",
} as const;

export const SIGNALDESK_SUMMARY_DOCS = {
  CONTROL_ROOM: "dashboard",
  QUEUES: "current",
  REVENUE: "current",
} as const;
