export const FUNCTION_FLAGS = {
  ENABLE_SIGNALDESK_HEALTH_CHECK: true,
  ENABLE_SIGNALDESK_PROVIDER_WEBHOOKS: false,
  ENABLE_SIGNALDESK_AI_WORKERS: false,
  ENABLE_SIGNALDESK_SCHEDULED_SUMMARIES: false,
} as const;
