export { default as AnalyticsTab } from "./AnalyticsTab";
export { default as BasicInfoTab } from "./BasicInfoTab";
export { default as BusinessCopySetupTab } from "./BusinessCopySetupTab";
export { default as BusinessAttributesTab } from "./BusinessAttributesTab";
export { default as ContactPersonTab } from "./ContactPersonTab";
export { default as CustomDomainTab } from "./CustomDomainTab";
export { default as CustomerAppTab } from "./CustomerAppTab";
export { default as DomainSettingsTab } from "./DomainSettingsTab";
export { default as FeedbackSettingsTab } from "./FeedbackSettingsTab";
export { default as IntegrationsTab } from "./IntegrationsTab";
export { default as LocaleSettingsTab } from "./LocaleSettingsTab";
export { default as LocationInfoTab } from "./LocationInfoTab";
export { default as OfficialPageTab } from "./OfficialPageTab";
export { default as PosSyncTab } from "./PosSyncTab";
export { default as SeoTab } from "./SeoTab";
export { default as SocialMediaTab } from "./SocialMediaTab";
// T3-N-02: SubdomainTab removed — superseded by DomainSettingsTab (G-08).
export { default as TimeSlotPresetsTab } from "./TimeSlotPresetsTab";
export { default as WorkingHoursTab } from "./WorkingHoursTab";
