import { Alert, Space, Typography } from 'antd';
import React from 'react';

const { Text, Paragraph } = Typography;

const AiDisclaimerAlert: React.FC = () => {
    return (
        <Alert
            type="info"
            showIcon
            style={{ margin: '16px 0' }}
            message={<Text strong>AI-Powered Feature Disclaimer</Text>}
            description={
                <Space direction="vertical" style={{ width: '100%' }}>
                    <Paragraph>
                        Please be aware that several features within this project, such as content generation (descriptions, menu items), image creation, and language translation, are powered by AI. While we strive for accuracy and relevance, please note the following:
                    </Paragraph>

                    <ul style={{ margin: 0, paddingLeft: '20px' }}>
                        <li>
                            <Text>Outputs from these features (text, images, translations) are AI-assisted and may not be solely human-created.</Text>
                        </li>
                        <li>
                            <Text>AI models can make mistakes. Always carefully review and verify all generated content.</Text>
                        </li>
                        <li>
                            <Text>Inaccuracies, inconsistencies, or unexpected results may occur in text, images, or translations.</Text>
                        </li>
                        <li>
                            <Text>AI might occasionally produce plausible-sounding but incorrect or inappropriate information.</Text>
                        </li>
                        <li>
                            <Text>It is crucial to verify all critical details: prices, ingredients, allergen information, visual representations in images, and the contextual accuracy of translations.</Text>
                        </li>
                        <li>
                            <Text>Do not rely on responses generated by MenuListAi as medical, legal, financial, or other professional advice.</Text>
                        </li>
                    </ul>

                    <Paragraph style={{ marginBottom: 0 }}>
                        We strongly recommend thoroughly reviewing, editing, and validating all AI-generated outputs before publishing or relying on them to ensure they accurately meet your needs and standards.
                    </Paragraph>
                </Space>
            }
        />
    );
};

export default AiDisclaimerAlert;
