'use client';

import { LuCheck, LuDatabase, LuLock, LuShield, LuUserCheck, LuUsers } from 'react-icons/lu';
import AnimateOnScroll, { AnimateStaggerChild } from '../shared/AnimateOnScroll';
import SectionHeading from '../shared/SectionHeading';
import SectionWrapper from '../shared/SectionWrapper';
import WebsiteButton from '../shared/WebsiteButton';
import WebsiteHeadline from '../shared/WebsiteHeadline';

const dataCollected = [
    {
        icon: LuUserCheck,
        title: 'Information you provide',
        desc: 'Data you voluntarily give us when you register and use our services.',
        points: [
            'Account information: Name, email address, and business details when you register',
            'Staff account information: Staff name, email or phone number, Staff ID alias, role, store assignment, and account status when a business adds team access',
            'Business content: Menus, price lists, images, and documents you upload',
            'Payment information: Processed securely through Razorpay — we never store credit card details',
        ],
    },
    {
        icon: LuDatabase,
        title: 'Content generated on your behalf',
        desc: 'We store content generated by our system on your behalf, including images and product descriptions, to provide the service to you.',
        points: [
            'Your content is private — we do not use it to train our models',
            'Your intellectual property remains yours',
            'Generated assets belong to you',
        ],
    },
    {
        icon: LuShield,
        title: 'Automatically collected information',
        desc: 'When you use our services, we automatically collect technical data to improve our platform.',
        points: [
            'IP address, browser type, and operating system',
            'Device information and usage analytics',
            'Authentication and security events, including access checks, reset requests, and session revocation metadata',
            'Menu analytics do not collect customer identities; optional feedback may include contact details a guest chooses to provide',
        ],
    },
];

const howWeUse = [
    { label: 'Provide services', value: 'Process your content and generate assets' },
    { label: 'Customer support', value: 'Manage your account and assist you' },
    { label: 'Communications', value: 'Send important updates and policy changes' },
    { label: 'Staff access control', value: 'Create staff access, apply roles, reset passcodes, and revoke sessions' },
    { label: 'Improve platform', value: 'Analyse usage to enhance features' },
    { label: 'Security', value: 'Detect and prevent fraud and abuse' },
    { label: 'Legal compliance', value: 'Comply with laws and regulations' },
];

const securityMeasures = [
    {
        icon: LuLock,
        title: 'Encryption',
        desc: 'All data is protected both at rest and in transit using industry-standard encryption.',
        points: [
            'AES-256 encryption at rest',
            'TLS 1.2/1.3 encryption in transit',
        ],
    },
    {
        icon: LuShield,
        title: 'Infrastructure security',
        desc: 'Built on Google Cloud with continuous monitoring and regular audits.',
        points: [
            '24/7 security operations',
            'Regular security audits',
        ],
    },
    {
        icon: LuUserCheck,
        title: 'Access controls',
        desc: 'Owner and staff access is controlled through roles, store assignments, account status, and session checks.',
        points: [
            'Owners can assign staff roles and store access',
            'Owners can reset staff passcodes or sign out staff sessions',
            'MenuList does not store plain-text staff passcodes',
        ],
    },
];

const privacyRights = [
    { label: 'Right to access', value: 'Request a copy of your personal data' },
    { label: 'Right to correction', value: 'Update inaccurate or incomplete data' },
    { label: 'Right to deletion', value: 'Request deletion of your personal data' },
    { label: 'Right to portability', value: 'Receive your data in a machine-readable format' },
    { label: 'Right to object', value: 'Object to certain data processing' },
    { label: 'Right to withdraw consent', value: 'Withdraw consent for data processing' },
];

export default function PrivacyPolicyPage() {
    const lastUpdated = 'May 19, 2026';

    return (
        <div className="ws-page">
            {/* Hero */}
            <section style={{ padding: 'var(--ws-space-24) var(--ws-space-6) var(--ws-space-16)', backgroundColor: 'var(--ws-bg-primary)', textAlign: 'center' }}>
                <div className="ws-container" style={{ maxWidth: 'var(--ws-max-w-text)' }}>
                    <AnimateOnScroll>
                        <p style={{ fontSize: '0.8125rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: 0, color: 'var(--ws-brand-secondary)', marginBottom: 'var(--ws-space-4)' }}>
                            Privacy Policy
                        </p>
                        <WebsiteHeadline
                            as="h1"
                            parts={[
                                { text: 'How we handle ' },
                                { text: 'your data.', highlight: true },
                            ]}
                        />
                        <p className="ws-body" style={{ marginTop: 'var(--ws-space-6)', maxWidth: '580px', marginLeft: 'auto', marginRight: 'auto' }}>
                            Your privacy matters. This policy explains what we collect, why, and how we protect it.
                        </p>
                        <p className="ws-caption" style={{ marginTop: 'var(--ws-space-4)' }}>
                            Last updated: {lastUpdated} · Questions? Contact us at{' '}
                            <a href="mailto:privacy@menulist.ai" style={{ color: 'var(--ws-brand-secondary)', textDecoration: 'none', fontWeight: 500 }}>privacy@menulist.ai</a>
                        </p>
                    </AnimateOnScroll>
                </div>
            </section>

            {/* Information We Collect */}
            <SectionWrapper variant="subtle">
                <AnimateOnScroll>
                    <SectionHeading
                        title="Information we collect"
                        subtitle="What data we gather and how it reaches us."
                    />
                </AnimateOnScroll>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: 'var(--ws-space-6)', marginTop: 'var(--ws-space-12)', maxWidth: '960px', marginLeft: 'auto', marginRight: 'auto' }}>
                    {dataCollected.map((item, i) => {
                        const Icon = item.icon;
                        return (
                            <AnimateStaggerChild key={item.title} index={i}>
                                <div className="ws-card" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ws-space-4)', height: '100%' }}>
                                    <div style={{ display: 'flex', gap: 'var(--ws-space-4)', alignItems: 'flex-start' }}>
                                        <div style={{ width: '44px', height: '44px', borderRadius: 'var(--ws-radius-md)', backgroundColor: 'var(--ws-bg-accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                                            <Icon size={22} color="var(--ws-brand-secondary)" />
                                        </div>
                                        <div>
                                            <h3 style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--ws-text-primary)' }}>{item.title}</h3>
                                            <p className="ws-caption" style={{ marginTop: 'var(--ws-space-2)' }}>{item.desc}</p>
                                        </div>
                                    </div>
                                    <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 'var(--ws-space-2)', borderTop: '1px solid var(--ws-border-subtle)', paddingTop: 'var(--ws-space-3)' }}>
                                        {item.points.map((point) => (
                                            <li key={point} style={{ display: 'flex', gap: 'var(--ws-space-2)', alignItems: 'flex-start' }}>
                                                <LuCheck size={14} color="var(--ws-success)" style={{ flexShrink: 0, marginTop: '3px' }} />
                                                <span style={{ fontSize: '0.875rem', color: 'var(--ws-text-secondary)' }}>{point}</span>
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </AnimateStaggerChild>
                        );
                    })}
                </div>
            </SectionWrapper>

            {/* How We Use */}
            <SectionWrapper variant="default">
                <AnimateOnScroll>
                    <SectionHeading
                        title="How we use your information"
                        subtitle="We use the data we collect for these purposes — nothing more."
                    />
                </AnimateOnScroll>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: 'var(--ws-space-3)', marginTop: 'var(--ws-space-10)', maxWidth: '900px', marginLeft: 'auto', marginRight: 'auto' }}>
                    {howWeUse.map((fact, i) => (
                        <AnimateStaggerChild key={fact.label} index={i}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', padding: 'var(--ws-space-4) var(--ws-space-5)', backgroundColor: 'var(--ws-bg-primary)', borderRadius: 'var(--ws-radius-lg)', border: '1px solid var(--ws-border-default)', gap: 'var(--ws-space-4)' }}>
                                <span style={{ fontSize: '0.9375rem', color: 'var(--ws-text-secondary)', flex: 1 }}>{fact.label}</span>
                                <span style={{ fontSize: '0.875rem', fontWeight: 600, color: 'var(--ws-text-primary)', textAlign: 'right', flexShrink: 0, maxWidth: '220px' }}>{fact.value}</span>
                            </div>
                        </AnimateStaggerChild>
                    ))}
                </div>
            </SectionWrapper>

            {/* Data Sharing */}
            <SectionWrapper variant="subtle">
                <AnimateOnScroll>
                    <SectionHeading
                        title="How we share your information"
                        subtitle="We never sell your data. Here is who else may access it and why."
                    />
                </AnimateOnScroll>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(420px, 1fr))', gap: 'var(--ws-space-6)', marginTop: 'var(--ws-space-12)', maxWidth: '960px', marginLeft: 'auto', marginRight: 'auto' }}>
                    <AnimateStaggerChild index={0}>
                        <div className="ws-card" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ws-space-4)' }}>
                            <div style={{ display: 'flex', gap: 'var(--ws-space-4)', alignItems: 'flex-start' }}>
                                <div style={{ width: '44px', height: '44px', borderRadius: 'var(--ws-radius-md)', backgroundColor: 'var(--ws-bg-accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                                    <LuUserCheck size={22} color="var(--ws-brand-secondary)" />
                                </div>
                                <div>
                                    <h3 style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--ws-text-primary)' }}>Service providers</h3>
                                    <p className="ws-caption" style={{ marginTop: 'var(--ws-space-2)' }}>We share data with trusted vendors who help us operate the platform.</p>
                                </div>
                            </div>
                            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 'var(--ws-space-2)', borderTop: '1px solid var(--ws-border-subtle)', paddingTop: 'var(--ws-space-3)' }}>
                                {['Payment processing (Razorpay) — PCI-compliant and secure', 'Cloud hosting (Vercel, Google Cloud, Firebase)', 'Content generation (Google Gemini) — under strict confidentiality agreements'].map((p) => (
                                    <li key={p} style={{ display: 'flex', gap: 'var(--ws-space-2)', alignItems: 'flex-start' }}>
                                        <LuCheck size={14} color="var(--ws-success)" style={{ flexShrink: 0, marginTop: '3px' }} />
                                        <span style={{ fontSize: '0.875rem', color: 'var(--ws-text-secondary)' }}>{p}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </AnimateStaggerChild>
                    <AnimateStaggerChild index={1}>
                        <div className="ws-card" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ws-space-4)' }}>
                            <div style={{ display: 'flex', gap: 'var(--ws-space-4)', alignItems: 'flex-start' }}>
                                <div style={{ width: '44px', height: '44px', borderRadius: 'var(--ws-radius-md)', backgroundColor: 'var(--ws-bg-accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                                    <LuShield size={22} color="var(--ws-brand-secondary)" />
                                </div>
                                <div>
                                    <h3 style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--ws-text-primary)' }}>Legal requirements</h3>
                                    <p className="ws-caption" style={{ marginTop: 'var(--ws-space-2)' }}>We may disclose your information when legally required to comply with court orders, subpoenas, or applicable law.</p>
                                </div>
                            </div>
                            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 'var(--ws-space-2)', borderTop: '1px solid var(--ws-border-subtle)', paddingTop: 'var(--ws-space-3)' }}>
                                {['We never sell, rent, or trade your personal information', 'Data is shared only when strictly necessary for service operation', 'All third parties operate under confidentiality agreements'].map((p) => (
                                    <li key={p} style={{ display: 'flex', gap: 'var(--ws-space-2)', alignItems: 'flex-start' }}>
                                        <LuCheck size={14} color="var(--ws-success)" style={{ flexShrink: 0, marginTop: '3px' }} />
                                        <span style={{ fontSize: '0.875rem', color: 'var(--ws-text-secondary)' }}>{p}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </AnimateStaggerChild>
                    <AnimateStaggerChild index={2}>
                        <div className="ws-card" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ws-space-4)' }}>
                            <div style={{ display: 'flex', gap: 'var(--ws-space-4)', alignItems: 'flex-start' }}>
                                <div style={{ width: '44px', height: '44px', borderRadius: 'var(--ws-radius-md)', backgroundColor: 'var(--ws-bg-accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                                    <LuUsers size={22} color="var(--ws-brand-secondary)" />
                                </div>
                                <div>
                                    <h3 style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--ws-text-primary)' }}>Authorized team access</h3>
                                    <p className="ws-caption" style={{ marginTop: 'var(--ws-space-2)' }}>Owners may give staff access to the business account. Staff can see only the areas their assigned role allows.</p>
                                </div>
                            </div>
                            <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 'var(--ws-space-2)', borderTop: '1px solid var(--ws-border-subtle)', paddingTop: 'var(--ws-space-3)' }}>
                                {['Staff access is controlled by the business owner', 'Role and store assignments limit what staff can access', 'Owners should remove, deactivate, or sign out staff when access is no longer needed'].map((p) => (
                                    <li key={p} style={{ display: 'flex', gap: 'var(--ws-space-2)', alignItems: 'flex-start' }}>
                                        <LuCheck size={14} color="var(--ws-success)" style={{ flexShrink: 0, marginTop: '3px' }} />
                                        <span style={{ fontSize: '0.875rem', color: 'var(--ws-text-secondary)' }}>{p}</span>
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </AnimateStaggerChild>
                </div>
            </SectionWrapper>

            {/* Data Security */}
            <SectionWrapper variant="default">
                <AnimateOnScroll>
                    <SectionHeading
                        title="Data security"
                        subtitle="Industry-standard measures to protect your information."
                    />
                </AnimateOnScroll>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(420px, 1fr))', gap: 'var(--ws-space-6)', marginTop: 'var(--ws-space-12)', maxWidth: '960px', marginLeft: 'auto', marginRight: 'auto' }}>
                    {securityMeasures.map((item, i) => {
                        const Icon = item.icon;
                        return (
                            <AnimateStaggerChild key={item.title} index={i}>
                                <div className="ws-card" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ws-space-4)' }}>
                                    <div style={{ display: 'flex', gap: 'var(--ws-space-4)', alignItems: 'flex-start' }}>
                                        <div style={{ width: '44px', height: '44px', borderRadius: 'var(--ws-radius-md)', backgroundColor: 'var(--ws-bg-accent)', display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 }}>
                                            <Icon size={22} color="var(--ws-brand-secondary)" />
                                        </div>
                                        <div>
                                            <h3 style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--ws-text-primary)' }}>{item.title}</h3>
                                            <p className="ws-caption" style={{ marginTop: 'var(--ws-space-2)' }}>{item.desc}</p>
                                        </div>
                                    </div>
                                    <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: 'var(--ws-space-2)', borderTop: '1px solid var(--ws-border-subtle)', paddingTop: 'var(--ws-space-3)' }}>
                                        {item.points.map((point) => (
                                            <li key={point} style={{ display: 'flex', gap: 'var(--ws-space-2)', alignItems: 'flex-start' }}>
                                                <LuCheck size={14} color="var(--ws-success)" style={{ flexShrink: 0, marginTop: '3px' }} />
                                                <span style={{ fontSize: '0.875rem', color: 'var(--ws-text-secondary)' }}>{point}</span>
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </AnimateStaggerChild>
                        );
                    })}
                </div>
            </SectionWrapper>

            {/* Privacy Rights */}
            <SectionWrapper variant="subtle">
                <AnimateOnScroll>
                    <SectionHeading
                        title="Your privacy rights"
                        subtitle="Depending on your location, you may have the following rights under applicable data protection laws."
                    />
                </AnimateOnScroll>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(400px, 1fr))', gap: 'var(--ws-space-3)', marginTop: 'var(--ws-space-10)', maxWidth: '900px', marginLeft: 'auto', marginRight: 'auto' }}>
                    {privacyRights.map((right, i) => (
                        <AnimateStaggerChild key={right.label} index={i}>
                            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', padding: 'var(--ws-space-4) var(--ws-space-5)', backgroundColor: 'var(--ws-bg-primary)', borderRadius: 'var(--ws-radius-lg)', border: '1px solid var(--ws-border-default)', gap: 'var(--ws-space-4)' }}>
                                <span style={{ fontSize: '0.9375rem', color: 'var(--ws-text-secondary)', flex: 1 }}>{right.label}</span>
                                <span style={{ fontSize: '0.875rem', fontWeight: 600, color: 'var(--ws-text-primary)', textAlign: 'right', flexShrink: 0, maxWidth: '220px' }}>{right.value}</span>
                            </div>
                        </AnimateStaggerChild>
                    ))}
                </div>
                <AnimateOnScroll>
                    <p style={{ textAlign: 'center', marginTop: 'var(--ws-space-8)', fontSize: '0.9375rem', color: 'var(--ws-text-secondary)' }}>
                        To exercise your rights, contact us at{' '}
                        <a href="mailto:privacy@menulist.ai" style={{ color: 'var(--ws-brand-secondary)', textDecoration: 'none', fontWeight: 500 }}>privacy@menulist.ai</a>
                    </p>
                </AnimateOnScroll>
            </SectionWrapper>

            {/* CTA */}
            <SectionWrapper variant="default">
                <AnimateOnScroll>
                    <div style={{ textAlign: 'center', maxWidth: 'var(--ws-max-w-text)', margin: '0 auto' }}>
                        <WebsiteHeadline as="h2" text="Your privacy is built in." />
                        <p className="ws-body" style={{ marginTop: 'var(--ws-space-4)' }}>
                            Privacy is not a feature we added — it is how the system was designed.
                        </p>
                        <div style={{ marginTop: 'var(--ws-space-8)' }}>
                            <WebsiteButton href="/create-menu">Upload your menu →</WebsiteButton>
                        </div>
                    </div>
                </AnimateOnScroll>
            </SectionWrapper>
        </div>
    );
}
